import type { TestCase } from "../types.js";

export const appShellTestCases: TestCase[] = [
  {
    id: "TC-APP-001",
    feature: "APP",
    featureDoc: "app-shell.md",
    title: "Application boots with REST layout and empty request state",
    type: "functional",
    priority: "P0",
    preconditions: ["Fresh browser session (localStorage cleared)", "Dev server at /"],
    steps: [
      { order: 1, action: "navigate", input: "/", expected: "Page loads without error" },
      {
        order: 2,
        action: "verify",
        elementId: "EL-RB-001",
        expected: "URL input visible with placeholder",
      },
      {
        order: 3,
        action: "verify",
        elementId: "EL-RV-001",
        expected: "Response empty state visible",
      },
      {
        order: 4,
        action: "verify",
        elementId: "EL-SID-003",
        expected: "History tab visible in sidebar",
      },
    ],
    expectedResult: "Full REST shell renders: header, sidebar, tab strip, URL bar, response panel",
    elementIds: ["EL-RB-001", "EL-RV-001", "EL-SID-003", "EL-APP-003"],
    automation: {
      status: "covered",
      spec: "e2e/smoke.spec.ts",
      testName: "app boots with the shell",
    },
    tags: ["smoke", "boot"],
  },
  {
    id: "TC-APP-002",
    feature: "APP",
    featureDoc: "app-shell.md",
    title: "Sidebar collapses and expands without layout break",
    type: "ux",
    priority: "P0",
    preconditions: ["REST workspace active"],
    steps: [
      {
        order: 1,
        action: "click",
        elementId: "EL-SID-006",
        expected: "Sidebar hides; expand button appears",
      },
      {
        order: 2,
        action: "click",
        elementId: "EL-SID-007",
        expected: "Sidebar restores; History/Draft/Collections visible",
      },
      {
        order: 3,
        action: "verify",
        elementId: "EL-RB-001",
        expected: "URL bar still aligned; no horizontal page overflow",
      },
    ],
    expectedResult: "Sidebar toggle is reversible with stable main-panel layout",
    elementIds: ["EL-SID-006", "EL-SID-007", "EL-RB-001"],
    automation: {
      status: "covered",
      spec: "e2e/smoke.spec.ts",
      testName: "sidebar collapses and expands",
    },
    tags: ["sidebar", "layout"],
  },
  {
    id: "TC-APP-003",
    feature: "APP",
    featureDoc: "app-shell.md",
    title: "Response panel resize handle adjusts split and double-click resets",
    type: "ux",
    priority: "P1",
    preconditions: ["Request with response visible"],
    steps: [
      {
        order: 1,
        action: "drag",
        elementId: "EL-APP-010",
        expected: "Request/response split moves",
      },
      {
        order: 2,
        action: "verify",
        elementId: "EL-RV-004",
        expected: "Response body remains reachable after resize",
      },
      {
        order: 3,
        action: "dblclick",
        elementId: "EL-APP-010",
        expected: "Split returns to default ratio",
      },
    ],
    expectedResult: "Panel resize is smooth and resettable",
    elementIds: ["EL-APP-010", "EL-RV-004"],
    automation: {
      status: "covered",
      spec: "e2e/smoke.spec.ts",
      testName: "response resize keeps the panel reachable",
    },
    tags: ["layout", "resize"],
  },
  {
    id: "TC-APP-004",
    feature: "APP",
    featureDoc: "app-shell.md",
    title: "Production environment shows red indicator in header",
    type: "ui",
    priority: "P1",
    preconditions: ["At least one environment marked Production"],
    steps: [
      { order: 1, action: "click", elementId: "EL-ENV-003", expected: "Environment manager opens" },
      {
        order: 2,
        action: "check",
        elementId: "EL-ENV-005",
        expected: "Production checkbox checked",
      },
      { order: 3, action: "click", elementId: "EL-ENV-009", expected: "Environment set active" },
      {
        order: 4,
        action: "verify",
        elementId: "EL-APP-008",
        expected: "Red production indicator visible in header",
      },
    ],
    expectedResult: "Active production env triggers persistent red visual cues",
    elementIds: ["EL-ENV-003", "EL-ENV-005", "EL-ENV-009", "EL-APP-008"],
    automation: {
      status: "partial",
      spec: "e2e/environments.spec.ts",
      testName: "marking an environment production shows red cues",
    },
    tags: ["environment", "production", "visual"],
  },
  {
    id: "TC-APP-005",
    feature: "APP",
    featureDoc: "app-shell.md",
    title: "Modal Escape dismisses topmost overlay without closing app",
    type: "ux",
    priority: "P1",
    preconditions: ["Settings or Import modal open"],
    steps: [
      { order: 1, action: "click", elementId: "EL-APP-007", expected: "Settings drawer opens" },
      { order: 2, action: "keyboard", input: "Escape", expected: "Settings closes" },
      {
        order: 3,
        action: "verify",
        elementId: "EL-RB-001",
        expected: "Request editor still visible and focused area restored",
      },
    ],
    expectedResult: "Escape closes overlay stack correctly",
    elementIds: ["EL-APP-007", "EL-RB-001"],
    automation: { status: "partial", spec: "e2e/settings-theme.spec.ts" },
    tags: ["modal", "keyboard", "escape"],
  },
];

export const workspaceTestCases: TestCase[] = [
  {
    id: "TC-WS-001",
    feature: "WS",
    featureDoc: "workspaces.md",
    title: "MCP header button opens coming-soon page in-place",
    type: "functional",
    priority: "P1",
    preconditions: ["REST workspace with open tabs"],
    steps: [
      {
        order: 1,
        action: "click",
        elementId: "EL-APP-004",
        expected: "MCP coming-soon page replaces workspace",
      },
      {
        order: 2,
        action: "verify",
        elementId: "EL-WS-001",
        expected: "Coming soon message visible",
      },
      { order: 3, action: "verify", elementId: "EL-SID-001", expected: "Sidebar hidden" },
      { order: 4, action: "verify", elementId: "EL-TAB-001", expected: "Tab strip hidden" },
    ],
    expectedResult: "MCP swaps in-place; no new browser tab; REST chrome hidden",
    elementIds: ["EL-APP-004", "EL-WS-001", "EL-SID-001", "EL-TAB-001"],
    automation: {
      status: "covered",
      spec: "e2e/find-and-kind-tabs.spec.ts",
      testName: "MCP opens in-place",
    },
    tags: ["workspace", "mcp", "coming-soon"],
  },
  {
    id: "TC-WS-002",
    feature: "WS",
    featureDoc: "workspaces.md",
    title: "GraphQL workspace opens via header and ⌘⇧G shortcut",
    type: "keyboard",
    priority: "P1",
    preconditions: ["REST workspace active"],
    steps: [
      {
        order: 1,
        action: "click",
        elementId: "EL-APP-005",
        expected: "GraphQL coming-soon visible",
      },
      {
        order: 2,
        action: "keyboard",
        input: "Meta+Shift+R",
        expected: "Returns to REST workspace",
      },
      {
        order: 3,
        action: "keyboard",
        input: "Meta+Shift+G",
        expected: "GraphQL coming-soon visible again",
      },
    ],
    expectedResult: "GraphQL reachable by header and keyboard; REST restores layout",
    elementIds: ["EL-APP-005", "EL-WS-002", "EL-APP-003"],
    automation: {
      status: "covered",
      spec: "e2e/find-and-kind-tabs.spec.ts",
      testName: "GraphQL opens in-place via ⌘⇧G",
    },
    tags: ["workspace", "graphql", "keyboard"],
  },
  {
    id: "TC-WS-003",
    feature: "WS",
    featureDoc: "workspaces.md",
    title: "Header search and Settings remain reachable from coming-soon page",
    type: "ux",
    priority: "P2",
    preconditions: ["MCP coming-soon page active"],
    steps: [
      { order: 1, action: "click", elementId: "EL-APP-004", expected: "On MCP coming-soon" },
      {
        order: 2,
        action: "click",
        elementId: "EL-APP-001",
        expected: "Header search receives focus",
      },
      {
        order: 3,
        action: "click",
        elementId: "EL-APP-007",
        expected: "Settings drawer opens over coming-soon",
      },
    ],
    expectedResult: "Global header actions work from any workspace",
    elementIds: ["EL-APP-001", "EL-APP-007", "EL-WS-001"],
    automation: { status: "missing" },
    tags: ["workspace", "header"],
  },
];

export const sidebarTestCases: TestCase[] = [
  {
    id: "TC-SID-001",
    feature: "SID",
    featureDoc: "sidebar.md",
    title: "New Request creates a fresh GET tab",
    type: "crud",
    priority: "P0",
    preconditions: ["REST workspace"],
    steps: [
      {
        order: 1,
        action: "click",
        elementId: "EL-SID-001",
        expected: "New tab appears in tab strip",
      },
      { order: 2, action: "verify", elementId: "EL-RB-002", expected: "Method defaults to GET" },
      {
        order: 3,
        action: "verify",
        elementId: "EL-RB-011",
        expected: "Send disabled until URL entered",
      },
    ],
    expectedResult: "New Request opens editable empty tab",
    elementIds: ["EL-SID-001", "EL-RB-002", "EL-RB-011", "EL-TAB-002"],
    automation: {
      status: "covered",
      spec: "e2e/shortcuts.spec.ts",
      testName: "⌘N opens a new tab",
    },
    tags: ["sidebar", "tabs", "create"],
  },
  {
    id: "TC-SID-002",
    feature: "SID",
    featureDoc: "sidebar.md",
    title: "Import modal opens from sidebar and supports cURL mode",
    type: "functional",
    priority: "P1",
    preconditions: ["REST workspace"],
    steps: [
      { order: 1, action: "click", elementId: "EL-SID-002", expected: "Import modal opens" },
      { order: 2, action: "verify", elementId: "EL-IE-001", expected: "cURL mode selected" },
      { order: 3, action: "verify", elementId: "EL-IE-003", expected: "cURL textarea visible" },
    ],
    expectedResult: "Import entry point reachable; cURL mode default",
    elementIds: ["EL-SID-002", "EL-IE-001", "EL-IE-003"],
    automation: { status: "covered", spec: "e2e/import-curl.spec.ts" },
    tags: ["sidebar", "import"],
  },
  {
    id: "TC-SID-003",
    feature: "SID",
    featureDoc: "sidebar.md",
    title: "Sidebar tabs switch History, Draft, and Collections content",
    type: "ui",
    priority: "P0",
    preconditions: ["At least one sent request exists"],
    steps: [
      { order: 1, action: "click", elementId: "EL-SID-003", expected: "History list visible" },
      { order: 2, action: "click", elementId: "EL-SID-004", expected: "Draft tree visible" },
      {
        order: 3,
        action: "click",
        elementId: "EL-SID-005",
        expected: "Collections tree or empty CTA visible",
      },
    ],
    expectedResult: "Each sidebar tab shows distinct content panel",
    elementIds: ["EL-SID-003", "EL-SID-004", "EL-SID-005"],
    automation: {
      status: "covered",
      spec: "e2e/smoke.spec.ts",
      testName: "sidebar exposes History / Draft / Collections",
    },
    tags: ["sidebar", "navigation"],
  },
  {
    id: "TC-SID-004",
    feature: "SID",
    featureDoc: "sidebar.md",
    title: "Header search filters History and Draft rows",
    type: "functional",
    priority: "P1",
    preconditions: ["Multiple history entries with distinct URLs"],
    steps: [
      { order: 1, action: "click", elementId: "EL-SID-003", expected: "History tab active" },
      { order: 2, action: "keyboard", input: "Meta+F", expected: "Header search focused" },
      {
        order: 3,
        action: "type",
        elementId: "EL-APP-001",
        input: "posts",
        expected: "Only matching rows remain visible",
      },
      { order: 4, action: "clear", elementId: "EL-APP-001", expected: "Full list restored" },
    ],
    expectedResult: "Search filters sidebar lists in real time",
    elementIds: ["EL-APP-001", "EL-SID-003", "EL-SID-004"],
    automation: { status: "covered", spec: "e2e/sidebar-search.spec.ts" },
    tags: ["search", "sidebar"],
  },
];
