import type { TestCase } from "../types.js";

export const environmentTestCases: TestCase[] = [
  {
    id: "TC-ENV-001",
    feature: "ENV",
    featureDoc: "environments.md",
    title: "Create environment with variable persists across reload",
    type: "crud",
    priority: "P0",
    preconditions: ["No environments"],
    steps: [
      { order: 1, action: "click", elementId: "EL-ENV-003", expected: "Env manager opens" },
      { order: 2, action: "type", input: "Staging", expected: "Env name entered" },
      { order: 3, action: "click", input: "Add", expected: "Env appears in list" },
      { order: 4, action: "type", elementId: "EL-ENV-006", input: "baseUrl", expected: "Key set" },
      {
        order: 5,
        action: "type",
        elementId: "EL-ENV-007",
        input: "https://staging.example.com",
        expected: "Value set",
      },
      { order: 6, action: "reload", expected: "Env and vars still present" },
    ],
    expectedResult: "Environment CRUD persisted",
    elementIds: ["EL-ENV-003", "EL-ENV-006", "EL-ENV-007"],
    automation: {
      status: "covered",
      spec: "e2e/environments.spec.ts",
      testName: "create env + variable, set active, and it persists",
    },
    tags: ["environment", "create", "persistence"],
  },
  {
    id: "TC-ENV-002",
    feature: "ENV",
    featureDoc: "environments.md",
    title: "Switch active environment updates resolved URL values",
    type: "functional",
    priority: "P0",
    preconditions: ["Two envs with different baseUrl"],
    steps: [
      {
        order: 1,
        action: "click",
        elementId: "EL-ENV-009",
        input: "Set Dev active",
        expected: "Header shows Dev",
      },
      {
        order: 2,
        action: "type",
        elementId: "EL-RB-001",
        input: "{{baseUrl}}/users",
        expected: "Token resolves to Dev baseUrl on send",
      },
      {
        order: 3,
        action: "click",
        elementId: "EL-ENV-002",
        input: "Switch to Staging",
        expected: "Same URL resolves to Staging on send",
      },
    ],
    expectedResult: "Active env drives interpolation",
    elementIds: ["EL-ENV-009", "EL-RB-001", "EL-ENV-002"],
    automation: {
      status: "covered",
      spec: "e2e/environments.spec.ts",
      testName: "a defined variable resolves and the request sends",
    },
    tags: ["environment", "switch"],
  },
  {
    id: "TC-ENV-003",
    feature: "ENV",
    featureDoc: "environments.md",
    title: "Hover {{token}} in URL shows resolved value preview",
    type: "ux",
    priority: "P1",
    preconditions: ["Active env with baseUrl; URL contains {{baseUrl}}"],
    steps: [
      {
        order: 1,
        action: "hover",
        elementId: "EL-RB-013",
        expected: "Tooltip shows resolved URL value",
      },
    ],
    expectedResult: "Non-strict preview on hover",
    elementIds: ["EL-RB-013"],
    automation: {
      status: "covered",
      spec: "e2e/environments.spec.ts",
      testName: "hovering a {{token}} in the URL shows its resolved value",
    },
    tags: ["environment", "preview"],
  },
  {
    id: "TC-ENV-004",
    feature: "ENV",
    featureDoc: "environments.md",
    title: "Production env prompts confirm on DELETE/PUT/PATCH",
    type: "ux",
    priority: "P1",
    preconditions: ["Production env active"],
    steps: [
      { order: 1, action: "click", elementId: "EL-RB-007", expected: "DELETE selected" },
      { order: 2, action: "click", elementId: "EL-RB-011", expected: "Confirm dialog appears" },
      {
        order: 3,
        action: "click",
        elementId: "EL-ENV-010",
        input: "Don't ask again",
        expected: "Subsequent mutating sends skip confirm in session",
      },
    ],
    expectedResult: "Production guardrail on destructive methods",
    elementIds: ["EL-RB-007", "EL-RB-011", "EL-ENV-010"],
    automation: { status: "missing" },
    tags: ["environment", "production", "confirm"],
  },
  {
    id: "TC-ENV-005",
    feature: "ENV",
    featureDoc: "environments.md",
    title: "Duplicate environment copies vars without production flag",
    type: "crud",
    priority: "P2",
    preconditions: ["Production env with vars"],
    steps: [
      { order: 1, action: "click", input: "Duplicate", expected: "Copy named '<name> copy'" },
      {
        order: 2,
        action: "verify",
        elementId: "EL-ENV-005",
        expected: "Production unchecked on copy",
      },
      { order: 3, action: "verify", elementId: "EL-ENV-006", expected: "Variables copied" },
    ],
    expectedResult: "Duplicate is safe copy without prod flag",
    elementIds: ["EL-ENV-005", "EL-ENV-006"],
    automation: { status: "missing" },
    tags: ["environment", "duplicate"],
  },
];

export const importExportTestCases: TestCase[] = [
  {
    id: "TC-IE-001",
    feature: "IE",
    featureDoc: "import-export.md",
    title: "Import modal parses valid cURL into new tab",
    type: "functional",
    priority: "P0",
    preconditions: ["REST workspace"],
    steps: [
      { order: 1, action: "click", elementId: "EL-SID-002", expected: "Import modal" },
      {
        order: 2,
        action: "fill",
        elementId: "EL-IE-003",
        input: "curl https://api.example.com -H 'Accept: application/json'",
        expected: "cURL pasted",
      },
      {
        order: 3,
        action: "click",
        elementId: "EL-IE-004",
        expected: "New tab with parsed request",
      },
    ],
    expectedResult: "Modal import opens result in new tab",
    elementIds: ["EL-SID-002", "EL-IE-003", "EL-IE-004"],
    automation: { status: "covered", spec: "e2e/import-curl.spec.ts" },
    tags: ["import", "curl"],
  },
  {
    id: "TC-IE-002",
    feature: "IE",
    featureDoc: "import-export.md",
    title: "Invalid cURL in import modal shows error without crash",
    type: "edge",
    priority: "P1",
    preconditions: ["Import modal open"],
    steps: [
      {
        order: 1,
        action: "fill",
        elementId: "EL-IE-003",
        input: "not a curl command",
        expected: "Error message shown",
      },
      {
        order: 2,
        action: "verify",
        elementId: "EL-IE-007",
        expected: "User-readable validation error",
      },
    ],
    expectedResult: "Graceful import failure",
    elementIds: ["EL-IE-003", "EL-IE-007"],
    automation: {
      status: "partial",
      spec: "e2e/import-curl.spec.ts",
      testName: "invalid curl command shows an error",
    },
    tags: ["import", "error"],
  },
  {
    id: "TC-IE-003",
    feature: "IE",
    featureDoc: "import-export.md",
    title: "Copy as cURL produces valid round-trip command",
    type: "functional",
    priority: "P1",
    preconditions: ["Configured POST with headers and body"],
    steps: [
      {
        order: 1,
        action: "click",
        elementId: "EL-APP-006",
        expected: "cURL copied to clipboard; checkmark feedback",
      },
      { order: 2, action: "click", elementId: "EL-SID-002", expected: "Import modal" },
      {
        order: 3,
        action: "fill",
        elementId: "EL-IE-003",
        input: "pasted cURL",
        expected: "Equivalent request reproduced",
      },
    ],
    expectedResult: "Export/import round-trip fidelity",
    elementIds: ["EL-APP-006", "EL-IE-003"],
    automation: {
      status: "partial",
      spec: "e2e/method-and-actions.spec.ts",
      testName: "copy-as-cURL confirms with a check",
    },
    tags: ["export", "curl", "round-trip"],
  },
  {
    id: "TC-IE-004",
    feature: "IE",
    featureDoc: "import-export.md",
    title: "Postman collection import creates collection tree",
    type: "functional",
    priority: "P1",
    preconditions: ["Valid Postman collection JSON"],
    steps: [
      { order: 1, action: "click", elementId: "EL-IE-002", expected: "Postman mode" },
      {
        order: 2,
        action: "click",
        elementId: "EL-IE-006",
        input: "Upload file",
        expected: "File selected",
      },
      { order: 3, action: "click", elementId: "EL-IE-005", expected: "Submit import" },
      {
        order: 4,
        action: "verify",
        elementId: "EL-SID-010",
        expected: "Imported folders/requests in Collections tab",
      },
    ],
    expectedResult: "Postman import builds collection tree",
    elementIds: ["EL-IE-002", "EL-IE-006", "EL-SID-010"],
    automation: { status: "missing" },
    tags: ["import", "postman"],
  },
];

export const commandPaletteTestCases: TestCase[] = [
  {
    id: "TC-CP-001",
    feature: "CP",
    featureDoc: "command-palette.md",
    title: "⌘K opens command palette and searches collection requests",
    type: "functional",
    priority: "P0",
    preconditions: ["Saved collection request with unique body text"],
    steps: [
      { order: 1, action: "keyboard", input: "Meta+K", expected: "Palette overlay opens" },
      {
        order: 2,
        action: "type",
        elementId: "EL-CP-002",
        input: "unique body fragment",
        expected: "Matching collection result shown",
      },
      { order: 3, action: "click", elementId: "EL-CP-003", expected: "Request opens in tab" },
    ],
    expectedResult: "Palette finds saved requests by body",
    elementIds: ["EL-CP-001", "EL-CP-002", "EL-CP-003"],
    automation: { status: "covered", spec: "e2e/command-palette.spec.ts" },
    tags: ["palette", "search"],
  },
  {
    id: "TC-CP-002",
    feature: "CP",
    featureDoc: "command-palette.md",
    title: "Palette keyboard navigation with arrows and Enter",
    type: "keyboard",
    priority: "P1",
    preconditions: ["Multiple palette results"],
    steps: [
      { order: 1, action: "keyboard", input: "Meta+K", expected: "Palette open" },
      { order: 2, action: "keyboard", input: "ArrowDown", expected: "Selection moves" },
      { order: 3, action: "keyboard", input: "Enter", expected: "Selected item opens" },
    ],
    expectedResult: "Full keyboard-driven palette workflow",
    elementIds: ["EL-CP-001", "EL-CP-002"],
    automation: { status: "partial" },
    tags: ["palette", "keyboard"],
  },
  {
    id: "TC-CP-003",
    feature: "CP",
    featureDoc: "command-palette.md",
    title: "Escape closes palette without side effects",
    type: "ux",
    priority: "P1",
    preconditions: ["Palette open"],
    steps: [
      { order: 1, action: "keyboard", input: "Escape", expected: "Palette closes" },
      { order: 2, action: "verify", elementId: "EL-TAB-002", expected: "Active tab unchanged" },
    ],
    expectedResult: "Esc dismisses palette cleanly",
    elementIds: ["EL-CP-001", "EL-TAB-002"],
    automation: {
      status: "covered",
      spec: "e2e/command-palette.spec.ts",
      testName: "Escape closes the palette",
    },
    tags: ["palette", "escape"],
  },
];

export const settingsPersistenceTestCases: TestCase[] = [
  {
    id: "TC-SET-001",
    feature: "SET",
    featureDoc: "settings.md",
    title: "Dark and Light theme toggle persists across reload",
    type: "ui",
    priority: "P0",
    preconditions: ["Settings accessible"],
    steps: [
      { order: 1, action: "click", elementId: "EL-APP-007", expected: "Settings opens" },
      { order: 2, action: "click", elementId: "EL-SET-007", expected: "Light theme applied" },
      { order: 3, action: "reload", expected: "Light theme persists" },
      { order: 4, action: "click", elementId: "EL-SET-006", expected: "Dark theme restored" },
    ],
    expectedResult: "Theme preference stored",
    elementIds: ["EL-APP-007", "EL-SET-006", "EL-SET-007"],
    automation: { status: "covered", spec: "e2e/settings-theme.spec.ts" },
    tags: ["settings", "theme"],
  },
  {
    id: "TC-SET-002",
    feature: "SET",
    featureDoc: "settings.md",
    title: "Clear All wipes history/drafts/envs but preserves collections",
    type: "crud",
    priority: "P0",
    preconditions: ["Data in all categories"],
    steps: [
      { order: 1, action: "click", elementId: "EL-SET-004", expected: "Data tab" },
      { order: 2, action: "click", input: "Clear All", expected: "Confirm dialog" },
      { order: 3, action: "click", elementId: "EL-COL-008", expected: "Confirmed" },
      { order: 4, action: "verify", elementId: "EL-SET-011", expected: "History count zero" },
      { order: 5, action: "click", elementId: "EL-SID-005", expected: "Collections still present" },
    ],
    expectedResult: "Clear All semantics correct",
    elementIds: ["EL-SET-004", "EL-COL-008", "EL-SET-011", "EL-SID-005"],
    automation: {
      status: "covered",
      spec: "e2e/settings-theme.spec.ts",
      testName: "Clear All wipes history/drafts/environments but never collections",
    },
    tags: ["settings", "data", "clear"],
  },
  {
    id: "TC-SET-003",
    feature: "SET",
    featureDoc: "settings.md",
    title: "Keyboard shortcuts modal matches canonical doc list",
    type: "functional",
    priority: "P1",
    preconditions: ["REST workspace"],
    steps: [
      { order: 1, action: "keyboard", input: "Meta+/", expected: "Shortcuts modal opens" },
      {
        order: 2,
        action: "verify",
        elementId: "EL-SET-012",
        expected: "Lists ⌘K, ⌘Enter, ⌘S, etc.",
      },
    ],
    expectedResult: "Modal matches keyboard-shortcuts.md",
    elementIds: ["EL-SET-012"],
    automation: {
      status: "covered",
      spec: "e2e/shortcuts.spec.ts",
      testName: "⌘/ opens the shortcuts modal",
    },
    tags: ["settings", "keyboard"],
  },
  {
    id: "TC-PER-001",
    feature: "PER",
    featureDoc: "persistence.md",
    title: "Browser reload preserves collections, tabs, and environments",
    type: "persistence",
    priority: "P0",
    preconditions: ["Collection, env, and open tabs exist"],
    steps: [
      { order: 1, action: "reload", expected: "App reloads" },
      { order: 2, action: "verify", elementId: "EL-SID-005", expected: "Collections intact" },
      { order: 3, action: "verify", elementId: "EL-APP-002", expected: "Active env restored" },
      { order: 4, action: "verify", elementId: "EL-TAB-001", expected: "Open tabs restored" },
    ],
    expectedResult: "localStorage persistence round-trip",
    elementIds: ["EL-SID-005", "EL-APP-002", "EL-TAB-001"],
    automation: {
      status: "partial",
      spec: "e2e/tabs.spec.ts",
      testName: "restores open tabs after app reload",
    },
    tags: ["persistence", "browser"],
  },
];

export const contentTypeTestCases: TestCase[] = [
  {
    id: "TC-CT-001",
    feature: "CT",
    featureDoc: "content-types.md",
    title: "URL Encoded body serializes as application/x-www-form-urlencoded",
    type: "functional",
    priority: "P0",
    preconditions: ["POST with URL Encoded body rows"],
    steps: [
      { order: 1, action: "click", elementId: "EL-RB-030", expected: "URL Encoded selected" },
      {
        order: 2,
        action: "type",
        elementId: "EL-RB-032",
        input: "key=value pairs",
        expected: "Rows filled",
      },
      {
        order: 3,
        action: "click",
        elementId: "EL-RB-011",
        expected: "Wire Content-Type and body correct",
      },
    ],
    expectedResult: "Form encoding on wire matches editor",
    elementIds: ["EL-RB-030", "EL-RB-011"],
    automation: {
      status: "covered",
      spec: "e2e/body-editor.spec.ts",
      testName: "URL Encoded body serializes",
    },
    tags: ["body", "content-type"],
  },
  {
    id: "TC-CT-002",
    feature: "CT",
    featureDoc: "content-types.md",
    title: "GET and HEAD never send request body",
    type: "functional",
    priority: "P1",
    preconditions: ["GET tab with JSON body configured"],
    steps: [
      { order: 1, action: "click", elementId: "EL-RB-003", expected: "GET method" },
      { order: 2, action: "click", elementId: "EL-RB-017", expected: "Body configured" },
      {
        order: 3,
        action: "click",
        elementId: "EL-RB-011",
        expected: "No body in outbound request",
      },
    ],
    expectedResult: "Body stripped for GET/HEAD",
    elementIds: ["EL-RB-003", "EL-RB-017", "EL-RB-011"],
    automation: { status: "missing" },
    tags: ["body", "method"],
  },
  {
    id: "TC-CT-003",
    feature: "CT",
    featureDoc: "content-types.md",
    title: "HTML response renders in sandboxed preview iframe",
    type: "ui",
    priority: "P2",
    preconditions: ["Mock HTML response"],
    steps: [
      { order: 1, action: "click", elementId: "EL-RV-007", expected: "HTML preview mode" },
      {
        order: 2,
        action: "verify",
        elementId: "EL-RV-007",
        expected: "Iframe sandboxed; scripts restricted",
      },
    ],
    expectedResult: "HTML preview safe rendering",
    elementIds: ["EL-RV-007"],
    automation: { status: "missing" },
    tags: ["response", "html", "security"],
  },
];

export const keyboardTestCases: TestCase[] = [
  {
    id: "TC-KB-001",
    feature: "KB",
    featureDoc: "keyboard-shortcuts.md",
    title: "Full keyboard chord walkthrough (REST workspace)",
    type: "keyboard",
    priority: "P1",
    preconditions: ["REST workspace; mock endpoints"],
    steps: [
      { order: 1, action: "keyboard", input: "Meta+T", expected: "New tab" },
      { order: 2, action: "keyboard", input: "Meta+L", expected: "URL focused" },
      { order: 3, action: "keyboard", input: "Meta+Enter", expected: "Send" },
      { order: 4, action: "keyboard", input: "Meta+S", expected: "Save modal" },
      { order: 5, action: "keyboard", input: "Meta+Shift+E", expected: "Env manager" },
      { order: 6, action: "keyboard", input: "Meta+Backslash", expected: "Sidebar toggle" },
      { order: 7, action: "keyboard", input: "Meta+Comma", expected: "Settings" },
    ],
    expectedResult: "All documented chords fire expected actions",
    elementIds: ["EL-RB-001", "EL-APP-007", "EL-ENV-003"],
    automation: { status: "partial", spec: "e2e/shortcuts.spec.ts" },
    tags: ["keyboard", "regression"],
  },
];

export const sharedUiTestCases: TestCase[] = [
  {
    id: "TC-SUI-001",
    feature: "SUI",
    featureDoc: "shared-ui.md",
    title: "Modal Space key in input does not close backdrop",
    type: "ux",
    priority: "P1",
    preconditions: ["Collection name modal open"],
    steps: [
      { order: 1, action: "click", elementId: "EL-COL-001", expected: "Modal open" },
      { order: 2, action: "click", elementId: "EL-COL-002", expected: "Input focused" },
      {
        order: 3,
        action: "keyboard",
        input: "Space",
        expected: "Space typed into field; modal stays open",
      },
    ],
    expectedResult: "Space does not propagate to backdrop close",
    elementIds: ["EL-COL-002"],
    automation: { status: "missing" },
    tags: ["modal", "keyboard"],
  },
  {
    id: "TC-SUI-002",
    feature: "SUI",
    featureDoc: "shared-ui.md",
    title: "KeyValueEditor row delete removes row and updates counts",
    type: "functional",
    priority: "P1",
    preconditions: ["Headers tab with multiple rows"],
    steps: [
      { order: 1, action: "click", elementId: "EL-RB-016", expected: "Headers tab" },
      { order: 2, action: "click", input: "Remove row", expected: "Row removed" },
      {
        order: 3,
        action: "verify",
        elementId: "EL-RB-016",
        expected: "Header badge count decremented",
      },
    ],
    expectedResult: "Row CRUD in KV editor works",
    elementIds: ["EL-RB-016", "EL-RB-021"],
    automation: { status: "missing" },
    tags: ["kv-editor"],
  },
];

export const mcpTestCases: TestCase[] = [
  {
    id: "TC-MCP-001",
    feature: "MCP",
    featureDoc: "mcp.md",
    title: "MCP coming-soon page shown instead of bench (shipped UI)",
    type: "ui",
    priority: "P1",
    preconditions: ["REST workspace"],
    steps: [
      { order: 1, action: "click", elementId: "EL-APP-004", expected: "Coming soon page" },
      {
        order: 2,
        action: "verify",
        elementId: "EL-MCP-001",
        expected: "MCP panel NOT visible (bench disabled)",
      },
    ],
    expectedResult: "Production UI gates MCP bench",
    elementIds: ["EL-APP-004", "EL-WS-001", "EL-MCP-001"],
    automation: { status: "covered", spec: "e2e/mcp.spec.ts" },
    tags: ["mcp", "coming-soon"],
  },
  {
    id: "TC-MCP-002",
    feature: "MCP",
    featureDoc: "mcp.md",
    title: "[Retained] MCP connect and list tools (bench re-enable)",
    type: "functional",
    priority: "P2",
    preconditions: ["MCP bench enabled; test server running"],
    steps: [
      {
        order: 1,
        action: "type",
        elementId: "EL-MCP-002",
        input: "http://localhost:3000/mcp",
        expected: "URL entered",
      },
      { order: 2, action: "click", elementId: "EL-MCP-003", expected: "Connected; tools listed" },
      { order: 3, action: "click", elementId: "EL-MCP-004", expected: "Tool result in EL-MCP-005" },
    ],
    expectedResult: "Full MCP bench workflow when re-enabled",
    elementIds: ["EL-MCP-002", "EL-MCP-003", "EL-MCP-004", "EL-MCP-005"],
    automation: { status: "manual-only" },
    tags: ["mcp", "bench", "future"],
  },
];

export const graphqlTestCases: TestCase[] = [
  {
    id: "TC-GQL-001",
    feature: "GQL",
    featureDoc: "graphql.md",
    title: "GraphQL coming-soon page via header and ⌘⇧G",
    type: "ui",
    priority: "P2",
    preconditions: ["REST workspace"],
    steps: [
      {
        order: 1,
        action: "click",
        elementId: "EL-APP-005",
        expected: "GraphQL coming soon visible",
      },
      { order: 2, action: "keyboard", input: "Meta+Shift+G", expected: "Same page via shortcut" },
    ],
    expectedResult: "GraphQL workspace placeholder reachable",
    elementIds: ["EL-APP-005", "EL-WS-002"],
    automation: { status: "covered", spec: "e2e/find-and-kind-tabs.spec.ts" },
    tags: ["graphql", "coming-soon"],
  },
];
