import type { TestCase } from "../types.js";

/** Extra cases that close feature-doc checklist gaps after the first catalog pass. */

export const extraAppShellCases: TestCase[] = [
  {
    id: "TC-APP-006",
    feature: "APP",
    featureDoc: "app-shell.md",
    title: "Sidebar resize to min/max width does not overflow the page",
    type: "ux",
    priority: "P1",
    preconditions: ["REST workspace; sidebar expanded"],
    steps: [
      {
        order: 1,
        action: "drag",
        elementId: "EL-SID-008",
        input: "to ~180px",
        expected: "Sidebar shrinks; labels still readable or truncated",
      },
      {
        order: 2,
        action: "drag",
        elementId: "EL-SID-008",
        input: "to ~400px",
        expected: "Sidebar grows; URL bar still visible",
      },
      {
        order: 3,
        action: "verify",
        elementId: "EL-RB-001",
        expected: "No document-level horizontal scrollbar",
      },
    ],
    expectedResult: "Sidebar width extremes keep the workspace inside the window",
    elementIds: ["EL-SID-008", "EL-RB-001"],
    automation: { status: "missing" },
    tags: ["layout", "resize", "sidebar"],
  },
  {
    id: "TC-APP-007",
    feature: "APP",
    featureDoc: "app-shell.md",
    title: "Deactivating production env removes red header indicator",
    type: "ui",
    priority: "P1",
    preconditions: ["Production environment currently active"],
    steps: [
      {
        order: 1,
        action: "verify",
        elementId: "EL-APP-008",
        expected: "Red production indicator visible",
      },
      { order: 2, action: "click", elementId: "EL-APP-002", expected: "Env dropdown opens" },
      { order: 3, action: "click", elementId: "EL-ENV-001", expected: "No environment selected" },
      {
        order: 4,
        action: "verify",
        elementId: "EL-APP-008",
        expected: "Indicator gone; Send button not production-red",
      },
    ],
    expectedResult: "Production visual cues are tied to the active env, not leftover state",
    elementIds: ["EL-APP-008", "EL-APP-002", "EL-ENV-001"],
    automation: { status: "partial", spec: "e2e/environments.spec.ts" },
    tags: ["environment", "production", "visual"],
  },
  {
    id: "TC-APP-008",
    feature: "APP",
    featureDoc: "app-shell.md",
    title: "Header MCP and GraphQL buttons show styled tooltips on hover and focus",
    type: "accessibility",
    priority: "P2",
    preconditions: ["REST workspace"],
    steps: [
      {
        order: 1,
        action: "hover",
        elementId: "EL-APP-004",
        expected: "Styled tooltip, not native title, for MCP coming soon",
      },
      {
        order: 2,
        action: "hover",
        elementId: "EL-APP-005",
        expected: "Styled tooltip for GraphQL coming soon",
      },
      {
        order: 3,
        action: "keyboard",
        input: "Tab to MCP button",
        expected: "Tooltip also appears on keyboard focus",
      },
    ],
    expectedResult: "Workspace buttons are labeled for pointer and keyboard users",
    elementIds: ["EL-APP-004", "EL-APP-005"],
    automation: {
      status: "covered",
      spec: "e2e/find-and-kind-tabs.spec.ts",
      testName: "header icon-button tooltips",
    },
    tags: ["a11y", "tooltip", "header"],
  },
  {
    id: "TC-APP-009",
    feature: "APP",
    featureDoc: "app-shell.md",
    title: "Copy as cURL from header shows checkmark feedback",
    type: "ux",
    priority: "P1",
    preconditions: ["Tab with URL, method, and optional headers"],
    steps: [
      {
        order: 1,
        action: "click",
        elementId: "EL-APP-006",
        expected: "Button briefly shows check / Copied",
      },
      {
        order: 2,
        action: "verify",
        elementId: "EL-APP-006",
        expected: "Clipboard contains a valid curl command",
      },
    ],
    expectedResult: "Export action confirms success without a blocking toast",
    elementIds: ["EL-APP-006"],
    automation: {
      status: "covered",
      spec: "e2e/method-and-actions.spec.ts",
      testName: "copy-as-cURL confirms with a check",
    },
    tags: ["export", "curl", "header"],
  },
];

export const extraWorkspaceCases: TestCase[] = [
  {
    id: "TC-WS-004",
    feature: "WS",
    featureDoc: "workspaces.md",
    title: "REST restores previous tabs after visiting MCP coming-soon",
    type: "functional",
    priority: "P0",
    preconditions: ["Two REST tabs open with URLs"],
    steps: [
      {
        order: 1,
        action: "click",
        elementId: "EL-APP-004",
        expected: "MCP coming-soon; sidebar and tabs hidden",
      },
      { order: 2, action: "click", elementId: "EL-APP-003", expected: "REST workspace restored" },
      {
        order: 3,
        action: "verify",
        elementId: "EL-TAB-001",
        expected: "Same tabs still present with prior URLs",
      },
    ],
    expectedResult: "Coming-soon swap is in-place and non-destructive",
    elementIds: ["EL-APP-004", "EL-APP-003", "EL-TAB-001", "EL-WS-001"],
    automation: { status: "covered", spec: "e2e/mcp.spec.ts" },
    tags: ["workspace", "tabs", "mcp"],
  },
  {
    id: "TC-WS-005",
    feature: "WS",
    featureDoc: "workspaces.md",
    title: "Cycle REST → MCP → GraphQL → REST with header shortcuts",
    type: "keyboard",
    priority: "P1",
    preconditions: ["REST workspace"],
    steps: [
      { order: 1, action: "keyboard", input: "Meta+Shift+M", expected: "MCP coming-soon" },
      { order: 2, action: "keyboard", input: "Meta+Shift+G", expected: "GraphQL coming-soon" },
      { order: 3, action: "keyboard", input: "Meta+Shift+R", expected: "REST layout restored" },
    ],
    expectedResult: "Workbench chords match keyboard-shortcuts.md",
    elementIds: ["EL-WS-001", "EL-WS-002", "EL-APP-003"],
    automation: { status: "partial", spec: "e2e/find-and-kind-tabs.spec.ts" },
    tags: ["workspace", "keyboard"],
  },
];

export const extraSidebarCases: TestCase[] = [
  {
    id: "TC-SID-005",
    feature: "SID",
    featureDoc: "sidebar.md",
    title: "Empty Collections tab shows Create Collection CTA",
    type: "ui",
    priority: "P1",
    preconditions: ["No collections"],
    steps: [
      { order: 1, action: "click", elementId: "EL-SID-005", expected: "Collections tab" },
      {
        order: 2,
        action: "verify",
        elementId: "EL-SID-013",
        expected: "Empty state + Create Collection CTA",
      },
    ],
    expectedResult: "Empty collections is guided, not a blank panel",
    elementIds: ["EL-SID-005", "EL-SID-013"],
    automation: { status: "partial" },
    tags: ["sidebar", "empty-state", "collections"],
  },
  {
    id: "TC-SID-006",
    feature: "SID",
    featureDoc: "sidebar.md",
    title: "Sidebar icons remain contrast-safe in Light and Dark",
    type: "ui",
    priority: "P2",
    preconditions: ["REST workspace"],
    steps: [
      { order: 1, action: "click", elementId: "EL-APP-007", expected: "Settings open" },
      { order: 2, action: "click", elementId: "EL-SET-007", expected: "Light theme" },
      {
        order: 3,
        action: "verify",
        elementId: "EL-SID-001",
        expected: "New Request and tab icons readable on light bg",
      },
      { order: 4, action: "click", elementId: "EL-SET-006", expected: "Dark theme restored" },
    ],
    expectedResult: "Sidebar chrome uses tokens, not hardcoded dark-only colors",
    elementIds: ["EL-SID-001", "EL-SET-006", "EL-SET-007"],
    automation: { status: "missing" },
    tags: ["theme", "contrast", "sidebar"],
  },
];

export const extraTabCases: TestCase[] = [
  {
    id: "TC-TAB-008",
    feature: "TAB",
    featureDoc: "tabs.md",
    title: "Right-click Duplicate creates a copy of the active request",
    type: "crud",
    priority: "P1",
    preconditions: ["Tab with URL, headers, and body"],
    steps: [
      {
        order: 1,
        action: "click",
        elementId: "EL-TAB-002",
        input: "right-click",
        expected: "Context menu",
      },
      {
        order: 2,
        action: "click",
        elementId: "EL-TAB-009",
        expected: "New tab appears with same URL/method",
      },
      {
        order: 3,
        action: "verify",
        elementId: "EL-RB-001",
        expected: "Duplicated tab is independent after edits",
      },
    ],
    expectedResult: "Duplicate clones request state into a new tab",
    elementIds: ["EL-TAB-002", "EL-TAB-009", "EL-RB-001"],
    automation: { status: "missing" },
    tags: ["tabs", "duplicate", "context-menu"],
  },
  {
    id: "TC-TAB-009",
    feature: "TAB",
    featureDoc: "tabs.md",
    title: "Clearing a locked rename restores auto path name",
    type: "ux",
    priority: "P1",
    preconditions: ["Tab renamed and URL path set"],
    steps: [
      { order: 1, action: "dblclick", elementId: "EL-TAB-002", expected: "Rename input" },
      { order: 2, action: "clear", elementId: "EL-TAB-007", expected: "Name field empty" },
      {
        order: 3,
        action: "keyboard",
        input: "Enter",
        expected: "Tab label returns to URL path auto-name",
      },
    ],
    expectedResult: "Unlocking rename re-enables auto naming",
    elementIds: ["EL-TAB-002", "EL-TAB-007"],
    automation: { status: "partial", spec: "e2e/tabs.spec.ts" },
    tags: ["tabs", "rename"],
  },
  {
    id: "TC-TAB-010",
    feature: "TAB",
    featureDoc: "tabs.md",
    title: "Close All leaves a single empty Untitled tab",
    type: "crud",
    priority: "P1",
    preconditions: ["Three tabs open"],
    steps: [
      {
        order: 1,
        action: "click",
        elementId: "EL-TAB-002",
        input: "right-click",
        expected: "Menu",
      },
      {
        order: 2,
        action: "click",
        elementId: "EL-TAB-011",
        expected: "One empty Untitled Request remains",
      },
      { order: 3, action: "verify", elementId: "EL-RB-026", expected: "Empty-request CTA visible" },
    ],
    expectedResult: "Workspace never has zero tabs",
    elementIds: ["EL-TAB-011", "EL-RB-026"],
    automation: { status: "missing" },
    tags: ["tabs", "close-all"],
  },
];

export const extraRequestBuilderCases: TestCase[] = [
  {
    id: "TC-RB-013",
    feature: "RB",
    featureDoc: "request-builder.md",
    title: "Re-enabling a disabled param restores it in the URL query",
    type: "functional",
    priority: "P1",
    preconditions: ["URL with ?q=test; param row disabled"],
    steps: [
      { order: 1, action: "click", elementId: "EL-RB-014", expected: "Params tab" },
      { order: 2, action: "check", elementId: "EL-RB-041", expected: "Row enabled again" },
      { order: 3, action: "verify", elementId: "EL-RB-001", expected: "q=test back in URL" },
    ],
    expectedResult: "Enable/disable is reversible and stays in sync with the URL",
    elementIds: ["EL-RB-014", "EL-RB-041", "EL-RB-001"],
    automation: { status: "missing" },
    tags: ["params", "disable"],
  },
  {
    id: "TC-RB-014",
    feature: "RB",
    featureDoc: "request-builder.md",
    title: "Basic auth sends Authorization: Basic on the wire",
    type: "functional",
    priority: "P1",
    preconditions: ["Mocked endpoint"],
    steps: [
      { order: 1, action: "click", elementId: "EL-RB-015", expected: "Auth tab" },
      {
        order: 2,
        action: "select",
        elementId: "EL-RB-043",
        input: "Basic Auth",
        expected: "Username/password fields",
      },
      {
        order: 3,
        action: "type",
        elementId: "EL-RB-037",
        input: "alice",
        expected: "Username set",
      },
      {
        order: 4,
        action: "type",
        elementId: "EL-RB-038",
        input: "secret",
        expected: "Password set",
      },
      {
        order: 5,
        action: "click",
        elementId: "EL-RB-011",
        expected: "Authorization: Basic <base64> on wire",
      },
    ],
    expectedResult: "Basic credentials are encoded at send time, not stored as a raw header row",
    elementIds: ["EL-RB-015", "EL-RB-043", "EL-RB-037", "EL-RB-038", "EL-RB-011"],
    automation: { status: "missing" },
    tags: ["auth", "basic", "send"],
  },
  {
    id: "TC-RB-015",
    feature: "RB",
    featureDoc: "request-builder.md",
    title: "API Key auth can inject as a header",
    type: "functional",
    priority: "P1",
    preconditions: ["Mocked endpoint"],
    steps: [
      { order: 1, action: "click", elementId: "EL-RB-015", expected: "Auth tab" },
      {
        order: 2,
        action: "select",
        elementId: "EL-RB-043",
        input: "API Key",
        expected: "Key/value/Add to fields",
      },
      {
        order: 3,
        action: "type",
        elementId: "EL-RB-039",
        input: "X-API-Key",
        expected: "Key name",
      },
      { order: 4, action: "type", elementId: "EL-RB-040", input: "abc123", expected: "Value" },
      { order: 5, action: "select", input: "Header", expected: "Add to header" },
      { order: 6, action: "click", elementId: "EL-RB-011", expected: "X-API-Key: abc123 on wire" },
    ],
    expectedResult: "API key header injected at send, not duplicated in Headers editor",
    elementIds: ["EL-RB-015", "EL-RB-039", "EL-RB-040", "EL-RB-011"],
    automation: { status: "missing" },
    tags: ["auth", "api-key"],
  },
  {
    id: "TC-RB-016",
    feature: "RB",
    featureDoc: "request-builder.md",
    title: "API Key auth can inject as a query param",
    type: "functional",
    priority: "P1",
    preconditions: ["Mocked endpoint; URL without that query key"],
    steps: [
      {
        order: 1,
        action: "select",
        elementId: "EL-RB-043",
        input: "API Key",
        expected: "Fields visible",
      },
      { order: 2, action: "type", elementId: "EL-RB-039", input: "api_key", expected: "Key" },
      { order: 3, action: "type", elementId: "EL-RB-040", input: "xyz", expected: "Value" },
      { order: 4, action: "select", input: "Query Params", expected: "Add to query" },
      {
        order: 5,
        action: "click",
        elementId: "EL-RB-011",
        expected: "Wire URL includes api_key=xyz",
      },
    ],
    expectedResult:
      "API key query is applied at send without rewriting the Params editor permanently",
    elementIds: ["EL-RB-039", "EL-RB-040", "EL-RB-011"],
    automation: { status: "missing" },
    tags: ["auth", "api-key", "query"],
  },
  {
    id: "TC-RB-017",
    feature: "RB",
    featureDoc: "request-builder.md",
    title: "Body word wrap toggle shares preference with Settings and response",
    type: "ux",
    priority: "P1",
    preconditions: ["JSON body editor open"],
    steps: [
      { order: 1, action: "click", elementId: "EL-RB-024", expected: "Wrap on in body editor" },
      { order: 2, action: "click", elementId: "EL-APP-007", expected: "Settings" },
      {
        order: 3,
        action: "verify",
        elementId: "EL-SET-008",
        expected: "Word wrap switch matches body toggle",
      },
      {
        order: 4,
        action: "verify",
        elementId: "EL-RV-008",
        expected: "Response wrap matches after a response exists",
      },
    ],
    expectedResult: "pg_word_wrap is a single shared preference",
    elementIds: ["EL-RB-024", "EL-SET-008", "EL-RV-008"],
    automation: { status: "missing" },
    tags: ["word-wrap", "settings"],
  },
  {
    id: "TC-RB-018",
    feature: "RB",
    featureDoc: "request-builder.md",
    title: "GET with JSON body configured does not send a body",
    type: "functional",
    priority: "P0",
    preconditions: ["POST tab with JSON body; mocked endpoint"],
    steps: [
      { order: 1, action: "click", elementId: "EL-RB-003", expected: "Method GET" },
      { order: 2, action: "click", elementId: "EL-RB-011", expected: "Request sent" },
      {
        order: 3,
        action: "verify",
        expected: "Outbound request has no body / no JSON Content-Type from body",
      },
    ],
    expectedResult: "GET never transmits the editor body",
    elementIds: ["EL-RB-003", "EL-RB-011", "EL-RB-017"],
    automation: { status: "missing" },
    tags: ["method", "body", "get"],
  },
  {
    id: "TC-RB-019",
    feature: "RB",
    featureDoc: "request-builder.md",
    title: "HEAD never sends a body",
    type: "functional",
    priority: "P1",
    preconditions: ["JSON body configured"],
    steps: [
      { order: 1, action: "click", elementId: "EL-RB-008", expected: "HEAD selected" },
      { order: 2, action: "click", elementId: "EL-RB-011", expected: "No body on wire" },
    ],
    expectedResult: "HEAD body is stripped at send",
    elementIds: ["EL-RB-008", "EL-RB-011"],
    automation: { status: "missing" },
    tags: ["method", "body", "head"],
  },
  {
    id: "TC-RB-020",
    feature: "RB",
    featureDoc: "request-builder.md",
    title: "Try an example fills a sample URL and leaves empty state",
    type: "ux",
    priority: "P1",
    preconditions: ["Empty URL tab"],
    steps: [
      { order: 1, action: "verify", elementId: "EL-RB-026", expected: "CTA visible" },
      {
        order: 2,
        action: "click",
        elementId: "EL-RB-026",
        expected: "URL populated; editor tabs appear",
      },
      { order: 3, action: "verify", elementId: "EL-RB-011", expected: "Send enabled" },
    ],
    expectedResult: "Example CTA is the only empty-state action",
    elementIds: ["EL-RB-026", "EL-RB-001", "EL-RB-011"],
    automation: { status: "partial", spec: "e2e/smoke.spec.ts" },
    tags: ["empty-state"],
  },
  {
    id: "TC-RB-021",
    feature: "RB",
    featureDoc: "request-builder.md",
    title: "⌘F in body editor opens in-panel find, not header search",
    type: "keyboard",
    priority: "P1",
    preconditions: ["JSON body with repeated tokens"],
    steps: [
      { order: 1, action: "click", elementId: "EL-RB-017", expected: "Body focused" },
      {
        order: 2,
        action: "keyboard",
        input: "Meta+F",
        expected: "Body find bar (EL-RB-025) opens",
      },
      {
        order: 3,
        action: "type",
        elementId: "EL-RB-042",
        input: "key",
        expected: "Match count shown; header search not focused",
      },
    ],
    expectedResult: "Contextual find stays in the body editor",
    elementIds: ["EL-RB-017", "EL-RB-025", "EL-RB-042", "EL-APP-001"],
    automation: {
      status: "covered",
      spec: "e2e/find-and-kind-tabs.spec.ts",
      testName: "⌘F in the body editor opens the body find bar",
    },
    tags: ["find", "keyboard", "body"],
  },
  {
    id: "TC-RB-022",
    feature: "RB",
    featureDoc: "request-builder.md",
    title: "Long header value supports End key and horizontal scroll",
    type: "edge",
    priority: "P1",
    preconditions: ["Headers tab"],
    steps: [
      { order: 1, action: "click", elementId: "EL-RB-016", expected: "Headers" },
      {
        order: 2,
        action: "fill",
        elementId: "EL-RB-021",
        input: "600+ char token",
        expected: "Value accepted",
      },
      { order: 3, action: "keyboard", input: "End", expected: "Caret at end; overlay aligned" },
    ],
    expectedResult: "Long KV values scroll inside the cell, not the page",
    elementIds: ["EL-RB-016", "EL-RB-021"],
    automation: { status: "covered", spec: "e2e/long-values.spec.ts" },
    tags: ["edge", "headers"],
  },
  {
    id: "TC-RB-023",
    feature: "RB",
    featureDoc: "request-builder.md",
    title: "Format button pretty-prints JSON body",
    type: "ux",
    priority: "P2",
    preconditions: ["JSON body type; minified JSON"],
    steps: [
      { order: 1, action: "click", elementId: "EL-RB-028", expected: "JSON selected" },
      {
        order: 2,
        action: "fill",
        elementId: "EL-RB-032",
        input: '{"a":1}',
        expected: "Minified JSON",
      },
      { order: 3, action: "click", elementId: "EL-RB-035", expected: "Indented pretty JSON" },
    ],
    expectedResult: "Format is local to the editor and does not send",
    elementIds: ["EL-RB-028", "EL-RB-032", "EL-RB-035"],
    automation: { status: "missing" },
    tags: ["body", "json", "format"],
  },
];

export const extraResponseExecutionCases: TestCase[] = [
  {
    id: "TC-RV-006",
    feature: "RV",
    featureDoc: "response-viewer.md",
    title: "Response word wrap preference persists across reload",
    type: "persistence",
    priority: "P1",
    preconditions: ["JSON response visible"],
    steps: [
      { order: 1, action: "click", elementId: "EL-RV-008", expected: "Wrap on" },
      { order: 2, action: "reload", expected: "App reloads" },
      {
        order: 3,
        action: "verify",
        elementId: "EL-RV-008",
        expected: "Wrap still on after a new send",
      },
    ],
    expectedResult: "Word wrap stored in pg_word_wrap",
    elementIds: ["EL-RV-008"],
    automation: { status: "missing" },
    tags: ["word-wrap", "persistence"],
  },
  {
    id: "TC-RV-007",
    feature: "RV",
    featureDoc: "response-viewer.md",
    title: "Huge JSON scrolls only inside the response pane",
    type: "edge",
    priority: "P1",
    preconditions: ["Mocked large JSON body"],
    steps: [
      { order: 1, action: "click", elementId: "EL-RB-011", expected: "Large 200 JSON" },
      {
        order: 2,
        action: "scroll",
        elementId: "EL-RV-004",
        expected: "Vertical scroll in pane; page does not grow",
      },
    ],
    expectedResult: "Oversized bodies are contained",
    elementIds: ["EL-RV-004"],
    automation: { status: "missing" },
    tags: ["response", "scroll", "edge"],
  },
  {
    id: "TC-RV-008",
    feature: "RV",
    featureDoc: "response-viewer.md",
    title: "Response Headers tab lists headers; long values scroll",
    type: "ui",
    priority: "P1",
    preconditions: ["Response with 4+ headers including a long value"],
    steps: [
      { order: 1, action: "click", elementId: "EL-RV-012", expected: "Headers table visible" },
      { order: 2, action: "scroll", expected: "Long header value readable via horizontal scroll" },
    ],
    expectedResult: "Headers tab is complete and overflow-safe",
    elementIds: ["EL-RV-012"],
    automation: { status: "missing" },
    tags: ["response", "headers"],
  },
  {
    id: "TC-RV-009",
    feature: "RV",
    featureDoc: "response-viewer.md",
    title: "SSE stream lists events and Stop ends the stream",
    type: "functional",
    priority: "P1",
    preconditions: ["Desktop or mocked text/event-stream"],
    steps: [
      { order: 1, action: "click", elementId: "EL-RB-011", expected: "SSE panel appears" },
      { order: 2, action: "verify", elementId: "EL-RV-013", expected: "Events accumulate" },
      {
        order: 3,
        action: "click",
        elementId: "EL-RV-014",
        expected: "Stream stops; no further events",
      },
    ],
    expectedResult: "SSE UI supports inspect + stop",
    elementIds: ["EL-RV-013", "EL-RV-014", "EL-RV-021"],
    automation: { status: "missing" },
    tags: ["sse", "desktop"],
  },
  {
    id: "TC-RV-010",
    feature: "RV",
    featureDoc: "response-viewer.md",
    title: "Download response saves the body locally",
    type: "functional",
    priority: "P2",
    preconditions: ["JSON response visible"],
    steps: [
      {
        order: 1,
        action: "click",
        elementId: "EL-RV-015",
        expected: "Browser download starts with response bytes",
      },
    ],
    expectedResult: "Download uses the current body, not a re-fetch",
    elementIds: ["EL-RV-015"],
    automation: { status: "missing" },
    tags: ["response", "download"],
  },
  {
    id: "TC-RV-011",
    feature: "RV",
    featureDoc: "response-viewer.md",
    title: "Find next re-centers on subsequent matches in pretty JSON",
    type: "keyboard",
    priority: "P1",
    preconditions: ["Pretty JSON with several matches"],
    steps: [
      { order: 1, action: "keyboard", input: "Meta+F", expected: "Find bar" },
      { order: 2, action: "type", elementId: "EL-RV-019", input: "id", expected: "Count > 1" },
      {
        order: 3,
        action: "click",
        elementId: "EL-RV-020",
        expected: "Scroll jumps to next match; formatting stays pretty",
      },
    ],
    expectedResult: "Find does not flatten pretty JSON",
    elementIds: ["EL-RV-019", "EL-RV-020", "EL-RV-005"],
    automation: { status: "covered", spec: "e2e/find-and-kind-tabs.spec.ts" },
    tags: ["find", "json"],
  },
  {
    id: "TC-EX-004",
    feature: "EX",
    featureDoc: "execution.md",
    title: "Params are authoritative when URL query also exists",
    type: "functional",
    priority: "P0",
    preconditions: ["URL ?a=2 and Params a=1"],
    steps: [
      {
        order: 1,
        action: "type",
        elementId: "EL-RB-001",
        input: "https://mock.test/x?a=2",
        expected: "URL query",
      },
      { order: 2, action: "fill", elementId: "EL-RB-019", input: "1", expected: "Param a=1" },
      {
        order: 3,
        action: "click",
        elementId: "EL-RB-011",
        expected: "Wire query has a=1 only (no duplicate a=2)",
      },
    ],
    expectedResult: "Send uses params when present to avoid duplicated query keys",
    elementIds: ["EL-RB-001", "EL-RB-019", "EL-RB-011"],
    automation: { status: "missing" },
    tags: ["send", "params", "url-sync"],
  },
  {
    id: "TC-EX-005",
    feature: "EX",
    featureDoc: "execution.md",
    title: "Follow Redirects setting is honored on desktop 302",
    type: "functional",
    priority: "P2",
    preconditions: ["Desktop app; 302 endpoint"],
    steps: [
      { order: 1, action: "click", elementId: "EL-APP-007", expected: "Settings" },
      { order: 2, action: "click", elementId: "EL-SET-020", expected: "Requests tab" },
      { order: 3, action: "click", elementId: "EL-SET-014", expected: "Follow Redirects off" },
      { order: 4, action: "click", elementId: "EL-RB-011", expected: "Status 302, not followed" },
    ],
    expectedResult: "Redirect policy is user-controlled on desktop",
    elementIds: ["EL-SET-014", "EL-RB-011", "EL-RV-003"],
    automation: { status: "manual-only" },
    tags: ["desktop", "redirects"],
  },
  {
    id: "TC-EX-006",
    feature: "EX",
    featureDoc: "execution.md",
    title: "Status line shows timing and size after send",
    type: "ui",
    priority: "P1",
    preconditions: ["Mocked 200 JSON"],
    steps: [
      { order: 1, action: "click", elementId: "EL-RB-011", expected: "200" },
      {
        order: 2,
        action: "verify",
        elementId: "EL-RV-003",
        expected: "ms timing and byte size visible",
      },
    ],
    expectedResult: "Status line includes status, duration, and payload size",
    elementIds: ["EL-RV-003"],
    automation: { status: "partial", spec: "e2e/send.spec.ts" },
    tags: ["send", "status"],
  },
];

export const extraCollectionCases: TestCase[] = [
  {
    id: "TC-COL-007",
    feature: "COL",
    featureDoc: "collections.md",
    title: "Nested folders blocked past MAX_NESTING_DEPTH (10)",
    type: "edge",
    priority: "P2",
    preconditions: ["Collection with 10 nested folders"],
    steps: [
      {
        order: 1,
        action: "click",
        elementId: "EL-COL-010",
        expected: "Add folder on deepest node rejected or disabled",
      },
      { order: 2, action: "verify", expected: "No 11th folder created" },
    ],
    expectedResult: "Nesting hard-stop at 10",
    elementIds: ["EL-COL-010", "EL-SID-010"],
    automation: { status: "missing" },
    tags: ["collections", "nesting", "edge"],
  },
  {
    id: "TC-COL-008",
    feature: "COL",
    featureDoc: "collections.md",
    title: "Drag request onto collection root leaves its folder",
    type: "ux",
    priority: "P1",
    preconditions: ["Request nested in a folder"],
    steps: [
      {
        order: 1,
        action: "drag",
        elementId: "EL-SID-010",
        input: "onto collection root",
        expected: "Drop highlight",
      },
      { order: 2, action: "drop", expected: "Request is a direct child of the collection" },
    ],
    expectedResult: "Root drop un-nests the request",
    elementIds: ["EL-SID-010", "EL-COL-007"],
    automation: { status: "partial", spec: "e2e/collections.spec.ts" },
    tags: ["collections", "dnd"],
  },
  {
    id: "TC-COL-009",
    feature: "COL",
    featureDoc: "collections.md",
    title: "Delete collection confirms and removes the whole tree",
    type: "crud",
    priority: "P0",
    preconditions: ["Named collection with children"],
    steps: [
      { order: 1, action: "hover", elementId: "EL-SID-010", expected: "Delete visible" },
      { order: 2, action: "click", elementId: "EL-SID-012", expected: "Confirm modal" },
      {
        order: 3,
        action: "click",
        elementId: "EL-COL-008",
        expected: "Collection gone from sidebar",
      },
    ],
    expectedResult: "Collection delete is confirmed and complete",
    elementIds: ["EL-SID-012", "EL-COL-008"],
    automation: { status: "partial", spec: "e2e/collections.spec.ts" },
    tags: ["collections", "delete"],
  },
  {
    id: "TC-COL-010",
    feature: "COL",
    featureDoc: "collections.md",
    title: "⌘S updates a collection-linked request in place without modal",
    type: "keyboard",
    priority: "P0",
    preconditions: ["Tab opened from a saved collection request"],
    steps: [
      {
        order: 1,
        action: "type",
        elementId: "EL-RB-001",
        input: "changed path",
        expected: "URL edited",
      },
      {
        order: 2,
        action: "keyboard",
        input: "Meta+S",
        expected: "No save modal; tree node updated",
      },
      { order: 3, action: "click", elementId: "EL-SID-010", expected: "Reopen shows new URL" },
    ],
    expectedResult: "In-place save for linked tabs; ⌘⇧S still opens Save As",
    elementIds: ["EL-RB-001", "EL-SID-010", "EL-COL-003"],
    automation: {
      status: "partial",
      spec: "e2e/shortcuts.spec.ts",
      testName: "⌘S opens Save to Collection",
    },
    tags: ["collections", "save", "keyboard"],
  },
  {
    id: "TC-COL-011",
    feature: "COL",
    featureDoc: "collections.md",
    title: "Add folder and add request from collection row actions",
    type: "crud",
    priority: "P1",
    preconditions: ["Existing collection"],
    steps: [
      {
        order: 1,
        action: "hover",
        elementId: "EL-SID-010",
        expected: "Add request / Add folder visible",
      },
      { order: 2, action: "click", elementId: "EL-COL-010", expected: "Name modal for folder" },
      {
        order: 3,
        action: "type",
        elementId: "EL-COL-002",
        input: "Auth",
        expected: "Folder created collapsed",
      },
      {
        order: 4,
        action: "click",
        elementId: "EL-COL-009",
        expected: "New request node under collection or folder",
      },
    ],
    expectedResult: "Row actions create children without leaving the sidebar",
    elementIds: ["EL-COL-009", "EL-COL-010", "EL-COL-002"],
    automation: { status: "partial", spec: "e2e/collections.spec.ts" },
    tags: ["collections", "create"],
  },
  {
    id: "TC-COL-012",
    feature: "COL",
    featureDoc: "collections.md",
    title: "Folder auth inheritance applies bearer from ancestor folder",
    type: "functional",
    priority: "P1",
    preconditions: ["Folder with bearer config; nested request without its own auth"],
    steps: [
      { order: 1, action: "click", elementId: "EL-COL-005", expected: "Folder Auth tab" },
      {
        order: 2,
        action: "select",
        elementId: "EL-RB-043",
        input: "Bearer",
        expected: "Token saved on folder",
      },
      {
        order: 3,
        action: "click",
        elementId: "EL-SID-010",
        input: "nested request",
        expected: "Opened tab Auth shows inherited bearer",
      },
    ],
    expectedResult: "Inheritance is a one-time merge at open; request-owned auth wins",
    elementIds: ["EL-COL-005", "EL-RB-015", "EL-SID-010"],
    automation: { status: "missing" },
    tags: ["collections", "inheritance", "auth"],
  },
];

export const extraHistoryDraftCases: TestCase[] = [
  {
    id: "TC-HD-003",
    feature: "HD",
    featureDoc: "history-drafts.md",
    title: "Sending a different URL adds a second history row",
    type: "functional",
    priority: "P1",
    preconditions: ["One history row already present"],
    steps: [
      {
        order: 1,
        action: "fill",
        elementId: "EL-RB-001",
        input: "https://mock.test/other",
        expected: "New URL",
      },
      { order: 2, action: "click", elementId: "EL-RB-011", expected: "Sent" },
      { order: 3, action: "click", elementId: "EL-SID-003", expected: "Two distinct history rows" },
    ],
    expectedResult: "Distinct URLs are not collapsed",
    elementIds: ["EL-RB-001", "EL-RB-011", "EL-SID-003"],
    automation: { status: "partial", spec: "e2e/history-drafts.spec.ts" },
    tags: ["history"],
  },
  {
    id: "TC-HD-004",
    feature: "HD",
    featureDoc: "history-drafts.md",
    title: "Draft tab groups requests in a host/path tree, not a flat list",
    type: "ui",
    priority: "P1",
    preconditions: ["Sent request to a host with a path"],
    steps: [
      { order: 1, action: "click", elementId: "EL-SID-004", expected: "Draft tab" },
      {
        order: 2,
        action: "verify",
        elementId: "EL-SID-014",
        expected: "Host folder then path/request, not a single flat row",
      },
    ],
    expectedResult: "Drafts are auto-organized by URL structure",
    elementIds: ["EL-SID-004", "EL-SID-014"],
    automation: { status: "partial", spec: "e2e/history-drafts.spec.ts" },
    tags: ["drafts", "tree"],
  },
  {
    id: "TC-HD-005",
    feature: "HD",
    featureDoc: "history-drafts.md",
    title: "Opening a draft loads the request into a tab",
    type: "functional",
    priority: "P0",
    preconditions: ["Draft tree has an entry"],
    steps: [
      { order: 1, action: "click", elementId: "EL-SID-004", expected: "Draft tab" },
      { order: 2, action: "click", elementId: "EL-SID-014", expected: "Tab URL matches draft" },
    ],
    expectedResult: "Drafts are reopenable composers",
    elementIds: ["EL-SID-004", "EL-SID-014", "EL-RB-001"],
    automation: { status: "partial" },
    tags: ["drafts", "open"],
  },
  {
    id: "TC-HD-006",
    feature: "HD",
    featureDoc: "history-drafts.md",
    title: "History and drafts persist across browser reload",
    type: "persistence",
    priority: "P0",
    preconditions: ["At least one sent request"],
    steps: [
      { order: 1, action: "reload", expected: "App reloads" },
      { order: 2, action: "click", elementId: "EL-SID-003", expected: "History row still present" },
      { order: 3, action: "click", elementId: "EL-SID-004", expected: "Draft tree still present" },
    ],
    expectedResult: "Browser localStorage round-trips history/drafts",
    elementIds: ["EL-SID-003", "EL-SID-004"],
    automation: { status: "missing" },
    tags: ["persistence", "history", "drafts"],
  },
  {
    id: "TC-HD-007",
    feature: "HD",
    featureDoc: "history-drafts.md",
    title: "Delete history row removes only that entry",
    type: "crud",
    priority: "P1",
    preconditions: ["Two history rows"],
    steps: [
      { order: 1, action: "hover", elementId: "EL-SID-009", expected: "Delete visible" },
      {
        order: 2,
        action: "click",
        elementId: "EL-SID-012",
        expected: "Row gone; other row remains",
      },
    ],
    expectedResult: "Per-row delete does not wipe all history",
    elementIds: ["EL-SID-009", "EL-SID-012"],
    automation: { status: "missing" },
    tags: ["history", "delete"],
  },
];

export const extraEnvironmentCases: TestCase[] = [
  {
    id: "TC-ENV-006",
    feature: "ENV",
    featureDoc: "environments.md",
    title: "Active env overrides globals for the same key",
    type: "functional",
    priority: "P1",
    preconditions: ["Globals baseUrl=global; Dev baseUrl=dev"],
    steps: [
      { order: 1, action: "click", elementId: "EL-ENV-013", expected: "Globals editor" },
      {
        order: 2,
        action: "type",
        elementId: "EL-ENV-006",
        input: "baseUrl=https://global.example",
        expected: "Global set",
      },
      {
        order: 3,
        action: "click",
        elementId: "EL-ENV-009",
        expected: "Dev active with different baseUrl",
      },
      {
        order: 4,
        action: "click",
        elementId: "EL-RB-011",
        expected: "Resolved URL uses Dev, not global",
      },
    ],
    expectedResult: "Precedence: active env > globals > built-ins",
    elementIds: ["EL-ENV-013", "EL-ENV-006", "EL-ENV-009", "EL-RB-011"],
    automation: { status: "missing" },
    tags: ["environment", "globals", "precedence"],
  },
  {
    id: "TC-ENV-007",
    feature: "ENV",
    featureDoc: "environments.md",
    title: "{{$uuid}} changes between consecutive sends",
    type: "functional",
    priority: "P2",
    preconditions: ["URL contains {{$uuid}}"],
    steps: [
      {
        order: 1,
        action: "type",
        elementId: "EL-RB-001",
        input: "https://mock.test/{{$uuid}}",
        expected: "Token chip",
      },
      { order: 2, action: "click", elementId: "EL-RB-011", expected: "First UUID on wire" },
      {
        order: 3,
        action: "click",
        elementId: "EL-RB-011",
        expected: "Second UUID different from first",
      },
    ],
    expectedResult: "Built-ins regenerate per send",
    elementIds: ["EL-RB-001", "EL-RB-011"],
    automation: { status: "missing" },
    tags: ["environment", "builtins"],
  },
  {
    id: "TC-ENV-008",
    feature: "ENV",
    featureDoc: "environments.md",
    title: "Secret lock masks value; eye reveals it",
    type: "ux",
    priority: "P1",
    preconditions: ["Env modal open with a variable"],
    steps: [
      { order: 1, action: "click", elementId: "EL-ENV-014", expected: "Value masked" },
      { order: 2, action: "click", input: "Reveal / eye", expected: "Plaintext shown" },
    ],
    expectedResult: "Secrets are masked in UI (plaintext at rest in v1)",
    elementIds: ["EL-ENV-014", "EL-ENV-007"],
    automation: { status: "missing" },
    tags: ["environment", "secret"],
  },
  {
    id: "TC-ENV-009",
    feature: "ENV",
    featureDoc: "environments.md",
    title: "Deleting the active env falls back to No environment",
    type: "crud",
    priority: "P1",
    preconditions: ["Active named environment"],
    steps: [
      { order: 1, action: "click", elementId: "EL-ENV-012", expected: "Env deleted" },
      {
        order: 2,
        action: "verify",
        elementId: "EL-APP-002",
        expected: "Header shows No environment",
      },
    ],
    expectedResult: "No dangling active env id",
    elementIds: ["EL-ENV-012", "EL-APP-002", "EL-ENV-001"],
    automation: { status: "missing" },
    tags: ["environment", "delete"],
  },
  {
    id: "TC-ENV-010",
    feature: "ENV",
    featureDoc: "environments.md",
    title: "Arrow keys navigate the full {{ suggestion list",
    type: "keyboard",
    priority: "P1",
    preconditions: ["Env with several variables"],
    steps: [
      {
        order: 1,
        action: "type",
        elementId: "EL-RB-001",
        input: "{{",
        expected: "Suggestions open",
      },
      {
        order: 2,
        action: "keyboard",
        input: "ArrowDown repeatedly",
        expected: "Highlight walks entire list",
      },
      { order: 3, action: "keyboard", input: "Enter", expected: "Selected var inserted" },
    ],
    expectedResult: "Keyboard nav is not truncated to the first few items",
    elementIds: ["EL-RB-001", "EL-ENV-008"],
    automation: {
      status: "covered",
      spec: "e2e/environments.spec.ts",
      testName: "arrow keys navigate the whole suggestion list",
    },
    tags: ["environment", "autocomplete", "keyboard"],
  },
];

export const extraImportExportCases: TestCase[] = [
  {
    id: "TC-IE-005",
    feature: "IE",
    featureDoc: "import-export.md",
    title: "URL-bar paste of curl POST JSON applies method, headers, and body",
    type: "functional",
    priority: "P1",
    preconditions: ["Empty tab"],
    steps: [
      {
        order: 1,
        action: "fill",
        elementId: "EL-RB-001",
        input:
          "curl -X POST https://api.example.com/x -H 'Content-Type: application/json' -d '{\"a\":1}'",
        expected: "Parsed",
      },
      { order: 2, action: "verify", elementId: "EL-RB-002", expected: "POST" },
      { order: 3, action: "click", elementId: "EL-RB-017", expected: 'JSON body contains {"a":1}' },
    ],
    expectedResult: "URL-bar curl handles POST JSON, not only GET",
    elementIds: ["EL-RB-001", "EL-RB-002", "EL-RB-017"],
    automation: { status: "partial", spec: "e2e/import-curl.spec.ts" },
    tags: ["import", "curl", "post"],
  },
  {
    id: "TC-IE-006",
    feature: "IE",
    featureDoc: "import-export.md",
    title: "Invalid Postman JSON shows error without crash",
    type: "edge",
    priority: "P1",
    preconditions: ["Import modal Postman mode"],
    steps: [
      { order: 1, action: "click", elementId: "EL-IE-002", expected: "Postman mode" },
      {
        order: 2,
        action: "fill",
        elementId: "EL-IE-005",
        input: "{not json",
        expected: "Error, app still usable",
      },
      { order: 3, action: "verify", elementId: "EL-IE-007", expected: "Validation message" },
    ],
    expectedResult: "Postman import fails closed",
    elementIds: ["EL-IE-002", "EL-IE-005", "EL-IE-007"],
    automation: { status: "missing" },
    tags: ["import", "postman", "error"],
  },
  {
    id: "TC-IE-007",
    feature: "IE",
    featureDoc: "import-export.md",
    title: "Round-trip: import curl → tweak → copy → re-import",
    type: "functional",
    priority: "P2",
    preconditions: ["Valid curl import"],
    steps: [
      { order: 1, action: "click", elementId: "EL-IE-004", expected: "Tab created" },
      {
        order: 2,
        action: "type",
        elementId: "EL-RB-020",
        input: "X-Extra: 1",
        expected: "Header added",
      },
      {
        order: 3,
        action: "click",
        elementId: "EL-APP-006",
        expected: "Copied curl includes X-Extra",
      },
      {
        order: 4,
        action: "click",
        elementId: "EL-IE-004",
        expected: "Re-import matches tweaked request",
      },
    ],
    expectedResult: "Export/import fidelity after edits",
    elementIds: ["EL-IE-004", "EL-APP-006", "EL-RB-020"],
    automation: { status: "missing" },
    tags: ["import", "export", "round-trip"],
  },
];

export const extraPaletteCases: TestCase[] = [
  {
    id: "TC-CP-004",
    feature: "CP",
    featureDoc: "command-palette.md",
    title: "⌘K works from empty-request state and from a filled tab",
    type: "keyboard",
    priority: "P1",
    preconditions: ["REST workspace"],
    steps: [
      { order: 1, action: "keyboard", input: "Meta+K", expected: "Palette from empty tab" },
      { order: 2, action: "keyboard", input: "Escape", expected: "Closed" },
      {
        order: 3,
        action: "type",
        elementId: "EL-RB-001",
        input: "https://api.example.com",
        expected: "URL set",
      },
      { order: 4, action: "keyboard", input: "Meta+K", expected: "Palette still opens" },
    ],
    expectedResult: "Palette is global, not blocked by empty state",
    elementIds: ["EL-CP-001", "EL-RB-001"],
    automation: { status: "partial", spec: "e2e/command-palette.spec.ts" },
    tags: ["palette", "keyboard"],
  },
  {
    id: "TC-CP-005",
    feature: "CP",
    featureDoc: "command-palette.md",
    title: "Opening a result reuses a single empty tab vs opens a new tab when dirty",
    type: "ux",
    priority: "P1",
    preconditions: ["Saved collection request; one empty tab"],
    steps: [
      { order: 1, action: "keyboard", input: "Meta+K", expected: "Palette" },
      {
        order: 2,
        action: "click",
        elementId: "EL-CP-003",
        expected: "Empty tab reused (tab count unchanged)",
      },
      { order: 3, action: "keyboard", input: "Meta+K", expected: "Palette again" },
      {
        order: 4,
        action: "click",
        elementId: "EL-CP-003",
        expected: "New tab because current has content",
      },
    ],
    expectedResult: "Tab reuse policy matches command-palette.md",
    elementIds: ["EL-CP-003", "EL-TAB-001"],
    automation: { status: "missing" },
    tags: ["palette", "tabs"],
  },
];

export const extraSettingsCases: TestCase[] = [
  {
    id: "TC-SET-004",
    feature: "SET",
    featureDoc: "settings.md",
    title: "Word wrap switch in General applies to body and response",
    type: "functional",
    priority: "P1",
    preconditions: ["Settings open on General"],
    steps: [
      { order: 1, action: "click", elementId: "EL-SET-008", expected: "Wrap toggled" },
      { order: 2, action: "verify", elementId: "EL-RB-024", expected: "Body wrap matches" },
    ],
    expectedResult: "Settings is the source of truth for wrap",
    elementIds: ["EL-SET-008", "EL-RB-024"],
    automation: { status: "missing" },
    tags: ["settings", "word-wrap"],
  },
  {
    id: "TC-SET-005",
    feature: "SET",
    featureDoc: "settings.md",
    title: "Proxy URL on Requests tab is stored in localStorage",
    type: "persistence",
    priority: "P2",
    preconditions: ["Settings → Requests"],
    steps: [
      { order: 1, action: "click", elementId: "EL-SET-020", expected: "Requests" },
      {
        order: 2,
        action: "fill",
        elementId: "EL-SET-013",
        input: "http://proxy:8080",
        expected: "Value stored",
      },
      { order: 3, action: "reload", expected: "Proxy field still filled" },
    ],
    expectedResult: "pg_proxy_url persists",
    elementIds: ["EL-SET-013", "EL-SET-020"],
    automation: { status: "missing" },
    tags: ["settings", "proxy", "persistence"],
  },
  {
    id: "TC-SET-006",
    feature: "SET",
    featureDoc: "settings.md",
    title: "Clear History only wipes history counts, not collections",
    type: "crud",
    priority: "P1",
    preconditions: ["History, drafts, and a collection exist"],
    steps: [
      { order: 1, action: "click", elementId: "EL-SET-021", expected: "Data tab" },
      { order: 2, action: "click", elementId: "EL-SET-016", expected: "History count 0" },
      {
        order: 3,
        action: "verify",
        elementId: "EL-SET-022",
        expected: "Collections count unchanged",
      },
    ],
    expectedResult: "Scoped clears do not touch collections",
    elementIds: ["EL-SET-016", "EL-SET-011", "EL-SET-022"],
    automation: { status: "partial", spec: "e2e/settings-theme.spec.ts" },
    tags: ["settings", "data", "clear"],
  },
  {
    id: "TC-SET-007",
    feature: "SET",
    featureDoc: "settings.md",
    title: "Clear Drafts only wipes drafts",
    type: "crud",
    priority: "P1",
    preconditions: ["Drafts and history exist"],
    steps: [
      { order: 1, action: "click", elementId: "EL-SET-017", expected: "Drafts count 0" },
      { order: 2, action: "verify", elementId: "EL-SET-011", expected: "History still non-zero" },
    ],
    expectedResult: "Clear Drafts is independent of history",
    elementIds: ["EL-SET-017", "EL-SET-011"],
    automation: { status: "missing" },
    tags: ["settings", "drafts", "clear"],
  },
  {
    id: "TC-SET-008",
    feature: "SET",
    featureDoc: "settings.md",
    title: "SSL Verification off shows a destructive warning",
    type: "ui",
    priority: "P2",
    preconditions: ["Settings → Requests"],
    steps: [
      { order: 1, action: "click", elementId: "EL-SET-015", expected: "SSL off" },
      { order: 2, action: "verify", expected: "Certificate warning banner visible" },
    ],
    expectedResult: "Dangerous request option is explicitly warned",
    elementIds: ["EL-SET-015"],
    automation: { status: "missing" },
    tags: ["settings", "ssl", "security"],
  },
  {
    id: "TC-SET-009",
    feature: "SET",
    featureDoc: "settings.md",
    title: "Save snapshots toggle changes history reopen behavior",
    type: "functional",
    priority: "P1",
    preconditions: ["Settings → Data"],
    steps: [
      { order: 1, action: "click", elementId: "EL-SET-010", expected: "Snapshots off" },
      { order: 2, action: "click", elementId: "EL-RB-011", expected: "Send" },
      {
        order: 3,
        action: "click",
        elementId: "EL-SID-009",
        expected: "History open does not restore a full body snapshot",
      },
    ],
    expectedResult: "pg_save_snapshots gates stored bodies",
    elementIds: ["EL-SET-010", "EL-SID-009", "EL-RV-009"],
    automation: { status: "missing" },
    tags: ["settings", "snapshots", "history"],
  },
  {
    id: "TC-SET-010",
    feature: "SET",
    featureDoc: "settings.md",
    title: "Settings tabs General / Requests / Data / About all render",
    type: "ui",
    priority: "P1",
    preconditions: ["Settings open"],
    steps: [
      { order: 1, action: "click", elementId: "EL-SET-020", expected: "Follow Redirects visible" },
      { order: 2, action: "click", elementId: "EL-SET-021", expected: "Storage counts visible" },
      { order: 3, action: "click", input: "About", expected: "Version shown" },
    ],
    expectedResult: "All four settings sections are reachable",
    elementIds: ["EL-SET-020", "EL-SET-021"],
    automation: {
      status: "covered",
      spec: "e2e/settings-theme.spec.ts",
      testName: "navigates settings tabs",
    },
    tags: ["settings", "navigation"],
  },
  {
    id: "TC-PER-002",
    feature: "PER",
    featureDoc: "persistence.md",
    title: "Data tab counts update after Clear History",
    type: "persistence",
    priority: "P1",
    preconditions: ["History length > 0; Data tab open"],
    steps: [
      { order: 1, action: "verify", elementId: "EL-SET-011", expected: "Non-zero history count" },
      {
        order: 2,
        action: "click",
        elementId: "EL-SET-016",
        expected: "Count becomes 0 immediately",
      },
    ],
    expectedResult: "Counts are live, not stale",
    elementIds: ["EL-SET-011", "EL-SET-016"],
    automation: { status: "partial", spec: "e2e/settings-theme.spec.ts" },
    tags: ["persistence", "counts"],
  },
];

export const extraContentTypeCases: TestCase[] = [
  {
    id: "TC-CT-004",
    feature: "CT",
    featureDoc: "content-types.md",
    title: "Form Data text + file field sends multipart",
    type: "functional",
    priority: "P1",
    preconditions: ["POST tab"],
    steps: [
      { order: 1, action: "click", elementId: "EL-RB-029", expected: "Form Data" },
      { order: 2, action: "type", input: "text field + file field", expected: "Rows filled" },
      {
        order: 3,
        action: "click",
        elementId: "EL-RB-011",
        expected: "Content-Type multipart/form-data on wire",
      },
    ],
    expectedResult: "Form Data uses multipart, not urlencoded",
    elementIds: ["EL-RB-029", "EL-RB-011"],
    automation: { status: "missing" },
    tags: ["body", "form-data", "multipart"],
  },
  {
    id: "TC-CT-005",
    feature: "CT",
    featureDoc: "content-types.md",
    title: "Binary body picker accepts a file and can preview PDF responses",
    type: "functional",
    priority: "P2",
    preconditions: ["POST tab; PDF fixture"],
    steps: [
      { order: 1, action: "click", elementId: "EL-RB-031", expected: "Binary selected" },
      { order: 2, action: "click", elementId: "EL-RB-045", expected: "File chosen" },
      {
        order: 3,
        action: "click",
        elementId: "EL-RB-011",
        expected: "Binary sent; PDF iframe if response is PDF",
      },
    ],
    expectedResult: "Binary path works end to end",
    elementIds: ["EL-RB-031", "EL-RB-045"],
    automation: { status: "missing" },
    tags: ["body", "binary"],
  },
  {
    id: "TC-CT-006",
    feature: "CT",
    featureDoc: "content-types.md",
    title: "Raw body Text/XML format dropdown changes editor language",
    type: "ui",
    priority: "P1",
    preconditions: ["Body tab"],
    steps: [
      { order: 1, action: "click", elementId: "EL-RB-034", expected: "Raw selected" },
      { order: 2, action: "select", input: "XML", expected: "Format dropdown XML" },
      {
        order: 3,
        action: "type",
        elementId: "EL-RB-032",
        input: "<root/>",
        expected: "Editor accepts XML",
      },
    ],
    expectedResult: "Raw formats are selectable",
    elementIds: ["EL-RB-034"],
    automation: {
      status: "covered",
      spec: "e2e/body-editor.spec.ts",
      testName: "Raw body with Text/XML format dropdown",
    },
    tags: ["body", "raw"],
  },
  {
    id: "TC-CT-007",
    feature: "CT",
    featureDoc: "content-types.md",
    title: "HTML response Preview is sandboxed (scripts do not run)",
    type: "accessibility",
    priority: "P1",
    preconditions: ["Mock HTML with <script>alert(1)</script>"],
    steps: [
      { order: 1, action: "click", elementId: "EL-RV-018", expected: "Preview iframe" },
      {
        order: 2,
        action: "verify",
        elementId: "EL-RV-007",
        expected: "sandbox attribute present; no alert",
      },
    ],
    expectedResult: "HTML preview cannot execute page scripts",
    elementIds: ["EL-RV-007", "EL-RV-018"],
    automation: { status: "missing" },
    tags: ["html", "security", "preview"],
  },
];

export const extraKeyboardCases: TestCase[] = [
  {
    id: "TC-KB-002",
    feature: "KB",
    featureDoc: "keyboard-shortcuts.md",
    title: "With command palette open, other global chords do not fire",
    type: "keyboard",
    priority: "P1",
    preconditions: ["Palette open"],
    steps: [
      { order: 1, action: "keyboard", input: "Meta+K", expected: "Palette open" },
      {
        order: 2,
        action: "keyboard",
        input: "Meta+T",
        expected: "No new tab; key stays in palette",
      },
      {
        order: 3,
        action: "keyboard",
        input: "Escape",
        expected: "Palette closes; chords work again",
      },
    ],
    expectedResult: "Palette suppresses other globals while focused",
    elementIds: ["EL-CP-001", "EL-TAB-001"],
    automation: { status: "missing" },
    tags: ["keyboard", "palette"],
  },
  {
    id: "TC-KB-003",
    feature: "KB",
    featureDoc: "keyboard-shortcuts.md",
    title: "⌘L focuses the URL bar",
    type: "keyboard",
    priority: "P1",
    preconditions: ["REST workspace"],
    steps: [{ order: 1, action: "keyboard", input: "Meta+L", expected: "url-input focused" }],
    expectedResult: "⌘L is the URL focus chord",
    elementIds: ["EL-RB-001"],
    automation: { status: "missing" },
    tags: ["keyboard", "url"],
  },
  {
    id: "TC-KB-004",
    feature: "KB",
    featureDoc: "keyboard-shortcuts.md",
    title: "⌘\\ toggles sidebar collapse",
    type: "keyboard",
    priority: "P1",
    preconditions: ["Sidebar expanded"],
    steps: [
      { order: 1, action: "keyboard", input: "Meta+\\", expected: "Sidebar collapsed" },
      { order: 2, action: "keyboard", input: "Meta+\\", expected: "Sidebar expanded" },
    ],
    expectedResult: "Sidebar chord matches docs",
    elementIds: ["EL-SID-006", "EL-SID-007"],
    automation: { status: "missing" },
    tags: ["keyboard", "sidebar"],
  },
  {
    id: "TC-KB-005",
    feature: "KB",
    featureDoc: "keyboard-shortcuts.md",
    title: "⌘⇧S always opens Save to Collection (Save As)",
    type: "keyboard",
    priority: "P0",
    preconditions: ["Tab with URL; may already be collection-linked"],
    steps: [
      {
        order: 1,
        action: "keyboard",
        input: "Meta+Shift+S",
        expected: "Save modal opens even if tab is linked",
      },
    ],
    expectedResult: "Save As is distinct from in-place ⌘S",
    elementIds: ["EL-COL-003"],
    automation: { status: "missing" },
    tags: ["keyboard", "save"],
  },
  {
    id: "TC-KB-006",
    feature: "KB",
    featureDoc: "keyboard-shortcuts.md",
    title: "⌘⇧E opens Environment Manager",
    type: "keyboard",
    priority: "P1",
    preconditions: ["REST workspace"],
    steps: [{ order: 1, action: "keyboard", input: "Meta+Shift+E", expected: "Env modal visible" }],
    expectedResult: "Env manager has a global chord",
    elementIds: ["EL-ENV-004"],
    automation: { status: "missing" },
    tags: ["keyboard", "environment"],
  },
  {
    id: "TC-KB-007",
    feature: "KB",
    featureDoc: "keyboard-shortcuts.md",
    title: "⌘F outside body/response focuses header search",
    type: "keyboard",
    priority: "P1",
    preconditions: ["URL bar focused; no find bar"],
    steps: [
      { order: 1, action: "click", elementId: "EL-RB-001", expected: "URL focused" },
      { order: 2, action: "keyboard", input: "Meta+F", expected: "Header search focused" },
    ],
    expectedResult: "Default find target is sidebar/header search",
    elementIds: ["EL-RB-001", "EL-APP-001"],
    automation: {
      status: "covered",
      spec: "e2e/shortcuts.spec.ts",
      testName: "⌘F focuses the header search input",
    },
    tags: ["keyboard", "search"],
  },
];

export const extraSharedUiCases: TestCase[] = [
  {
    id: "TC-SUI-003",
    feature: "SUI",
    featureDoc: "shared-ui.md",
    title: "KeyValueEditor: add 30 rows, disable one, delete one",
    type: "functional",
    priority: "P1",
    preconditions: ["Headers tab"],
    steps: [
      {
        order: 1,
        action: "click",
        elementId: "EL-RB-023",
        input: "until 30 rows",
        expected: "List scrolls",
      },
      { order: 2, action: "uncheck", elementId: "EL-RB-041", expected: "One row disabled" },
      { order: 3, action: "click", elementId: "EL-RB-044", expected: "Row removed" },
    ],
    expectedResult: "Shared KV editor handles dense lists",
    elementIds: ["EL-RB-023", "EL-RB-041", "EL-RB-044"],
    automation: { status: "partial", spec: "e2e/long-values.spec.ts" },
    tags: ["kv-editor"],
  },
  {
    id: "TC-SUI-004",
    feature: "SUI",
    featureDoc: "shared-ui.md",
    title: "Confirm modal Cancel leaves the collection intact",
    type: "ux",
    priority: "P1",
    preconditions: ["Collection delete confirm open"],
    steps: [
      { order: 1, action: "click", elementId: "EL-SID-012", expected: "Confirm open" },
      { order: 2, action: "click", input: "Cancel", expected: "Collection still in sidebar" },
    ],
    expectedResult: "Destructive confirms are abortable",
    elementIds: ["EL-SID-012", "EL-COL-008"],
    automation: { status: "missing" },
    tags: ["modal", "confirm"],
  },
];

export const extraMcpCases: TestCase[] = [
  {
    id: "TC-MCP-003",
    feature: "MCP",
    featureDoc: "mcp.md",
    title: "[Retained] Connect URL with unresolved {{var}} fails loudly",
    type: "functional",
    priority: "P2",
    preconditions: ["MCP bench enabled"],
    steps: [
      {
        order: 1,
        action: "type",
        elementId: "EL-MCP-002",
        input: "{{missing}}/mcp",
        expected: "URL entered",
      },
      { order: 2, action: "click", elementId: "EL-MCP-003", expected: "mcp-error; no crash" },
    ],
    expectedResult: "MCP connect uses the same strict interpolation as REST send",
    elementIds: ["EL-MCP-002", "EL-MCP-003", "EL-MCP-006"],
    automation: { status: "manual-only" },
    tags: ["mcp", "bench", "environment"],
  },
  {
    id: "TC-MCP-004",
    feature: "MCP",
    featureDoc: "mcp.md",
    title: "[Retained] Tool schema splits form fields vs raw JSON args",
    type: "functional",
    priority: "P2",
    preconditions: ["Connected; tools listed"],
    steps: [
      { order: 1, action: "click", input: "scalar tool", expected: "Form fields via mcp-arg-*" },
      {
        order: 2,
        action: "click",
        input: "object/array tool",
        expected: "Raw JSON args (EL-MCP-009)",
      },
    ],
    expectedResult: "Schema complexity chooses form vs raw",
    elementIds: ["EL-MCP-009", "EL-MCP-004"],
    automation: { status: "manual-only" },
    tags: ["mcp", "schema"],
  },
  {
    id: "TC-MCP-005",
    feature: "MCP",
    featureDoc: "mcp.md",
    title: "[Retained] Server killed mid-session surfaces mcp-error",
    type: "edge",
    priority: "P2",
    preconditions: ["Connected session"],
    steps: [
      { order: 1, action: "wait", input: "Kill MCP server", expected: "Process down" },
      {
        order: 2,
        action: "click",
        elementId: "EL-MCP-004",
        expected: "mcp-error; UI remains usable",
      },
    ],
    expectedResult: "Transport failure is contained",
    elementIds: ["EL-MCP-004", "EL-MCP-006"],
    automation: { status: "manual-only" },
    tags: ["mcp", "error"],
  },
];

export const extraGraphqlCases: TestCase[] = [
  {
    id: "TC-GQL-002",
    feature: "GQL",
    featureDoc: "graphql.md",
    title: "GraphQL-over-HTTP from REST using GraphQL content type",
    type: "functional",
    priority: "P2",
    preconditions: ["REST workspace; GraphQL HTTP endpoint"],
    steps: [
      { order: 1, action: "click", elementId: "EL-RB-004", expected: "POST" },
      { order: 2, action: "click", elementId: "EL-RB-034", expected: "Raw / GraphQL-capable body" },
      {
        order: 3,
        action: "click",
        elementId: "EL-RB-011",
        expected: "Query document sent over HTTP",
      },
    ],
    expectedResult: "Until GraphQL workspace ships, GraphQL is reachable via REST content types",
    elementIds: ["EL-RB-004", "EL-RB-034", "EL-RB-011"],
    automation: { status: "missing" },
    tags: ["graphql", "rest"],
  },
];

export const extraGapTestCases: TestCase[] = [
  ...extraAppShellCases,
  ...extraWorkspaceCases,
  ...extraSidebarCases,
  ...extraTabCases,
  ...extraRequestBuilderCases,
  ...extraResponseExecutionCases,
  ...extraCollectionCases,
  ...extraHistoryDraftCases,
  ...extraEnvironmentCases,
  ...extraImportExportCases,
  ...extraPaletteCases,
  ...extraSettingsCases,
  ...extraContentTypeCases,
  ...extraKeyboardCases,
  ...extraSharedUiCases,
  ...extraMcpCases,
  ...extraGraphqlCases,
];
