import type { TestCase } from "../types.js";

export const responseExecutionTestCases: TestCase[] = [
  {
    id: "TC-RV-001",
    feature: "RV",
    featureDoc: "response-viewer.md",
    title: "Send renders 200 JSON response with status, timing, and size",
    type: "functional",
    priority: "P0",
    preconditions: ["Mocked 200 JSON endpoint"],
    steps: [
      {
        order: 1,
        action: "type",
        elementId: "EL-RB-001",
        input: "https://mock.test/api",
        expected: "URL set",
      },
      {
        order: 2,
        action: "click",
        elementId: "EL-RB-011",
        expected: "Request in flight; Cancel visible",
      },
      { order: 3, action: "verify", elementId: "EL-RV-003", expected: "Status shows 200" },
      { order: 4, action: "verify", elementId: "EL-RV-004", expected: "JSON body pretty-printed" },
    ],
    expectedResult: "Successful response fully rendered",
    elementIds: ["EL-RB-001", "EL-RB-011", "EL-RV-003", "EL-RV-004"],
    automation: {
      status: "covered",
      spec: "e2e/send.spec.ts",
      testName: "sends and renders a 200 JSON response",
    },
    tags: ["send", "response"],
  },
  {
    id: "TC-RV-002",
    feature: "RV",
    featureDoc: "response-viewer.md",
    title: "Non-2xx empty body shows placeholder not blank pane",
    type: "ui",
    priority: "P1",
    preconditions: ["Mocked 404 empty body"],
    steps: [
      { order: 1, action: "click", elementId: "EL-RB-011", expected: "404 response received" },
      {
        order: 2,
        action: "verify",
        elementId: "EL-RV-002",
        expected: "Empty body placeholder visible",
      },
    ],
    expectedResult: "404 with no body shows guided empty state",
    elementIds: ["EL-RV-002", "EL-RV-003"],
    automation: {
      status: "covered",
      spec: "e2e/send.spec.ts",
      testName: "a non-2xx empty body shows the empty-body placeholder",
    },
    tags: ["response", "empty-body"],
  },
  {
    id: "TC-RV-003",
    feature: "RV",
    featureDoc: "response-viewer.md",
    title: "Pretty and Raw view modes toggle response formatting",
    type: "ui",
    priority: "P1",
    preconditions: ["JSON response visible"],
    steps: [
      { order: 1, action: "click", elementId: "EL-RV-005", expected: "Pretty formatted JSON" },
      { order: 2, action: "click", elementId: "EL-RV-006", expected: "Single-line raw JSON" },
    ],
    expectedResult: "View mode switches without re-fetching",
    elementIds: ["EL-RV-005", "EL-RV-006", "EL-RV-004"],
    automation: { status: "partial" },
    tags: ["response", "formatting"],
  },
  {
    id: "TC-RV-004",
    feature: "RV",
    featureDoc: "response-viewer.md",
    title: "⌘F in response panel opens find bar with match count",
    type: "keyboard",
    priority: "P1",
    preconditions: ["Response body with searchable text"],
    steps: [
      { order: 1, action: "click", elementId: "EL-RV-004", expected: "Response focused" },
      { order: 2, action: "keyboard", input: "Meta+F", expected: "Response find bar opens" },
      {
        order: 3,
        action: "type",
        elementId: "EL-RV-011",
        input: "userId",
        expected: "Matches highlighted; count shown",
      },
    ],
    expectedResult: "In-panel find works without stealing global search",
    elementIds: ["EL-RV-004", "EL-RV-011"],
    automation: { status: "covered", spec: "e2e/find-and-kind-tabs.spec.ts" },
    tags: ["find", "keyboard"],
  },
  {
    id: "TC-RV-005",
    feature: "RV",
    featureDoc: "response-viewer.md",
    title: "History snapshot opens without re-sending request",
    type: "functional",
    priority: "P0",
    preconditions: ["Prior sent request in History"],
    steps: [
      { order: 1, action: "click", elementId: "EL-SID-003", expected: "History tab" },
      { order: 2, action: "click", elementId: "EL-SID-009", expected: "History row opens tab" },
      { order: 3, action: "verify", elementId: "EL-RV-009", expected: "Snapshot label visible" },
      {
        order: 4,
        action: "verify",
        elementId: "EL-RV-004",
        expected: "Stored response body shown; zero new network calls",
      },
    ],
    expectedResult: "History replay is snapshot-only",
    elementIds: ["EL-SID-003", "EL-SID-009", "EL-RV-009", "EL-RV-004"],
    automation: { status: "covered", spec: "e2e/history-drafts.spec.ts" },
    tags: ["history", "snapshot"],
  },
  {
    id: "TC-EX-001",
    feature: "EX",
    featureDoc: "execution.md",
    title: "Send button disabled until valid URL entered",
    type: "ux",
    priority: "P0",
    preconditions: ["New empty tab"],
    steps: [
      { order: 1, action: "verify", elementId: "EL-RB-011", expected: "Send disabled" },
      {
        order: 2,
        action: "type",
        elementId: "EL-RB-001",
        input: "https://api.example.com",
        expected: "Send enabled",
      },
    ],
    expectedResult: "Send gated on URL presence",
    elementIds: ["EL-RB-011", "EL-RB-001"],
    automation: { status: "partial", spec: "e2e/smoke.spec.ts" },
    tags: ["send", "validation"],
  },
  {
    id: "TC-EX-002",
    feature: "EX",
    featureDoc: "execution.md",
    title: "⌘Enter sends active request from URL focus",
    type: "keyboard",
    priority: "P0",
    preconditions: ["Mocked endpoint; URL filled"],
    steps: [
      { order: 1, action: "click", elementId: "EL-RB-001", expected: "URL focused" },
      { order: 2, action: "keyboard", input: "Meta+Enter", expected: "Request sent" },
      { order: 3, action: "verify", elementId: "EL-RV-003", expected: "Response status visible" },
    ],
    expectedResult: "⌘Enter triggers send",
    elementIds: ["EL-RB-001", "EL-RV-003"],
    automation: {
      status: "partial",
      spec: "e2e/shortcuts.spec.ts",
      testName: "⌘Enter sends the active request",
    },
    tags: ["keyboard", "send", "known-failure"],
  },
  {
    id: "TC-EX-003",
    feature: "EX",
    featureDoc: "execution.md",
    title: "Cancel button aborts in-flight request",
    type: "functional",
    priority: "P2",
    preconditions: ["Slow endpoint"],
    steps: [
      { order: 1, action: "click", elementId: "EL-RB-011", expected: "Cancel replaces Send" },
      {
        order: 2,
        action: "click",
        elementId: "EL-RV-010",
        expected: "Request aborted; Send restored",
      },
    ],
    expectedResult: "User can cancel long requests",
    elementIds: ["EL-RB-011", "EL-RV-010"],
    automation: { status: "missing" },
    tags: ["send", "cancel"],
  },
];

export const collectionTestCases: TestCase[] = [
  {
    id: "TC-COL-001",
    feature: "COL",
    featureDoc: "collections.md",
    title: "Create collection persists across reload",
    type: "crud",
    priority: "P0",
    preconditions: ["Collections tab; no collections"],
    steps: [
      { order: 1, action: "click", elementId: "EL-SID-005", expected: "Collections tab" },
      { order: 2, action: "click", elementId: "EL-COL-001", expected: "Name modal opens" },
      {
        order: 3,
        action: "type",
        elementId: "EL-COL-002",
        input: "My API",
        expected: "Name entered",
      },
      { order: 4, action: "click", input: "Create", expected: "Collection appears in tree" },
      { order: 5, action: "reload", expected: "Page reloads" },
      { order: 6, action: "verify", elementId: "EL-SID-010", expected: "My API still in sidebar" },
    ],
    expectedResult: "Collection CRUD persisted in localStorage/SQLite",
    elementIds: ["EL-SID-005", "EL-COL-001", "EL-COL-002", "EL-SID-010"],
    automation: {
      status: "covered",
      spec: "e2e/collections.spec.ts",
      testName: "creates a collection and persists",
    },
    tags: ["collections", "create", "persistence"],
  },
  {
    id: "TC-COL-002",
    feature: "COL",
    featureDoc: "collections.md",
    title: "Rename collection updates sidebar label",
    type: "crud",
    priority: "P1",
    preconditions: ["Existing collection"],
    steps: [
      { order: 1, action: "hover", elementId: "EL-SID-010", expected: "Row actions visible" },
      { order: 2, action: "click", input: "Rename", expected: "Name modal with current name" },
      {
        order: 3,
        action: "fill",
        elementId: "EL-COL-002",
        input: "Renamed API",
        expected: "New name saved",
      },
    ],
    expectedResult: "Collection rename reflected immediately",
    elementIds: ["EL-COL-002", "EL-SID-010"],
    automation: { status: "covered", spec: "e2e/collections.spec.ts" },
    tags: ["collections", "update"],
  },
  {
    id: "TC-COL-003",
    feature: "COL",
    featureDoc: "collections.md",
    title: "Save request into nested folder via ⌘⇧S modal",
    type: "crud",
    priority: "P0",
    preconditions: ["Collection with nested folder; tab with URL"],
    steps: [
      { order: 1, action: "keyboard", input: "Meta+Shift+S", expected: "Save modal opens" },
      {
        order: 2,
        action: "click",
        elementId: "EL-COL-003",
        input: "Select folder destination",
        expected: "Destination chosen",
      },
      {
        order: 3,
        action: "click",
        input: "Save",
        expected: "Request appears under folder in tree",
      },
      {
        order: 4,
        action: "click",
        elementId: "EL-SID-010",
        input: "Saved request row",
        expected: "Request loads in tab with same URL",
      },
    ],
    expectedResult: "Save-as places request at chosen tree path",
    elementIds: ["EL-COL-003", "EL-SID-010", "EL-RB-001"],
    automation: { status: "partial", spec: "e2e/collections.spec.ts" },
    tags: ["collections", "save"],
  },
  {
    id: "TC-COL-004",
    feature: "COL",
    featureDoc: "collections.md",
    title: "Delete folder removes nested requests from tree",
    type: "crud",
    priority: "P0",
    preconditions: ["Folder with nested saved request"],
    steps: [
      {
        order: 1,
        action: "hover",
        elementId: "EL-SID-010",
        input: "Folder row",
        expected: "Delete action visible",
      },
      { order: 2, action: "click", input: "Delete", expected: "Confirm if prompted" },
      { order: 3, action: "click", elementId: "EL-COL-008", expected: "Confirm deletion" },
      {
        order: 4,
        action: "verify",
        elementId: "EL-SID-010",
        expected: "Folder and child requests gone from sidebar",
      },
    ],
    expectedResult: "Folder delete cascades to children",
    elementIds: ["EL-SID-010", "EL-COL-008"],
    automation: {
      status: "partial",
      spec: "e2e/collections.spec.ts",
      testName: "delete folder + collection",
    },
    tags: ["collections", "delete", "known-failure"],
  },
  {
    id: "TC-COL-005",
    feature: "COL",
    featureDoc: "collections.md",
    title: "Folder gear config inherits headers into nested request",
    type: "functional",
    priority: "P1",
    preconditions: ["Folder with config modal access"],
    steps: [
      {
        order: 1,
        action: "click",
        elementId: "EL-COL-004",
        expected: "Headers tab in folder config",
      },
      {
        order: 2,
        action: "type",
        elementId: "EL-COL-006",
        input: "X-Custom: inherited",
        expected: "Header saved on folder",
      },
      {
        order: 3,
        action: "click",
        elementId: "EL-SID-010",
        input: "Nested request",
        expected: "Request opens with inherited header",
      },
      {
        order: 4,
        action: "click",
        elementId: "EL-RB-016",
        expected: "Header visible unless overridden by request",
      },
    ],
    expectedResult: "Folder-level headers merge at open time",
    elementIds: ["EL-COL-004", "EL-COL-006", "EL-RB-016"],
    automation: {
      status: "covered",
      spec: "e2e/folder-config-layout.spec.ts",
      testName: "folder config headers appear in nested request editor",
    },
    tags: ["collections", "inheritance"],
  },
  {
    id: "TC-COL-006",
    feature: "COL",
    featureDoc: "collections.md",
    title: "Drag request between folders reorganizes tree",
    type: "ux",
    priority: "P1",
    preconditions: ["Two folders in same collection"],
    steps: [
      {
        order: 1,
        action: "drag",
        elementId: "EL-SID-010",
        input: "Request onto target folder",
        expected: "Drop highlight on EL-COL-007",
      },
      { order: 2, action: "drop", expected: "Request moves under target folder" },
      { order: 3, action: "reload", expected: "Move persisted" },
    ],
    expectedResult: "DnD move works within and across collections",
    elementIds: ["EL-SID-010", "EL-COL-007"],
    automation: { status: "partial", spec: "e2e/collections.spec.ts" },
    tags: ["collections", "dnd", "desktop"],
  },
];

export const historyDraftTestCases: TestCase[] = [
  {
    id: "TC-HD-001",
    feature: "HD",
    featureDoc: "history-drafts.md",
    title: "Sent request appears in both History and Draft",
    type: "functional",
    priority: "P0",
    preconditions: ["Fresh session"],
    steps: [
      { order: 1, action: "click", elementId: "EL-RB-011", expected: "Request sent successfully" },
      {
        order: 2,
        action: "click",
        elementId: "EL-SID-003",
        expected: "History shows entry with status badge",
      },
      {
        order: 3,
        action: "click",
        elementId: "EL-SID-004",
        expected: "Draft shows host-grouped entry",
      },
    ],
    expectedResult: "Send writes to history log and draft tree",
    elementIds: ["EL-RB-011", "EL-SID-003", "EL-SID-004"],
    automation: { status: "covered", spec: "e2e/history-drafts.spec.ts" },
    tags: ["history", "drafts"],
  },
  {
    id: "TC-HD-002",
    feature: "HD",
    featureDoc: "history-drafts.md",
    title: "Duplicate sends to same URL dedupe history entry",
    type: "functional",
    priority: "P1",
    preconditions: ["Same URL sent twice"],
    steps: [
      { order: 1, action: "click", elementId: "EL-RB-011", expected: "First send" },
      { order: 2, action: "click", elementId: "EL-RB-011", expected: "Second send" },
      {
        order: 3,
        action: "click",
        elementId: "EL-SID-003",
        expected: "Single history row for that URL/method",
      },
    ],
    expectedResult: "History dedupes identical requests",
    elementIds: ["EL-RB-011", "EL-SID-003"],
    automation: { status: "missing" },
    tags: ["history", "dedup"],
  },
];
