import type { TestCase } from "../types.js";

/**
 * REST-only pass: shortcut vs matching button, drag-and-drop, and remaining edge cases.
 * MCP / GraphQL workbenches are out of scope (coming-soon UI).
 */

export const restShortcutButtonPairCases: TestCase[] = [
  {
    id: "TC-KB-008",
    feature: "KB",
    featureDoc: "keyboard-shortcuts.md",
    title: "Send: ⌘Enter and the Send button perform the same action",
    type: "keyboard",
    priority: "P0",
    scope: "rest",
    preconditions: ["Mocked 200 endpoint; URL filled"],
    steps: [
      { order: 1, action: "click", elementId: "EL-RB-011", expected: "Response 200 via button" },
      { order: 2, action: "click", elementId: "EL-TAB-003", expected: "New tab" },
      {
        order: 3,
        action: "type",
        elementId: "EL-RB-001",
        input: "https://mock.test/via-kbd",
        expected: "URL set",
      },
      {
        order: 4,
        action: "keyboard",
        input: "Meta+Enter",
        expected: "Same send path as the button; status 200",
      },
    ],
    expectedResult: "Shortcut clicks the visible [data-send-btn]; button and chord are equivalent",
    elementIds: ["EL-RB-011", "EL-RB-001", "EL-RV-003"],
    automation: {
      status: "partial",
      spec: "e2e/shortcuts.spec.ts",
      testName: "⌘Enter sends the active request",
    },
    tags: ["keyboard", "button-pair", "send"],
  },
  {
    id: "TC-KB-009",
    feature: "KB",
    featureDoc: "keyboard-shortcuts.md",
    title: "New tab: ⌘T, ⌘⇧N, sidebar New Request, and tab-strip + are equivalent",
    type: "keyboard",
    priority: "P0",
    scope: "rest",
    preconditions: ["One empty tab"],
    steps: [
      {
        order: 1,
        action: "click",
        elementId: "EL-SID-001",
        expected: "Tab count +1 via sidebar button",
      },
      { order: 2, action: "click", elementId: "EL-TAB-003", expected: "Tab count +1 via strip +" },
      { order: 3, action: "keyboard", input: "Meta+T", expected: "Tab count +1 via ⌘T" },
      {
        order: 4,
        action: "keyboard",
        input: "Meta+Shift+N",
        expected: "Tab count +1 via ⌘⇧N alias",
      },
    ],
    expectedResult: "Four entry points all create a focused empty GET tab",
    elementIds: ["EL-SID-001", "EL-TAB-003"],
    automation: { status: "partial", spec: "e2e/tabs.spec.ts" },
    tags: ["keyboard", "button-pair", "tabs"],
  },
  {
    id: "TC-KB-010",
    feature: "KB",
    featureDoc: "keyboard-shortcuts.md",
    title: "Close tab: ⌘W and the tab × button are equivalent",
    type: "keyboard",
    priority: "P0",
    scope: "rest",
    preconditions: ["Two tabs"],
    steps: [
      { order: 1, action: "click", elementId: "EL-TAB-004", expected: "Active tab closed via ×" },
      { order: 2, action: "click", elementId: "EL-TAB-003", expected: "New tab" },
      { order: 3, action: "keyboard", input: "Meta+W", expected: "Active tab closed via shortcut" },
    ],
    expectedResult: "Close chord and close button share the same store action",
    elementIds: ["EL-TAB-004"],
    automation: { status: "covered", spec: "e2e/tabs.spec.ts", testName: "opens and closes tabs" },
    tags: ["keyboard", "button-pair", "tabs"],
  },
  {
    id: "TC-KB-011",
    feature: "KB",
    featureDoc: "keyboard-shortcuts.md",
    title: "Jump tab: ⌘1–⌘9 matches clicking that tab",
    type: "keyboard",
    priority: "P1",
    scope: "rest",
    preconditions: ["At least 3 tabs"],
    steps: [
      {
        order: 1,
        action: "click",
        elementId: "EL-TAB-013",
        expected: "First tab active via click",
      },
      { order: 2, action: "keyboard", input: "Meta+3", expected: "Third tab active via shortcut" },
      {
        order: 3,
        action: "keyboard",
        input: "Meta+9",
        expected: "No-op when fewer than 9 tabs; active tab unchanged",
      },
    ],
    expectedResult: "Digit jumps are index-based and no-op when the tab is missing",
    elementIds: ["EL-TAB-013", "EL-TAB-002"],
    automation: {
      status: "partial",
      spec: "e2e/tabs.spec.ts",
      testName: "supports Postman-style tab shortcuts",
    },
    tags: ["keyboard", "button-pair", "tabs", "edge"],
  },
  {
    id: "TC-KB-012",
    feature: "KB",
    featureDoc: "keyboard-shortcuts.md",
    title: "Settings: ⌘, and the header Settings button open the same drawer",
    type: "keyboard",
    priority: "P1",
    scope: "rest",
    preconditions: ["REST workspace"],
    steps: [
      { order: 1, action: "click", elementId: "EL-APP-007", expected: "Settings via button" },
      { order: 2, action: "keyboard", input: "Escape", expected: "Closed" },
      { order: 3, action: "keyboard", input: "Meta+Comma", expected: "Settings via shortcut" },
    ],
    expectedResult: "Chord and gear button are equivalent",
    elementIds: ["EL-APP-007"],
    automation: { status: "covered", spec: "e2e/shortcuts.spec.ts", testName: "⌘, opens Settings" },
    tags: ["keyboard", "button-pair", "settings"],
  },
  {
    id: "TC-KB-013",
    feature: "KB",
    featureDoc: "keyboard-shortcuts.md",
    title: "Environments: ⌘⇧E and Manage environments… open the same modal",
    type: "keyboard",
    priority: "P1",
    scope: "rest",
    preconditions: ["REST workspace"],
    steps: [
      { order: 1, action: "click", elementId: "EL-APP-002", expected: "Env dropdown" },
      { order: 2, action: "click", elementId: "EL-ENV-003", expected: "Manager via button" },
      { order: 3, action: "keyboard", input: "Escape", expected: "Closed" },
      {
        order: 4,
        action: "keyboard",
        input: "Meta+Shift+E",
        expected: "Same manager via shortcut",
      },
    ],
    expectedResult: "Env manager has a button path and a chord path",
    elementIds: ["EL-APP-002", "EL-ENV-003"],
    automation: { status: "missing" },
    tags: ["keyboard", "button-pair", "environment"],
  },
  {
    id: "TC-KB-014",
    feature: "KB",
    featureDoc: "keyboard-shortcuts.md",
    title: "Sidebar collapse: ⌘\\ and Hide/Show sidebar buttons are equivalent",
    type: "keyboard",
    priority: "P1",
    scope: "rest",
    preconditions: ["Sidebar expanded"],
    steps: [
      { order: 1, action: "click", elementId: "EL-SID-006", expected: "Collapsed via button" },
      { order: 2, action: "click", elementId: "EL-SID-007", expected: "Expanded via button" },
      { order: 3, action: "keyboard", input: "Meta+\\", expected: "Collapsed via shortcut" },
      { order: 4, action: "keyboard", input: "Meta+\\", expected: "Expanded via shortcut" },
    ],
    expectedResult: "Collapse is reachable from UI and keyboard",
    elementIds: ["EL-SID-006", "EL-SID-007"],
    automation: { status: "partial", spec: "e2e/smoke.spec.ts" },
    tags: ["keyboard", "button-pair", "sidebar"],
  },
  {
    id: "TC-KB-015",
    feature: "KB",
    featureDoc: "keyboard-shortcuts.md",
    title: "Focus URL: ⌘L, ⌘⌥2, and clicking the URL field are equivalent",
    type: "keyboard",
    priority: "P1",
    scope: "rest",
    preconditions: ["REST workspace"],
    steps: [
      { order: 1, action: "click", elementId: "EL-RB-001", expected: "Focused via click" },
      { order: 2, action: "click", elementId: "EL-APP-001", expected: "Focus leaves URL" },
      { order: 3, action: "keyboard", input: "Meta+L", expected: "URL focused + selected" },
      { order: 4, action: "click", elementId: "EL-APP-001", expected: "Focus leaves URL" },
      { order: 5, action: "keyboard", input: "Meta+Alt+2", expected: "URL focused via ⌘⌥2" },
    ],
    expectedResult: "Both focus chords match clicking the URL input",
    elementIds: ["EL-RB-001", "EL-APP-001"],
    automation: { status: "missing" },
    tags: ["keyboard", "button-pair", "url"],
  },
  {
    id: "TC-KB-016",
    feature: "KB",
    featureDoc: "keyboard-shortcuts.md",
    title: "⌘⌥1 focuses sidebar New Request (or Expand when collapsed)",
    type: "keyboard",
    priority: "P2",
    scope: "rest",
    preconditions: ["Sidebar expanded"],
    steps: [
      { order: 1, action: "keyboard", input: "Meta+Alt+1", expected: "EL-SID-001 focused" },
      { order: 2, action: "click", elementId: "EL-SID-006", expected: "Collapsed" },
      { order: 3, action: "keyboard", input: "Meta+Alt+1", expected: "EL-SID-007 Expand focused" },
    ],
    expectedResult: "Chord targets the visible sidebar CTA",
    elementIds: ["EL-SID-001", "EL-SID-007"],
    automation: { status: "missing" },
    tags: ["keyboard", "button-pair", "sidebar"],
  },
  {
    id: "TC-KB-017",
    feature: "KB",
    featureDoc: "keyboard-shortcuts.md",
    title: "Header search: ⌘F (outside find bars) matches clicking the search field",
    type: "keyboard",
    priority: "P1",
    scope: "rest",
    preconditions: ["URL bar focused; no body/response find open"],
    steps: [
      { order: 1, action: "click", elementId: "EL-APP-001", expected: "Search focused via click" },
      { order: 2, action: "click", elementId: "EL-RB-001", expected: "URL focused" },
      { order: 3, action: "keyboard", input: "Meta+F", expected: "Search focused via shortcut" },
    ],
    expectedResult: "Default find target is the header search input",
    elementIds: ["EL-APP-001", "EL-RB-001"],
    automation: { status: "covered", spec: "e2e/shortcuts.spec.ts" },
    tags: ["keyboard", "button-pair", "search"],
  },
  {
    id: "TC-KB-018",
    feature: "KB",
    featureDoc: "keyboard-shortcuts.md",
    title: "Command palette: ⌘K, ⌘⇧K, and ⌘⇧P all toggle the same overlay",
    type: "keyboard",
    priority: "P1",
    scope: "rest",
    preconditions: ["REST workspace"],
    steps: [
      { order: 1, action: "keyboard", input: "Meta+K", expected: "Palette open" },
      { order: 2, action: "keyboard", input: "Meta+K", expected: "Palette closed (toggle)" },
      { order: 3, action: "keyboard", input: "Meta+Shift+K", expected: "Palette open (alias)" },
      { order: 4, action: "keyboard", input: "Escape", expected: "Closed" },
      { order: 5, action: "keyboard", input: "Meta+Shift+P", expected: "Palette open (alias)" },
    ],
    expectedResult: "Primary chord and aliases share one overlay; there is no palette button",
    elementIds: ["EL-CP-001"],
    automation: { status: "partial", spec: "e2e/command-palette.spec.ts" },
    tags: ["keyboard", "palette", "alias"],
  },
  {
    id: "TC-KB-019",
    feature: "KB",
    featureDoc: "keyboard-shortcuts.md",
    title: "Import: sidebar Import button opens the modal (no dedicated chord)",
    type: "functional",
    priority: "P1",
    scope: "rest",
    preconditions: ["REST workspace"],
    steps: [
      { order: 1, action: "click", elementId: "EL-SID-002", expected: "Import modal" },
      { order: 2, action: "keyboard", input: "Escape", expected: "Closed via Esc (overlay stack)" },
    ],
    expectedResult: "Import is button-first; Esc dismisses like other overlays",
    elementIds: ["EL-SID-002"],
    automation: { status: "covered", spec: "e2e/import-curl.spec.ts" },
    tags: ["button-pair", "import"],
  },
  {
    id: "TC-KB-020",
    feature: "KB",
    featureDoc: "keyboard-shortcuts.md",
    title: "Save: empty URL makes ⌘S and ⌘⇧S no-ops (no modal)",
    type: "edge",
    priority: "P0",
    scope: "rest",
    preconditions: ["Empty URL tab"],
    steps: [
      { order: 1, action: "keyboard", input: "Meta+S", expected: "No save modal" },
      { order: 2, action: "keyboard", input: "Meta+Shift+S", expected: "No save modal" },
      {
        order: 3,
        action: "type",
        elementId: "EL-RB-001",
        input: "https://api.example.com",
        expected: "URL set",
      },
      { order: 4, action: "keyboard", input: "Meta+Shift+S", expected: "Save modal opens" },
    ],
    expectedResult: "Save chords require a URL; empty state does not pop a modal",
    elementIds: ["EL-RB-001", "EL-COL-003"],
    automation: { status: "missing" },
    tags: ["keyboard", "save", "edge"],
  },
  {
    id: "TC-KB-021",
    feature: "KB",
    featureDoc: "keyboard-shortcuts.md",
    title: "Shortcuts modal: ⌘⇧/ lists every REST chord; compare 1:1 with docs",
    type: "keyboard",
    priority: "P1",
    scope: "rest",
    preconditions: ["REST workspace"],
    steps: [
      { order: 1, action: "keyboard", input: "Meta+Shift+/", expected: "Modal open" },
      {
        order: 2,
        action: "verify",
        elementId: "EL-SET-012",
        expected:
          "Lists Send, New Tab, Close, ⌘1–9, palette, save, sidebar, settings, env — not MCP/GraphQL as primary REST actions",
      },
    ],
    expectedResult: "In-app list matches keyboard-shortcuts.md and AppContent.tsx",
    elementIds: ["EL-SET-012"],
    automation: { status: "partial", spec: "e2e/shortcuts.spec.ts" },
    tags: ["keyboard", "docs"],
  },
];

export const restDragDropCases: TestCase[] = [
  {
    id: "TC-TAB-011",
    feature: "TAB",
    featureDoc: "tabs.md",
    title: "Drag last tab to first position; order persists after reload",
    type: "ux",
    priority: "P0",
    scope: "rest",
    preconditions: ["Three tabs named /first /second /third"],
    steps: [
      {
        order: 1,
        action: "drag",
        elementId: "EL-TAB-002",
        input: "third tab onto first",
        expected: "Order becomes /third /first /second",
      },
      { order: 2, action: "reload", expected: "App reloads" },
      {
        order: 3,
        action: "verify",
        elementId: "EL-TAB-001",
        expected: "Order still /third /first /second (pg_open_tabs:rest)",
      },
    ],
    expectedResult: "Horizontal @dnd-kit tab reorder is persisted",
    elementIds: ["EL-TAB-001", "EL-TAB-002"],
    automation: {
      status: "covered",
      spec: "e2e/tabs.spec.ts",
      testName: "reorders tabs by drag and drop",
    },
    tags: ["dnd", "tabs", "persistence"],
  },
  {
    id: "TC-TAB-012",
    feature: "TAB",
    featureDoc: "tabs.md",
    title: "Tab drag has a distance threshold so a click still selects",
    type: "edge",
    priority: "P1",
    scope: "rest",
    preconditions: ["Two tabs; second inactive"],
    steps: [
      {
        order: 1,
        action: "click",
        input: "inactive tab without moving pointer",
        expected: "Tab becomes active; order unchanged",
      },
      {
        order: 2,
        action: "drag",
        input: "same tab a few pixels then cancel",
        expected: "No accidental reorder",
      },
    ],
    expectedResult: "Click-to-activate is not stolen by sortable drag",
    elementIds: ["EL-TAB-002"],
    automation: { status: "missing" },
    tags: ["dnd", "tabs", "edge"],
  },
  {
    id: "TC-TAB-013",
    feature: "TAB",
    featureDoc: "tabs.md",
    title: "Dragging a tab onto itself does not change order",
    type: "edge",
    priority: "P2",
    scope: "rest",
    preconditions: ["Three tabs"],
    steps: [
      {
        order: 1,
        action: "drag",
        input: "middle tab down and back onto itself",
        expected: "Order unchanged",
      },
    ],
    expectedResult: "No-op drop is safe",
    elementIds: ["EL-TAB-001"],
    automation: { status: "missing" },
    tags: ["dnd", "tabs", "edge"],
  },
  {
    id: "TC-TAB-014",
    feature: "TAB",
    featureDoc: "tabs.md",
    title: "Close button on a tab is not a drag handle",
    type: "edge",
    priority: "P1",
    scope: "rest",
    preconditions: ["Two tabs"],
    steps: [
      {
        order: 1,
        action: "click",
        elementId: "EL-TAB-004",
        expected: "Tab closes; sibling not reordered",
      },
    ],
    expectedResult: "× click never starts a drag",
    elementIds: ["EL-TAB-004"],
    automation: { status: "partial", spec: "e2e/tabs.spec.ts" },
    tags: ["dnd", "tabs", "edge"],
  },
  {
    id: "TC-COL-013",
    feature: "COL",
    featureDoc: "collections.md",
    title: "Drag request onto another folder; destination expands; persists after reload",
    type: "ux",
    priority: "P0",
    scope: "rest",
    preconditions: ["Collection with Folder A (request inside) and Folder B"],
    steps: [
      {
        order: 1,
        action: "drag",
        elementId: "EL-SID-010",
        input: "request onto Folder B",
        expected: "Drop highlight (EL-COL-007); Folder B expands",
      },
      { order: 2, action: "drop", expected: "Request is a child of Folder B" },
      { order: 3, action: "reload", expected: "Same tree after reload" },
    ],
    expectedResult: "In-collection move works in browser Playwright and desktop WDIO",
    elementIds: ["EL-SID-010", "EL-COL-007"],
    automation: {
      status: "partial",
      spec: "e2e/collections.spec.ts",
      testName: "adds folders and a request, then drags",
    },
    tags: ["dnd", "collections", "persistence"],
  },
  {
    id: "TC-COL-014",
    feature: "COL",
    featureDoc: "collections.md",
    title: "Drag request onto collection root un-nests it from its folder",
    type: "ux",
    priority: "P0",
    scope: "rest",
    preconditions: ["Request nested in a folder"],
    steps: [
      {
        order: 1,
        action: "drag",
        elementId: "EL-SID-010",
        input: "onto collection root row",
        expected: "Root drop highlight",
      },
      { order: 2, action: "drop", expected: "Request is a direct child of the collection" },
    ],
    expectedResult: "Root is a valid drop target",
    elementIds: ["EL-SID-010", "EL-COL-007"],
    automation: { status: "missing" },
    tags: ["dnd", "collections"],
  },
  {
    id: "TC-COL-015",
    feature: "COL",
    featureDoc: "collections.md",
    title: "Drag request onto another collection (root or folder)",
    type: "ux",
    priority: "P0",
    scope: "rest",
    preconditions: ["Two collections; request in collection A"],
    steps: [
      {
        order: 1,
        action: "drag",
        elementId: "EL-SID-010",
        input: "onto collection B root or folder",
        expected: "Drop highlight on B",
      },
      { order: 2, action: "drop", expected: "Request leaves A; appears under B; B expands" },
    ],
    expectedResult: "Cross-collection move is supported",
    elementIds: ["EL-SID-010", "EL-COL-007"],
    automation: { status: "missing" },
    tags: ["dnd", "collections", "cross-collection"],
  },
  {
    id: "TC-COL-016",
    feature: "COL",
    featureDoc: "collections.md",
    title: "Folders are drop targets only — dragging a folder does not move it",
    type: "edge",
    priority: "P1",
    scope: "rest",
    preconditions: ["Collection with Folder Auth containing nested folder Tokens"],
    steps: [
      {
        order: 1,
        action: "drag",
        input: "Folder Auth row several pixels",
        expected: "No drag overlay; folder stays put",
      },
      {
        order: 2,
        action: "verify",
        elementId: "EL-SID-010",
        expected: "Tree order unchanged (only requests use useDraggable)",
      },
    ],
    expectedResult:
      "UI cannot create a folder cycle because folders are not drag sources; store.moveNode still rejects descendant drops in unit tests",
    elementIds: ["EL-SID-010"],
    automation: { status: "missing" },
    tags: ["dnd", "collections", "edge"],
  },
  {
    id: "TC-COL-017",
    feature: "COL",
    featureDoc: "collections.md",
    title: "Drop that would exceed MAX_NESTING_DEPTH (10) is rejected",
    type: "edge",
    priority: "P1",
    scope: "rest",
    preconditions: ["Deep folder chain at depth 10"],
    steps: [
      {
        order: 1,
        action: "drag",
        input: "a request/folder onto the deepest folder",
        expected: "Could not move that item here / tree unchanged",
      },
    ],
    expectedResult: "Nesting past 10 is blocked on drag as well as Add folder",
    elementIds: ["EL-SID-010"],
    automation: { status: "missing" },
    tags: ["dnd", "collections", "edge", "nesting"],
  },
  {
    id: "TC-COL-018",
    feature: "COL",
    featureDoc: "collections.md",
    title: "Collection drag starts only after ~6px move so click still opens the request",
    type: "edge",
    priority: "P1",
    scope: "rest",
    preconditions: ["Saved request in tree"],
    steps: [
      {
        order: 1,
        action: "click",
        elementId: "EL-SID-010",
        input: "request row without dragging",
        expected: "Request opens in a tab; not a move",
      },
    ],
    expectedResult: "PointerSensor distance: 6 keeps select vs drag distinct",
    elementIds: ["EL-SID-010", "EL-RB-001"],
    automation: { status: "partial", spec: "e2e/collections.spec.ts" },
    tags: ["dnd", "collections", "edge"],
  },
  {
    id: "TC-COL-019",
    feature: "COL",
    featureDoc: "collections.md",
    title: "Cancel in-progress collection drag (Esc / drop on empty) does not move",
    type: "edge",
    priority: "P2",
    scope: "rest",
    preconditions: ["Request in Folder A"],
    steps: [
      {
        order: 1,
        action: "drag",
        input: "start drag then press Escape",
        expected: "Request still in Folder A",
      },
    ],
    expectedResult: "handleDragCancel clears highlight without moveNode",
    elementIds: ["EL-SID-010", "EL-COL-007"],
    automation: { status: "missing" },
    tags: ["dnd", "collections", "edge"],
  },
  {
    id: "TC-COL-020",
    feature: "COL",
    featureDoc: "collections.md",
    title: "Hovering a folder during drag auto-expands it so nested drop targets appear",
    type: "ux",
    priority: "P1",
    scope: "rest",
    preconditions: ["Collapsed folder; dragging a request"],
    steps: [
      {
        order: 1,
        action: "drag",
        input: "hold over collapsed folder",
        expected: "Folder expands while dragging",
      },
    ],
    expectedResult: "Nested drop targets are reachable without a pre-click expand",
    elementIds: ["EL-SID-010"],
    automation: { status: "missing" },
    tags: ["dnd", "collections", "ux"],
  },
  {
    id: "TC-COL-021",
    feature: "COL",
    featureDoc: "collections.md",
    title: "Tree row action buttons (Rename/Delete/Add) do not start a drag",
    type: "edge",
    priority: "P1",
    scope: "rest",
    preconditions: ["Collection row hovered"],
    steps: [
      {
        order: 1,
        action: "click",
        elementId: "EL-SID-011",
        expected: "Rename modal; row not dragged",
      },
      { order: 2, action: "keyboard", input: "Escape", expected: "Modal closed" },
      {
        order: 3,
        action: "click",
        elementId: "EL-COL-010",
        expected: "Create Folder modal; no DnD",
      },
    ],
    expectedResult: "RowIconButton stopPropagation keeps actions clickable",
    elementIds: ["EL-SID-011", "EL-COL-010"],
    automation: { status: "partial", spec: "e2e/collections.spec.ts" },
    tags: ["dnd", "collections", "edge"],
  },
  {
    id: "TC-APP-010",
    feature: "APP",
    featureDoc: "app-shell.md",
    title: "Response split drag + double-click reset (layout DnD)",
    type: "ux",
    priority: "P1",
    scope: "rest",
    preconditions: ["REST layout with response panel"],
    steps: [
      { order: 1, action: "drag", elementId: "EL-APP-010", expected: "Split moves" },
      { order: 2, action: "dblclick", elementId: "EL-APP-010", expected: "Default ratio restored" },
    ],
    expectedResult: "Panel resize is a drag interaction distinct from tree/tab DnD",
    elementIds: ["EL-APP-010"],
    automation: { status: "covered", spec: "e2e/smoke.spec.ts" },
    tags: ["dnd", "layout"],
  },
];

export const restRemainingEdgeCases: TestCase[] = [
  {
    id: "TC-TAB-015",
    feature: "TAB",
    featureDoc: "tabs.md",
    title: "Closing the last tab leaves a replacement empty Untitled tab",
    type: "edge",
    priority: "P0",
    scope: "rest",
    preconditions: ["Single tab with a URL"],
    steps: [
      {
        order: 1,
        action: "click",
        elementId: "EL-TAB-004",
        expected: "Still one tab; empty Untitled + Load a sample",
      },
      { order: 2, action: "verify", elementId: "EL-RB-026", expected: "Empty-request CTA visible" },
    ],
    expectedResult: "Workspace never has zero tabs",
    elementIds: ["EL-TAB-004", "EL-RB-026"],
    automation: { status: "missing" },
    tags: ["tabs", "edge"],
  },
  {
    id: "TC-TAB-016",
    feature: "TAB",
    featureDoc: "tabs.md",
    title: "Rename Esc cancels without locking the name",
    type: "edge",
    priority: "P1",
    scope: "rest",
    preconditions: ["Tab auto-named /users"],
    steps: [
      { order: 1, action: "dblclick", elementId: "EL-TAB-002", expected: "Rename input" },
      { order: 2, action: "type", elementId: "EL-TAB-007", input: "Nope", expected: "Typed" },
      { order: 3, action: "keyboard", input: "Escape", expected: "Label still /users; not locked" },
    ],
    expectedResult: "Esc abort does not set nameLocked",
    elementIds: ["EL-TAB-002", "EL-TAB-007"],
    automation: { status: "missing" },
    tags: ["tabs", "rename", "edge"],
  },
  {
    id: "TC-TAB-017",
    feature: "TAB",
    featureDoc: "tabs.md",
    title: "Context menu New Request matches the + button",
    type: "crud",
    priority: "P1",
    scope: "rest",
    preconditions: ["One tab"],
    steps: [
      {
        order: 1,
        action: "click",
        elementId: "EL-TAB-002",
        input: "right-click",
        expected: "Menu",
      },
      {
        order: 2,
        action: "click",
        elementId: "EL-TAB-012",
        expected: "New empty tab; same as EL-TAB-003",
      },
    ],
    expectedResult: "Context New Request is a button equivalent of + / ⌘T",
    elementIds: ["EL-TAB-012", "EL-TAB-003"],
    automation: { status: "missing" },
    tags: ["tabs", "button-pair", "context-menu"],
  },
  {
    id: "TC-TAB-018",
    feature: "TAB",
    featureDoc: "tabs.md",
    title: "Esc closes tab context menu without closing the tab",
    type: "edge",
    priority: "P1",
    scope: "rest",
    preconditions: ["One tab"],
    steps: [
      {
        order: 1,
        action: "click",
        elementId: "EL-TAB-002",
        input: "right-click",
        expected: "Menu visible",
      },
      { order: 2, action: "keyboard", input: "Escape", expected: "Menu hidden; tab still open" },
      {
        order: 3,
        action: "type",
        elementId: "EL-RB-001",
        input: "https://api.example.com/after-menu",
        expected: "URL still editable",
      },
    ],
    expectedResult: "Esc is overlay-only, not Close Tab",
    elementIds: ["EL-TAB-002", "EL-RB-001"],
    automation: {
      status: "covered",
      spec: "e2e/tabs.spec.ts",
      testName: "Escape closes the tab context menu",
    },
    tags: ["tabs", "escape", "edge"],
  },
  {
    id: "TC-TAB-019",
    feature: "TAB",
    featureDoc: "tabs.md",
    title: "⌘⇧N is an alias of ⌘T (both create a tab)",
    type: "keyboard",
    priority: "P1",
    scope: "rest",
    preconditions: ["One tab"],
    steps: [{ order: 1, action: "keyboard", input: "Meta+Shift+N", expected: "Second tab" }],
    expectedResult: "Documented alternate new-tab chord works",
    elementIds: ["EL-TAB-001"],
    automation: { status: "missing" },
    tags: ["tabs", "keyboard", "alias"],
  },
  {
    id: "TC-RB-024",
    feature: "RB",
    featureDoc: "request-builder.md",
    title: "URL query with empty Params still sends the typed query",
    type: "edge",
    priority: "P1",
    scope: "rest",
    preconditions: ["URL ?raw=1 and Params rows all empty/disabled"],
    steps: [
      {
        order: 1,
        action: "type",
        elementId: "EL-RB-001",
        input: "https://mock.test/x?raw=1",
        expected: "Query in URL",
      },
      {
        order: 2,
        action: "click",
        elementId: "EL-RB-014",
        expected: "Params may be empty after clear",
      },
      {
        order: 3,
        action: "click",
        elementId: "EL-RB-011",
        expected: "Wire still has raw=1 when params empty",
      },
    ],
    expectedResult: "Params are authoritative only when present",
    elementIds: ["EL-RB-001", "EL-RB-014", "EL-RB-011"],
    automation: { status: "missing" },
    tags: ["params", "edge", "send"],
  },
  {
    id: "TC-RB-025",
    feature: "RB",
    featureDoc: "request-builder.md",
    title: "Inactive tab stays mounted: editing tab A then switching back keeps URL",
    type: "edge",
    priority: "P1",
    scope: "rest",
    preconditions: ["Two tabs with different URLs"],
    steps: [
      {
        order: 1,
        action: "type",
        elementId: "EL-RB-001",
        input: "https://a.example/1",
        expected: "Tab A URL",
      },
      { order: 2, action: "click", elementId: "EL-TAB-003", expected: "Tab B" },
      {
        order: 3,
        action: "type",
        elementId: "EL-RB-001",
        input: "https://b.example/2",
        expected: "Tab B URL",
      },
      {
        order: 4,
        action: "keyboard",
        input: "Meta+1",
        expected: "Back to A; URL still /1 (display:none mount)",
      },
    ],
    expectedResult: "Inactive editors are hidden, not unmounted",
    elementIds: ["EL-RB-001", "EL-TAB-003"],
    automation: { status: "partial", spec: "e2e/tabs.spec.ts" },
    tags: ["tabs", "edge", "state"],
  },
  {
    id: "TC-RB-026",
    feature: "RB",
    featureDoc: "request-builder.md",
    title: "OPTIONS request-target * is preserved (needs Host on desktop)",
    type: "edge",
    priority: "P2",
    scope: "rest",
    preconditions: ["REST workspace"],
    steps: [
      { order: 1, action: "click", elementId: "EL-RB-009", expected: "OPTIONS" },
      {
        order: 2,
        action: "fill",
        elementId: "EL-RB-001",
        input: "*",
        expected: "* accepted as URL/target",
      },
    ],
    expectedResult: "* is a valid OPTIONS target, not stripped",
    elementIds: ["EL-RB-009", "EL-RB-001"],
    automation: { status: "missing" },
    tags: ["method", "options", "edge"],
  },
  {
    id: "TC-ENV-011",
    feature: "ENV",
    featureDoc: "environments.md",
    title: "Duplicate and $prefixed variable keys are rejected inline",
    type: "edge",
    priority: "P1",
    scope: "rest",
    preconditions: ["Env modal; one var named baseUrl"],
    steps: [
      {
        order: 1,
        action: "type",
        elementId: "EL-ENV-006",
        input: "baseUrl on a second row",
        expected: "Duplicate key error",
      },
      { order: 2, action: "type", input: "$uuid as a custom key", expected: "$ prefix rejected" },
    ],
    expectedResult: "Editor blocks duplicate and built-in-colliding keys",
    elementIds: ["EL-ENV-006"],
    automation: { status: "missing" },
    tags: ["environment", "edge", "validation"],
  },
  {
    id: "TC-ENV-012",
    feature: "ENV",
    featureDoc: "environments.md",
    title: "Built-ins $email $firstName $lastName regenerate per send",
    type: "edge",
    priority: "P2",
    scope: "rest",
    preconditions: ["Body or URL uses {{$email}}"],
    steps: [
      {
        order: 1,
        action: "type",
        elementId: "EL-RB-001",
        input: "https://mock.test/?e={{$email}}",
        expected: "Token",
      },
      { order: 2, action: "click", elementId: "EL-RB-011", expected: "First email on wire" },
      { order: 3, action: "click", elementId: "EL-RB-011", expected: "Second email different" },
    ],
    expectedResult: "All $ built-ins are per-send, not cached",
    elementIds: ["EL-RB-001", "EL-RB-011"],
    automation: { status: "missing" },
    tags: ["environment", "builtins", "edge"],
  },
  {
    id: "TC-ENV-013",
    feature: "ENV",
    featureDoc: "environments.md",
    title: "Disabled environment variable is excluded from interpolation",
    type: "edge",
    priority: "P1",
    scope: "rest",
    preconditions: ["Active env with baseUrl disabled via checkbox"],
    steps: [
      {
        order: 1,
        action: "uncheck",
        elementId: "EL-RB-041",
        expected: "Var disabled in env editor",
      },
      {
        order: 2,
        action: "type",
        elementId: "EL-RB-001",
        input: "{{baseUrl}}/x",
        expected: "Token",
      },
      { order: 3, action: "click", elementId: "EL-RB-011", expected: "Send blocked as unresolved" },
    ],
    expectedResult: "Disabled vars do not resolve",
    elementIds: ["EL-ENV-006", "EL-RB-012"],
    automation: { status: "missing" },
    tags: ["environment", "disable", "edge"],
  },
  {
    id: "TC-HD-008",
    feature: "HD",
    featureDoc: "history-drafts.md",
    title: "History groups rows into Today / Yesterday buckets",
    type: "ui",
    priority: "P2",
    scope: "rest",
    preconditions: ["At least one send today"],
    steps: [
      {
        order: 1,
        action: "click",
        elementId: "EL-SID-003",
        expected: "TODAY (or similar) heading visible",
      },
    ],
    expectedResult: "History is time-bucketed, not a flat dump",
    elementIds: ["EL-SID-003"],
    automation: { status: "partial", spec: "e2e/history-drafts.spec.ts" },
    tags: ["history", "ui"],
  },
  {
    id: "TC-HD-009",
    feature: "HD",
    featureDoc: "history-drafts.md",
    title: "Draft folder gear applies inherited headers like collections",
    type: "functional",
    priority: "P1",
    scope: "rest",
    preconditions: ["Draft host folder after a send"],
    steps: [
      { order: 1, action: "click", elementId: "EL-SID-004", expected: "Draft tree" },
      { order: 2, action: "hover", elementId: "EL-SID-014", expected: "Gear on host/path folder" },
      { order: 3, action: "click", elementId: "EL-COL-011", expected: "Folder config modal" },
      { order: 4, action: "type", elementId: "EL-COL-006", input: "X-Draft: 1", expected: "Saved" },
      {
        order: 5,
        action: "click",
        elementId: "EL-SID-014",
        input: "leaf request",
        expected: "Opened tab includes inherited header",
      },
    ],
    expectedResult: "Draft folder config uses the same merge rules as collections",
    elementIds: ["EL-SID-004", "EL-COL-011", "EL-RB-016"],
    automation: { status: "missing" },
    tags: ["drafts", "inheritance"],
  },
  {
    id: "TC-COL-022",
    feature: "COL",
    featureDoc: "collections.md",
    title: "Folders start collapsed; expand is user-driven",
    type: "ux",
    priority: "P2",
    scope: "rest",
    preconditions: ["New collection with a nested folder"],
    steps: [
      {
        order: 1,
        action: "verify",
        elementId: "EL-SID-010",
        expected: "Nested request not visible until expand",
      },
      { order: 2, action: "click", input: "expand chevron", expected: "Children shown" },
    ],
    expectedResult: "No auto-expand-by-size",
    elementIds: ["EL-SID-010"],
    automation: { status: "missing" },
    tags: ["collections", "ux"],
  },
  {
    id: "TC-COL-023",
    feature: "COL",
    featureDoc: "collections.md",
    title: "Add current request via row button vs ⌘⇧S save modal both land in the tree",
    type: "crud",
    priority: "P0",
    scope: "rest",
    preconditions: ["Collection + folder; tab with URL"],
    steps: [
      {
        order: 1,
        action: "hover",
        elementId: "EL-SID-010",
        expected: "Add current request visible",
      },
      { order: 2, action: "click", elementId: "EL-COL-009", expected: "Save Request name modal" },
      { order: 3, action: "click", elementId: "EL-COL-013", expected: "Request in tree" },
      {
        order: 4,
        action: "keyboard",
        input: "Meta+Shift+S",
        expected: "Save As modal still available for another copy",
      },
    ],
    expectedResult: "Hover action and Save As are both valid create paths",
    elementIds: ["EL-COL-009", "EL-COL-013", "EL-COL-003"],
    automation: { status: "partial", spec: "e2e/collections.spec.ts" },
    tags: ["collections", "button-pair", "save"],
  },
  {
    id: "TC-COL-024",
    feature: "COL",
    featureDoc: "collections.md",
    title: "Name modal Space in the input does not close the backdrop",
    type: "edge",
    priority: "P1",
    scope: "rest",
    preconditions: ["Create Collection modal open"],
    steps: [
      {
        order: 1,
        action: "type",
        elementId: "EL-COL-002",
        input: "My API",
        expected: "Includes spaces if typed",
      },
      { order: 2, action: "keyboard", input: "Space", expected: "Modal stays open" },
    ],
    expectedResult: "Space is a character, not a dismiss",
    elementIds: ["EL-COL-002"],
    automation: { status: "missing" },
    tags: ["collections", "modal", "edge"],
  },
  {
    id: "TC-SUI-005",
    feature: "SUI",
    featureDoc: "shared-ui.md",
    title: "Esc overlay stack: palette → shortcuts → env → import → save → settings",
    type: "edge",
    priority: "P1",
    scope: "rest",
    preconditions: ["REST workspace"],
    steps: [
      { order: 1, action: "click", elementId: "EL-APP-007", expected: "Settings" },
      {
        order: 2,
        action: "keyboard",
        input: "Meta+Shift+E",
        expected: "Env on top if allowed, or settings remains",
      },
      { order: 3, action: "keyboard", input: "Escape", expected: "Topmost overlay only closes" },
    ],
    expectedResult: "Escape pops one overlay, never the window",
    elementIds: ["EL-APP-007", "EL-ENV-003"],
    automation: { status: "missing" },
    tags: ["modal", "escape", "edge"],
  },
  {
    id: "TC-IE-008",
    feature: "IE",
    featureDoc: "import-export.md",
    title: "Sidebar Import button vs URL-bar curl paste are different entry points",
    type: "functional",
    priority: "P1",
    scope: "rest",
    preconditions: ["Empty tab"],
    steps: [
      {
        order: 1,
        action: "fill",
        elementId: "EL-RB-001",
        input: "curl https://api.example.com",
        expected: "Current tab populated",
      },
      {
        order: 2,
        action: "click",
        elementId: "EL-SID-002",
        expected: "Modal import opens a new tab instead",
      },
    ],
    expectedResult: "URL-bar paste mutates current tab; modal import creates a new tab",
    elementIds: ["EL-RB-001", "EL-SID-002"],
    automation: { status: "partial", spec: "e2e/import-curl.spec.ts" },
    tags: ["import", "curl", "edge"],
  },
  {
    id: "TC-SET-011",
    feature: "SET",
    featureDoc: "settings.md",
    title: "Retention select does not prune drafts or collections",
    type: "edge",
    priority: "P1",
    scope: "rest",
    preconditions: ["History, drafts, and a collection exist"],
    steps: [
      { order: 1, action: "click", elementId: "EL-SET-021", expected: "Data tab" },
      {
        order: 2,
        action: "select",
        elementId: "EL-SET-009",
        input: "30 days",
        expected: "Setting stored",
      },
      {
        order: 3,
        action: "verify",
        elementId: "EL-SET-022",
        expected: "Collections count unchanged",
      },
    ],
    expectedResult: "Only history is time-pruned on next app start",
    elementIds: ["EL-SET-009", "EL-SET-022"],
    automation: { status: "missing" },
    tags: ["settings", "retention", "edge"],
  },
  {
    id: "TC-COL-025",
    feature: "COL",
    featureDoc: "collections.md",
    title: "Dropping a request onto another request is a no-op",
    type: "edge",
    priority: "P1",
    scope: "rest",
    preconditions: ["Two sibling requests in a collection"],
    steps: [
      {
        order: 1,
        action: "drag",
        elementId: "EL-SID-010",
        input: "request A onto request B (not a folder)",
        expected: "No drop highlight on the request row",
      },
      { order: 2, action: "drop", expected: "Both requests stay in the same parent" },
    ],
    expectedResult: "Only folders and collection roots are droppable",
    elementIds: ["EL-SID-010", "EL-COL-007"],
    automation: { status: "missing" },
    tags: ["dnd", "collections", "edge"],
  },
  {
    id: "TC-COL-026",
    feature: "COL",
    featureDoc: "collections.md",
    title: "Dropping a request onto its current parent folder is a no-op",
    type: "edge",
    priority: "P2",
    scope: "rest",
    preconditions: ["Request already inside Folder A"],
    steps: [
      {
        order: 1,
        action: "drag",
        elementId: "EL-SID-010",
        input: "onto Folder A again",
        expected: "Drop highlight may appear",
      },
      { order: 2, action: "drop", expected: "Tree unchanged; no alert" },
    ],
    expectedResult: "Same-parent move short-circuits without rewriting the collection",
    elementIds: ["EL-SID-010"],
    automation: { status: "missing" },
    tags: ["dnd", "collections", "edge"],
  },
  {
    id: "TC-COL-027",
    feature: "COL",
    featureDoc: "collections.md",
    title: "Header search filters the Collections tree by name and URL",
    type: "functional",
    priority: "P1",
    scope: "rest",
    preconditions: ["Collections tab; two requests with distinct names/URLs"],
    steps: [
      { order: 1, action: "click", elementId: "EL-SID-005", expected: "Collections tab" },
      { order: 2, action: "click", elementId: "EL-APP-001", expected: "Search focused" },
      {
        order: 3,
        action: "type",
        elementId: "EL-APP-001",
        input: "unique-name-xyz",
        expected: "Only matching request (and ancestors) visible",
      },
      {
        order: 4,
        action: "type",
        elementId: "EL-APP-001",
        input: "zzzz-no-hit",
        expected: "EL-COL-014 No matches",
      },
      { order: 5, action: "clear", elementId: "EL-APP-001", expected: "Full tree restored" },
    ],
    expectedResult:
      "Collection filter keeps ancestor folders of matches; empty query restores the tree",
    elementIds: ["EL-APP-001", "EL-SID-005", "EL-COL-014"],
    automation: { status: "partial", spec: "e2e/sidebar-search.spec.ts" },
    tags: ["collections", "search", "edge"],
  },
  {
    id: "TC-COL-028",
    feature: "COL",
    featureDoc: "collections.md",
    title: "Drag while a search filter is active still persists the real tree",
    type: "edge",
    priority: "P2",
    scope: "rest",
    preconditions: ["Two folders; search showing only one request"],
    steps: [
      {
        order: 1,
        action: "type",
        elementId: "EL-APP-001",
        input: "partial match",
        expected: "Filtered tree",
      },
      {
        order: 2,
        action: "drag",
        elementId: "EL-SID-010",
        input: "visible request onto a visible folder",
        expected: "Move succeeds or is rejected cleanly",
      },
      {
        order: 3,
        action: "clear",
        elementId: "EL-APP-001",
        expected: "Unfiltered tree matches the move result",
      },
    ],
    expectedResult: "Filter is display-only; moveNode writes the unfiltered collection",
    elementIds: ["EL-APP-001", "EL-SID-010"],
    automation: { status: "missing" },
    tags: ["dnd", "collections", "search", "edge"],
  },
  {
    id: "TC-TAB-020",
    feature: "TAB",
    featureDoc: "tabs.md",
    title: "Context menu Duplicate Request clones URL, method, headers, and body",
    type: "crud",
    priority: "P0",
    scope: "rest",
    preconditions: ["One tab with URL, POST, a header, and a JSON body"],
    steps: [
      {
        order: 1,
        action: "click",
        elementId: "EL-TAB-002",
        input: "right-click",
        expected: "Context menu",
      },
      {
        order: 2,
        action: "click",
        elementId: "EL-TAB-009",
        expected: "New tab; original still open",
      },
      { order: 3, action: "verify", elementId: "EL-RB-001", expected: "Cloned URL" },
      { order: 4, action: "verify", elementId: "EL-RB-002", expected: "Cloned method" },
    ],
    expectedResult: "Duplicate is a full request clone, not an empty tab",
    elementIds: ["EL-TAB-009", "EL-RB-001", "EL-RB-002"],
    automation: { status: "partial", spec: "e2e/tabs.spec.ts" },
    tags: ["tabs", "duplicate", "context-menu"],
  },
  {
    id: "TC-TAB-021",
    feature: "TAB",
    featureDoc: "tabs.md",
    title: "Close Tab context menu matches the × button and ⌘W",
    type: "keyboard",
    priority: "P0",
    scope: "rest",
    preconditions: ["Three tabs"],
    steps: [
      {
        order: 1,
        action: "click",
        elementId: "EL-TAB-002",
        input: "right-click",
        expected: "Menu",
      },
      { order: 2, action: "click", elementId: "EL-TAB-014", expected: "That tab closed via menu" },
      { order: 3, action: "click", elementId: "EL-TAB-004", expected: "Another tab closed via ×" },
      { order: 4, action: "keyboard", input: "Meta+W", expected: "Active tab closed via shortcut" },
    ],
    expectedResult: "Three close entry points share one store action",
    elementIds: ["EL-TAB-014", "EL-TAB-004"],
    automation: { status: "partial", spec: "e2e/tabs.spec.ts" },
    tags: ["tabs", "button-pair", "keyboard", "context-menu"],
  },
  {
    id: "TC-TAB-022",
    feature: "TAB",
    featureDoc: "tabs.md",
    title: "Overflow chevrons scroll the tab strip without changing the active tab",
    type: "ux",
    priority: "P1",
    scope: "rest",
    preconditions: ["Enough tabs that the strip overflows"],
    steps: [
      { order: 1, action: "verify", elementId: "EL-TAB-016", expected: "Scroll right visible" },
      {
        order: 2,
        action: "click",
        elementId: "EL-TAB-016",
        expected: "Later tabs come into view; active tab unchanged",
      },
      {
        order: 3,
        action: "click",
        elementId: "EL-TAB-015",
        expected: "Earlier tabs come into view",
      },
    ],
    expectedResult: "Scroll buttons are overflow chrome, not tab activation",
    elementIds: ["EL-TAB-015", "EL-TAB-016"],
    automation: { status: "missing" },
    tags: ["tabs", "overflow", "ux"],
  },
  {
    id: "TC-TAB-023",
    feature: "TAB",
    featureDoc: "tabs.md",
    title: "Dragging an overflowing tab still reorders after scrolling into view",
    type: "ux",
    priority: "P1",
    scope: "rest",
    preconditions: ["Many tabs; last tab off-screen"],
    steps: [
      { order: 1, action: "click", elementId: "EL-TAB-016", expected: "Last tab visible" },
      {
        order: 2,
        action: "drag",
        elementId: "EL-TAB-002",
        input: "last tab toward the first visible tab",
        expected: "Order updates",
      },
    ],
    expectedResult: "DnD works on tabs that were revealed by overflow scroll",
    elementIds: ["EL-TAB-016", "EL-TAB-002"],
    automation: { status: "missing" },
    tags: ["dnd", "tabs", "overflow"],
  },
  {
    id: "TC-KB-022",
    feature: "KB",
    featureDoc: "keyboard-shortcuts.md",
    title: "REST header button and ⌘⇧R are no-ops when already on REST",
    type: "keyboard",
    priority: "P1",
    scope: "rest",
    preconditions: ["REST workspace with open tabs"],
    steps: [
      {
        order: 1,
        action: "click",
        elementId: "EL-APP-003",
        expected: "Stay on REST; tabs and URL bar still visible",
      },
      {
        order: 2,
        action: "keyboard",
        input: "Meta+Shift+R",
        expected: "Still REST; no coming-soon flash",
      },
    ],
    expectedResult:
      "Do not open MCP/GraphQL; REST chrome stays mounted. MCP/GraphQL workbenches are out of this REST QA pass",
    elementIds: ["EL-APP-003", "EL-TAB-001", "EL-RB-001"],
    automation: { status: "missing" },
    tags: ["keyboard", "button-pair", "rest"],
  },
  {
    id: "TC-KB-023",
    feature: "KB",
    featureDoc: "keyboard-shortcuts.md",
    title: "Shortcuts overlay is keyboard-only (⌘⇧/) — Close button matches Esc",
    type: "keyboard",
    priority: "P1",
    scope: "rest",
    preconditions: ["REST workspace"],
    steps: [
      {
        order: 1,
        action: "keyboard",
        input: "Meta+Shift+/",
        expected: "Shortcuts modal; no header button exists",
      },
      { order: 2, action: "click", input: "modal Close", expected: "Closed via button" },
      { order: 3, action: "keyboard", input: "Meta+Shift+/", expected: "Reopened" },
      { order: 4, action: "keyboard", input: "Escape", expected: "Closed via Esc — same as Close" },
    ],
    expectedResult: "Help is chord-only to open; Close and Esc are equivalent dismissals",
    elementIds: ["EL-SET-012"],
    automation: { status: "partial", spec: "e2e/shortcuts.spec.ts" },
    tags: ["keyboard", "button-pair", "shortcuts-modal"],
  },
  {
    id: "TC-APP-011",
    feature: "APP",
    featureDoc: "app-shell.md",
    title: "App launches on the REST workbench (sidebar, tabs, URL bar)",
    type: "functional",
    priority: "P0",
    scope: "rest",
    preconditions: ["Fresh load / empty persistence"],
    steps: [
      { order: 1, action: "navigate", expected: "REST layout" },
      { order: 2, action: "verify", elementId: "EL-SID-001", expected: "New Request visible" },
      { order: 3, action: "verify", elementId: "EL-TAB-001", expected: "Tab strip visible" },
      { order: 4, action: "verify", elementId: "EL-RB-001", expected: "URL input visible" },
    ],
    expectedResult: "Default product surface is REST. Do not require MCP or GraphQL for this pass",
    elementIds: ["EL-SID-001", "EL-TAB-001", "EL-RB-001"],
    automation: { status: "covered", spec: "e2e/smoke.spec.ts" },
    tags: ["smoke", "rest"],
  },
  {
    id: "TC-APP-012",
    feature: "APP",
    featureDoc: "app-shell.md",
    title: "Sidebar resize drag is independent of tab and collection DnD",
    type: "ux",
    priority: "P1",
    scope: "rest",
    preconditions: ["REST workspace; sidebar expanded; two tabs"],
    steps: [
      {
        order: 1,
        action: "drag",
        elementId: "EL-SID-008",
        expected: "Sidebar width changes; tab order unchanged",
      },
      { order: 2, action: "verify", elementId: "EL-TAB-001", expected: "Tabs not reordered" },
    ],
    expectedResult: "Three drag systems (sidebar, tabs, collections) do not steal each other",
    elementIds: ["EL-SID-008", "EL-TAB-001"],
    automation: { status: "missing" },
    tags: ["dnd", "layout", "sidebar"],
  },
];

export const restDndShortcutEdgeCases: TestCase[] = [
  ...restShortcutButtonPairCases,
  ...restDragDropCases,
  ...restRemainingEdgeCases,
];
