import type { TestCase } from "../types.js";

export const tabTestCases: TestCase[] = [
  {
    id: "TC-TAB-001",
    feature: "TAB",
    featureDoc: "tabs.md",
    title: "Tab auto-names from URL path segment",
    type: "functional",
    priority: "P0",
    preconditions: ["Single empty tab"],
    steps: [
      {
        order: 1,
        action: "type",
        elementId: "EL-RB-001",
        input: "https://api.example.com/users/42",
        expected: "URL accepted",
      },
      {
        order: 2,
        action: "verify",
        elementId: "EL-TAB-002",
        expected: "Tab label shows GET /users/42 or /users/42",
      },
    ],
    expectedResult: "Tab name tracks URL path until manually locked",
    elementIds: ["EL-RB-001", "EL-TAB-002"],
    automation: {
      status: "covered",
      spec: "e2e/tabs.spec.ts",
      testName: "auto name follows the URL path",
    },
    tags: ["tabs", "naming"],
  },
  {
    id: "TC-TAB-002",
    feature: "TAB",
    featureDoc: "tabs.md",
    title: "Open and close tabs via UI and ⌘W",
    type: "crud",
    priority: "P0",
    preconditions: ["REST workspace"],
    steps: [
      { order: 1, action: "click", elementId: "EL-TAB-003", expected: "Second tab opens" },
      { order: 2, action: "click", elementId: "EL-TAB-004", expected: "Active tab closes" },
      { order: 3, action: "click", elementId: "EL-TAB-003", expected: "New tab again" },
      { order: 4, action: "keyboard", input: "Meta+W", expected: "Tab closes via shortcut" },
    ],
    expectedResult: "Tab CRUD works from + button, close button, and ⌘W",
    elementIds: ["EL-TAB-003", "EL-TAB-004"],
    automation: { status: "covered", spec: "e2e/tabs.spec.ts", testName: "opens and closes tabs" },
    tags: ["tabs", "keyboard"],
  },
  {
    id: "TC-TAB-003",
    feature: "TAB",
    featureDoc: "tabs.md",
    title: "Manual rename locks tab name across URL changes",
    type: "ux",
    priority: "P1",
    preconditions: ["Tab with URL set"],
    steps: [
      { order: 1, action: "dblclick", elementId: "EL-TAB-002", expected: "Rename input appears" },
      {
        order: 2,
        action: "type",
        elementId: "EL-TAB-007",
        input: "My API Call",
        expected: "Name committed on Enter",
      },
      {
        order: 3,
        action: "type",
        elementId: "EL-RB-001",
        input: "https://api.example.com/other",
        expected: "URL updates",
      },
      {
        order: 4,
        action: "verify",
        elementId: "EL-TAB-002",
        expected: "Tab still titled My API Call",
      },
    ],
    expectedResult: "Locked name persists until rename cleared",
    elementIds: ["EL-TAB-002", "EL-TAB-007", "EL-RB-001"],
    automation: {
      status: "covered",
      spec: "e2e/tabs.spec.ts",
      testName: "a manual rename sticks across a path change",
    },
    tags: ["tabs", "rename"],
  },
  {
    id: "TC-TAB-004",
    feature: "TAB",
    featureDoc: "tabs.md",
    title: "Tab reorder via drag-and-drop persists after reload",
    type: "ux",
    priority: "P1",
    preconditions: ["Three or more tabs with distinct names"],
    steps: [
      {
        order: 1,
        action: "drag",
        elementId: "EL-TAB-002",
        input: "to third position",
        expected: "Tab order changes visually",
      },
      { order: 2, action: "reload", expected: "App reloads" },
      {
        order: 3,
        action: "verify",
        elementId: "EL-TAB-001",
        expected: "Tab order matches pre-reload order",
      },
    ],
    expectedResult: "Tab order persisted in localStorage/SQLite",
    elementIds: ["EL-TAB-001", "EL-TAB-002"],
    automation: {
      status: "covered",
      spec: "e2e/tabs.spec.ts",
      testName: "reorders tabs by drag and drop",
    },
    tags: ["tabs", "persistence", "dnd"],
  },
  {
    id: "TC-TAB-005",
    feature: "TAB",
    featureDoc: "tabs.md",
    title: "Overflowing tab strip scrolls with navigation buttons",
    type: "ui",
    priority: "P2",
    preconditions: ["Many tabs open (> viewport width)"],
    steps: [
      {
        order: 1,
        action: "click",
        elementId: "EL-TAB-003",
        input: "repeat 8x",
        expected: "Tabs overflow strip",
      },
      {
        order: 2,
        action: "click",
        elementId: "EL-TAB-006",
        expected: "Strip scrolls right; hidden tabs reachable",
      },
      { order: 3, action: "click", elementId: "EL-TAB-005", expected: "Strip scrolls left" },
    ],
    expectedResult: "Tab overflow handled without clipping close buttons",
    elementIds: ["EL-TAB-005", "EL-TAB-006", "EL-TAB-003"],
    automation: {
      status: "covered",
      spec: "e2e/tabs.spec.ts",
      testName: "scrolls overflowing tabs",
    },
    tags: ["tabs", "overflow"],
  },
  {
    id: "TC-TAB-006",
    feature: "TAB",
    featureDoc: "tabs.md",
    title: "Tab context menu Close Others and Close All",
    type: "crud",
    priority: "P1",
    preconditions: ["Three tabs open"],
    steps: [
      {
        order: 1,
        action: "click",
        elementId: "EL-TAB-002",
        input: "right-click",
        expected: "Context menu opens",
      },
      {
        order: 2,
        action: "click",
        elementId: "EL-TAB-008",
        input: "Close Others",
        expected: "Only active tab remains",
      },
      { order: 3, action: "click", elementId: "EL-TAB-003", expected: "New second tab" },
      {
        order: 4,
        action: "click",
        elementId: "EL-TAB-002",
        input: "right-click Close All",
        expected: "One empty tab remains",
      },
    ],
    expectedResult: "Bulk close operations behave predictably",
    elementIds: ["EL-TAB-002", "EL-TAB-008", "EL-TAB-003"],
    automation: {
      status: "partial",
      spec: "e2e/tabs.spec.ts",
      testName: "Escape closes the tab context menu",
    },
    tags: ["tabs", "context-menu"],
  },
  {
    id: "TC-TAB-007",
    feature: "TAB",
    featureDoc: "tabs.md",
    title: "⌘1–9 activates tab at position N",
    type: "keyboard",
    priority: "P1",
    preconditions: ["At least 3 tabs"],
    steps: [
      { order: 1, action: "keyboard", input: "Meta+3", expected: "Third tab becomes active" },
      {
        order: 2,
        action: "verify",
        elementId: "EL-TAB-002",
        expected: "aria-selected=true on third tab",
      },
    ],
    expectedResult: "Digit shortcuts jump to correct tab",
    elementIds: ["EL-TAB-002"],
    automation: {
      status: "covered",
      spec: "e2e/shortcuts.spec.ts",
      testName: "⌘⇧1-9 switches to the tab",
    },
    tags: ["tabs", "keyboard"],
  },
];

export const requestBuilderTestCases: TestCase[] = [
  {
    id: "TC-RB-001",
    feature: "RB",
    featureDoc: "request-builder.md",
    title: "URL query string syncs to Params editor on keystroke",
    type: "functional",
    priority: "P0",
    preconditions: ["Empty tab, Params tab active"],
    steps: [
      {
        order: 1,
        action: "type",
        elementId: "EL-RB-001",
        input: "https://api.example.com?q=hello&page=1",
        expected: "URL shows query",
      },
      { order: 2, action: "click", elementId: "EL-RB-014", expected: "Params tab active" },
      { order: 3, action: "verify", elementId: "EL-RB-018", expected: "Key q, value hello" },
      { order: 4, action: "verify", elementId: "EL-RB-019", expected: "Second row page=1" },
    ],
    expectedResult: "URL → Params live sync",
    elementIds: ["EL-RB-001", "EL-RB-014", "EL-RB-018", "EL-RB-019"],
    automation: {
      status: "covered",
      spec: "e2e/url-params.spec.ts",
      testName: "a typed query populates the Params editor",
    },
    tags: ["params", "url-sync"],
  },
  {
    id: "TC-RB-002",
    feature: "RB",
    featureDoc: "request-builder.md",
    title: "Editing Params rewrites URL query string",
    type: "functional",
    priority: "P0",
    preconditions: ["Tab with URL containing query params"],
    steps: [
      { order: 1, action: "click", elementId: "EL-RB-014", expected: "Params visible" },
      {
        order: 2,
        action: "fill",
        elementId: "EL-RB-019",
        input: "updated",
        expected: "Param value changed",
      },
      {
        order: 3,
        action: "verify",
        elementId: "EL-RB-001",
        expected: "URL query reflects new value",
      },
    ],
    expectedResult: "Params → URL live sync",
    elementIds: ["EL-RB-014", "EL-RB-019", "EL-RB-001"],
    automation: {
      status: "covered",
      spec: "e2e/url-params.spec.ts",
      testName: "editing a param rewrites the URL query",
    },
    tags: ["params", "url-sync"],
  },
  {
    id: "TC-RB-003",
    feature: "RB",
    featureDoc: "request-builder.md",
    title: "Clear URL shows empty state with Try an example only",
    type: "ui",
    priority: "P1",
    preconditions: ["Tab with URL"],
    steps: [
      { order: 1, action: "clear", elementId: "EL-RB-001", expected: "URL empty" },
      {
        order: 2,
        action: "verify",
        elementId: "EL-RB-026",
        expected: "Try an example CTA visible",
      },
      {
        order: 3,
        action: "verify",
        elementId: "EL-RB-014",
        expected: "Editor tabs hidden or empty state covers editor",
      },
    ],
    expectedResult: "Empty URL triggers EmptyRequestState",
    elementIds: ["EL-RB-001", "EL-RB-026"],
    automation: { status: "partial" },
    tags: ["empty-state"],
  },
  {
    id: "TC-RB-004",
    feature: "RB",
    featureDoc: "request-builder.md",
    title: "Long URL (≥2KB) supports End key and horizontal scroll",
    type: "edge",
    priority: "P1",
    preconditions: ["Empty tab"],
    steps: [
      {
        order: 1,
        action: "fill",
        elementId: "EL-RB-001",
        input: "~3KB URL with long query",
        expected: "URL accepted without layout break",
      },
      { order: 2, action: "keyboard", input: "End", expected: "Caret at end of URL" },
      {
        order: 3,
        action: "scroll",
        elementId: "EL-RB-001",
        input: "horizontal",
        expected: "Tint overlay stays aligned with text",
      },
    ],
    expectedResult: "Long URL remains editable; no page overflow",
    elementIds: ["EL-RB-001"],
    automation: { status: "covered", spec: "e2e/long-values.spec.ts" },
    tags: ["edge", "long-url"],
  },
  {
    id: "TC-RB-005",
    feature: "RB",
    featureDoc: "request-builder.md",
    title: "25+ header rows scroll vertically inside editor",
    type: "edge",
    priority: "P1",
    preconditions: ["Headers tab active"],
    steps: [
      { order: 1, action: "click", elementId: "EL-RB-016", expected: "Headers tab open" },
      {
        order: 2,
        action: "click",
        elementId: "EL-RB-023",
        input: "repeat 25x",
        expected: "Many rows added",
      },
      {
        order: 3,
        action: "scroll",
        elementId: "EL-RB-021",
        input: "to last row",
        expected: "Last row reachable via scroll",
      },
    ],
    expectedResult: "Header list scrolls inside panel, not page",
    elementIds: ["EL-RB-016", "EL-RB-023", "EL-RB-021"],
    automation: {
      status: "covered",
      spec: "e2e/long-values.spec.ts",
      testName: "25 header rows scroll vertically",
    },
    tags: ["edge", "headers"],
  },
  {
    id: "TC-RB-006",
    feature: "RB",
    featureDoc: "request-builder.md",
    title: "HTTP method dropdown lists all methods including QUERY",
    type: "functional",
    priority: "P0",
    preconditions: ["Tab with URL"],
    steps: [
      { order: 1, action: "click", elementId: "EL-RB-002", expected: "Method list opens" },
      { order: 2, action: "verify", elementId: "EL-RB-003", expected: "GET visible" },
      { order: 3, action: "verify", elementId: "EL-RB-010", expected: "QUERY visible" },
      {
        order: 4,
        action: "click",
        elementId: "EL-RB-004",
        expected: "POST selected; tab label updates",
      },
    ],
    expectedResult: "All HTTP methods selectable",
    elementIds: ["EL-RB-002", "EL-RB-003", "EL-RB-004", "EL-RB-010"],
    automation: { status: "covered", spec: "e2e/method-and-actions.spec.ts" },
    tags: ["method"],
  },
  {
    id: "TC-RB-007",
    feature: "RB",
    featureDoc: "request-builder.md",
    title: "Bearer auth injects Authorization header on send",
    type: "functional",
    priority: "P0",
    preconditions: ["Mocked API endpoint"],
    steps: [
      { order: 1, action: "click", elementId: "EL-RB-015", expected: "Auth tab open" },
      {
        order: 2,
        action: "select",
        elementId: "EL-RB-027",
        input: "Bearer",
        expected: "Token field visible",
      },
      {
        order: 3,
        action: "type",
        elementId: "EL-RB-027",
        input: "test-token-123",
        expected: "Token stored",
      },
      {
        order: 4,
        action: "click",
        elementId: "EL-RB-011",
        expected: "Request sent with Authorization: Bearer header",
      },
    ],
    expectedResult: "Auth credentials applied at send time",
    elementIds: ["EL-RB-015", "EL-RB-027", "EL-RB-011"],
    automation: {
      status: "covered",
      spec: "e2e/send.spec.ts",
      testName: "Bearer auth sets the Authorization header",
    },
    tags: ["auth", "send"],
  },
  {
    id: "TC-RB-008",
    feature: "RB",
    featureDoc: "request-builder.md",
    title: "Paste curl into URL bar populates full request",
    type: "functional",
    priority: "P1",
    preconditions: ["Empty tab"],
    steps: [
      {
        order: 1,
        action: "fill",
        elementId: "EL-RB-001",
        input: "curl -X POST https://api.example.com -H 'Authorization: Bearer x'",
        expected: "Request parsed",
      },
      { order: 2, action: "verify", elementId: "EL-RB-002", expected: "Method POST" },
      {
        order: 3,
        action: "click",
        elementId: "EL-RB-016",
        expected: "Authorization header present",
      },
    ],
    expectedResult: "cURL paste applies method, URL, headers, body",
    elementIds: ["EL-RB-001", "EL-RB-002", "EL-RB-016"],
    automation: {
      status: "covered",
      spec: "e2e/import-curl.spec.ts",
      testName: "typing a curl command into the URL bar parses it",
    },
    tags: ["import", "curl"],
  },
  {
    id: "TC-RB-009",
    feature: "RB",
    featureDoc: "request-builder.md",
    title: "Disabled param excluded from URL and send payload",
    type: "functional",
    priority: "P1",
    preconditions: ["Tab with param q=test"],
    steps: [
      { order: 1, action: "click", elementId: "EL-RB-014", expected: "Params tab" },
      {
        order: 2,
        action: "uncheck",
        elementId: "EL-RB-018",
        input: "Disable row checkbox",
        expected: "Row disabled",
      },
      { order: 3, action: "verify", elementId: "EL-RB-001", expected: "q removed from URL query" },
    ],
    expectedResult: "Disabled rows ignored in URL sync and send",
    elementIds: ["EL-RB-014", "EL-RB-018", "EL-RB-001"],
    automation: { status: "missing" },
    tags: ["params", "disable"],
  },
  {
    id: "TC-RB-010",
    feature: "RB",
    featureDoc: "request-builder.md",
    title: "Body editor JSON input serializes on send",
    type: "functional",
    priority: "P0",
    preconditions: ["POST tab with URL"],
    steps: [
      { order: 1, action: "click", elementId: "EL-RB-017", expected: "Body tab open" },
      { order: 2, action: "click", elementId: "EL-RB-028", expected: "JSON body type selected" },
      {
        order: 3,
        action: "type",
        elementId: "EL-RB-032",
        input: '{"title":"test"}',
        expected: "JSON in editor",
      },
      {
        order: 4,
        action: "click",
        elementId: "EL-RB-011",
        expected: "Content-Type: application/json on wire",
      },
    ],
    expectedResult: "JSON body sent with correct content type",
    elementIds: ["EL-RB-017", "EL-RB-028", "EL-RB-032", "EL-RB-011"],
    automation: {
      status: "covered",
      spec: "e2e/body-editor.spec.ts",
      testName: "JSON body accepts input",
    },
    tags: ["body", "json"],
  },
  {
    id: "TC-RB-011",
    feature: "RB",
    featureDoc: "request-builder.md",
    title: "Unresolved {{var}} blocks send with error message",
    type: "functional",
    priority: "P0",
    preconditions: ["No matching env variable"],
    steps: [
      {
        order: 1,
        action: "type",
        elementId: "EL-RB-001",
        input: "https://{{missingHost}}/path",
        expected: "Token chip visible",
      },
      { order: 2, action: "click", elementId: "EL-RB-011", expected: "Send blocked" },
      {
        order: 3,
        action: "verify",
        elementId: "EL-RB-012",
        expected: "Error lists missing variable name",
      },
    ],
    expectedResult: "Strict env resolution prevents bad sends",
    elementIds: ["EL-RB-001", "EL-RB-011", "EL-RB-012"],
    automation: {
      status: "covered",
      spec: "e2e/environments.spec.ts",
      testName: "unresolved {{var}} blocks the send",
    },
    tags: ["environment", "send-error"],
  },
  {
    id: "TC-RB-012",
    feature: "RB",
    featureDoc: "request-builder.md",
    title: "{{var}} autocomplete in URL, params, and body",
    type: "ux",
    priority: "P1",
    preconditions: ["Environment with baseUrl variable active"],
    steps: [
      {
        order: 1,
        action: "type",
        elementId: "EL-RB-001",
        input: "{{",
        expected: "Suggestion dropdown opens",
      },
      { order: 2, action: "click", elementId: "EL-ENV-008", expected: "Variable inserted in URL" },
      { order: 3, action: "click", elementId: "EL-RB-014", expected: "Params tab" },
      {
        order: 4,
        action: "type",
        elementId: "EL-RB-019",
        input: "{{",
        expected: "Autocomplete in param value",
      },
    ],
    expectedResult: "Autocomplete works in all supported fields",
    elementIds: ["EL-RB-001", "EL-ENV-008", "EL-RB-019"],
    automation: {
      status: "covered",
      spec: "e2e/environments.spec.ts",
      testName: "{{ autocomplete works in param values and the body",
    },
    tags: ["environment", "autocomplete"],
  },
];
