import type { TestElement } from "../types.js";

/** Application shell & global layout elements */
export const appShellElements: TestElement[] = [
  {
    id: "EL-APP-001",
    feature: "APP",
    name: "Header search input",
    selector: "[data-header-search]",
    component: "app/layout/Header.tsx",
    role: "textbox",
    notes: "Global search; ⌘F focuses when not in body/response find context",
  },
  {
    id: "EL-APP-002",
    feature: "APP",
    name: "Environment selector trigger",
    selector: '[data-testid="env-selector"]',
    testId: "env-selector",
    component: "features/environments/components/EnvSelector.tsx",
    role: "button",
  },
  {
    id: "EL-APP-003",
    feature: "APP",
    name: "REST workspace button",
    selector: '[data-testid="header-open-rest"]',
    testId: "header-open-rest",
    component: "app/layout/Header.tsx",
  },
  {
    id: "EL-APP-004",
    feature: "APP",
    name: "MCP workspace button",
    selector: '[data-testid="header-open-mcp"]',
    testId: "header-open-mcp",
    component: "app/layout/Header.tsx",
  },
  {
    id: "EL-APP-005",
    feature: "APP",
    name: "GraphQL workspace button",
    selector: '[data-testid="header-open-graphql"]',
    testId: "header-open-graphql",
    component: "app/layout/Header.tsx",
  },
  {
    id: "EL-APP-006",
    feature: "APP",
    name: "Copy as cURL (header)",
    selector: 'header button[title="Copy as cURL"]',
    component: "app/layout/Header.tsx",
    notes: "Uses title attribute, not data-testid",
  },
  {
    id: "EL-APP-007",
    feature: "APP",
    name: "Settings button",
    selector: 'header button[aria-label="Settings"]',
    component: "app/layout/Header.tsx",
    role: "button",
  },
  {
    id: "EL-APP-008",
    feature: "APP",
    name: "Production environment indicator",
    selector: '[data-testid="env-prod-indicator"]',
    testId: "env-prod-indicator",
    component: "app/AppContent.tsx",
  },
  {
    id: "EL-APP-009",
    feature: "APP",
    name: "Workspace layout root",
    selector: "#workspace-layout",
    elementId: "workspace-layout",
    component: "app/AppContent.tsx",
    planned: true,
    notes: "Add data-testid=workspace-layout to align with docs",
  },
  {
    id: "EL-APP-010",
    feature: "APP",
    name: "Response panel resize handle",
    selector: "#response-resize-handle",
    elementId: "response-resize-handle",
    component: "app/AppContent.tsx",
    notes: "Used in smoke.spec.ts via getByTestId mismatch — prefer data-testid",
  },
  {
    id: "EL-APP-011",
    feature: "APP",
    name: "Migration toast",
    selector: '[data-testid="migration-toast"]',
    testId: "migration-toast",
    component: "app/layout/MigrationToast.tsx",
    planned: true,
  },
  {
    id: "EL-APP-012",
    feature: "APP",
    name: "Update toast",
    selector: '[data-testid="update-toast"]',
    testId: "update-toast",
    component: "app/layout/UpdateToast.tsx",
    planned: true,
  },
];

export const workspaceElements: TestElement[] = [
  {
    id: "EL-WS-001",
    feature: "WS",
    name: "MCP coming soon page",
    selector: '[data-testid="mcp-coming-soon"]',
    testId: "mcp-coming-soon",
    component: "features/workspaces/components/ComingSoonWorkspace.tsx",
  },
  {
    id: "EL-WS-002",
    feature: "WS",
    name: "GraphQL coming soon page",
    selector: '[data-testid="graphql-coming-soon"]',
    testId: "graphql-coming-soon",
    component: "features/workspaces/components/ComingSoonWorkspace.tsx",
  },
];

export const sidebarElements: TestElement[] = [
  {
    id: "EL-SID-001",
    feature: "SID",
    name: "New Request button",
    selector: '[data-testid="sidebar-new-request"]',
    testId: "sidebar-new-request",
    component: "app/layout/Sidebar.tsx",
  },
  {
    id: "EL-SID-002",
    feature: "SID",
    name: "Import cURL / Postman button",
    selector: '[data-testid="sidebar-import"]',
    testId: "sidebar-import",
    component: "app/layout/Sidebar.tsx",
  },
  {
    id: "EL-SID-003",
    feature: "SID",
    name: "History sidebar tab",
    selector: '[data-testid="sidebar-tab-history"]',
    testId: "sidebar-tab-history",
    component: "app/layout/Sidebar.tsx",
  },
  {
    id: "EL-SID-004",
    feature: "SID",
    name: "Draft sidebar tab",
    selector: '[data-testid="sidebar-tab-draft"]',
    testId: "sidebar-tab-draft",
    component: "app/layout/Sidebar.tsx",
  },
  {
    id: "EL-SID-005",
    feature: "SID",
    name: "Collections sidebar tab",
    selector: '[data-testid="sidebar-tab-collections"]',
    testId: "sidebar-tab-collections",
    component: "app/layout/Sidebar.tsx",
  },
  {
    id: "EL-SID-006",
    feature: "SID",
    name: "Collapse sidebar",
    selector: '[data-testid="sidebar-collapse"]',
    testId: "sidebar-collapse",
    component: "app/layout/Sidebar.tsx",
  },
  {
    id: "EL-SID-007",
    feature: "SID",
    name: "Expand sidebar",
    selector: '[data-testid="sidebar-expand"]',
    testId: "sidebar-expand",
    component: "app/layout/Sidebar.tsx",
  },
  {
    id: "EL-SID-008",
    feature: "SID",
    name: "Sidebar resize handle",
    selector: '[data-testid="sidebar-resize-handle"]',
    testId: "sidebar-resize-handle",
    planned: true,
    component: "app/layout/Sidebar.tsx",
  },
  {
    id: "EL-SID-009",
    feature: "SID",
    name: "History row (by label)",
    selector: 'aside [role="complementary"] button:has-text("/")',
    component: "features/rest/history/components/HistoryTab.tsx",
    notes: "No stable row testid — match by method + path text",
  },
  {
    id: "EL-SID-010",
    feature: "SID",
    name: "Collection tree row",
    selector: '[role="treeitem"]',
    component: "shared/ui/TreeRow.tsx",
  },
  {
    id: "EL-SID-011",
    feature: "SID",
    name: "Tree row — Rename",
    selector: '[aria-label="Rename"]',
    component: "shared/ui/TreeRow.tsx",
  },
  {
    id: "EL-SID-012",
    feature: "SID",
    name: "Tree row — Delete",
    selector: '[aria-label="Delete"]',
    component: "shared/ui/TreeRow.tsx",
  },
  {
    id: "EL-SID-013",
    feature: "SID",
    name: "Collections empty CTA",
    selector: 'button:has-text("+ Create Collection")',
    component: "features/rest/collections/components/CollectionsTab.tsx",
  },
  {
    id: "EL-SID-014",
    feature: "SID",
    name: "Draft tree row",
    selector: '[data-testid="sidebar-tab-draft"] ~ * [role="treeitem"]',
    component: "features/rest/history/components/DraftTab.tsx",
  },
];
