import type { TestElement } from "../types.js";

export const responseViewerElements: TestElement[] = [
  {
    id: "EL-RV-001",
    feature: "RV",
    name: "Response empty state",
    selector: '[data-testid="response-empty"]',
    testId: "response-empty",
    component: "features/rest/response-viewer/components/EmptyResponse.tsx",
  },
  {
    id: "EL-RV-002",
    feature: "RV",
    name: "Response empty body placeholder",
    selector: '[data-testid="response-empty-body"]',
    testId: "response-empty-body",
    component: "features/rest/response-viewer/components/StatusEmptyBody.tsx",
  },
  {
    id: "EL-RV-003",
    feature: "RV",
    name: "Response status line",
    selector: '[data-testid="response-status"]:visible',
    testId: "response-status",
    component: "features/rest/response-viewer/components/StatusLine.tsx",
  },
  {
    id: "EL-RV-004",
    feature: "RV",
    name: "Response body pane",
    selector: '[data-testid="response-body"]:visible',
    testId: "response-body",
    component: "features/rest/response-viewer/components/BodyView.tsx",
  },
  {
    id: "EL-RV-005",
    feature: "RV",
    name: "Response Pretty view",
    selector: '[data-testid="response-view-pretty"]',
    testId: "response-view-pretty",
    component: "features/rest/response-viewer/components/BodyView.tsx",
  },
  {
    id: "EL-RV-006",
    feature: "RV",
    name: "Response Raw view",
    selector: '[data-testid="response-view-raw"]',
    testId: "response-view-raw",
    component: "features/rest/response-viewer/components/BodyView.tsx",
  },
  {
    id: "EL-RV-007",
    feature: "RV",
    name: "Response HTML preview",
    selector: '[data-testid="response-html-preview"]',
    testId: "response-html-preview",
    component: "features/rest/response-viewer/components/BodyView.tsx",
  },
  {
    id: "EL-RV-008",
    feature: "RV",
    name: "Response word wrap toggle",
    selector: '[data-testid="response-wrap-toggle"]',
    testId: "response-wrap-toggle",
    component: "features/rest/response-viewer/components/BodyView.tsx",
  },
  {
    id: "EL-RV-009",
    feature: "RV",
    name: "History snapshot label",
    selector: '[data-testid="response-snapshot-label"]',
    testId: "response-snapshot-label",
    component: "features/rest/response-viewer/components/ResponsePanel.tsx",
  },
  {
    id: "EL-RV-010",
    feature: "RV",
    name: "Cancel in-flight request",
    selector: '[data-testid="response-cancel"]',
    testId: "response-cancel",
    component: "features/rest/response-viewer/components/StatusLine.tsx",
  },
  {
    id: "EL-RV-011",
    feature: "RV",
    name: "Response find bar",
    selector: '[data-testid="response-find"]',
    testId: "response-find",
    component: "shared/ui/FindBar.tsx",
  },
  {
    id: "EL-RV-012",
    feature: "RV",
    name: "Response Headers tab",
    selector: '[data-testid="response-tab-headers"]',
    testId: "response-tab-headers",
    planned: true,
    component: "features/rest/response-viewer/components/ResponsePanel.tsx",
  },
  {
    id: "EL-RV-013",
    feature: "RV",
    name: "SSE event stream panel",
    selector: '[data-testid="response-sse"]',
    testId: "response-sse",
    component: "features/rest/response-viewer/components/SseEventList.tsx",
  },
  {
    id: "EL-RV-014",
    feature: "RV",
    name: "SSE stop button",
    selector: '[data-testid="response-sse-stop"]',
    testId: "response-sse-stop",
    component: "features/rest/response-viewer/components/SseEventList.tsx",
  },
  {
    id: "EL-RV-015",
    feature: "RV",
    name: "Download response button",
    selector: 'button:has-text("Download response")',
    component: "features/rest/response-viewer/components/ResponsePanel.tsx",
  },
  {
    id: "EL-RV-016",
    feature: "RV",
    name: "Response Body tab",
    selector: 'button:has-text("Body")',
    component: "features/rest/response-viewer/components/ResponsePanel.tsx",
  },
  {
    id: "EL-RV-017",
    feature: "RV",
    name: "Response Copy as cURL",
    selector: '[data-testid="response-copy-curl"]',
    testId: "response-copy-curl",
    planned: true,
    component: "features/rest/response-viewer/components/ResponsePanel.tsx",
    notes: "Currently title/label Copy as cURL in response panel",
  },
  {
    id: "EL-RV-018",
    feature: "RV",
    name: "Response Preview view",
    selector: '[data-testid="response-view-preview"]',
    testId: "response-view-preview",
    component: "features/rest/response-viewer/components/StatusLine.tsx",
  },
  {
    id: "EL-RV-019",
    feature: "RV",
    name: "Response find input",
    selector: '[data-testid="response-find-input"]',
    testId: "response-find-input",
    component: "shared/ui/FindBar.tsx",
  },
  {
    id: "EL-RV-020",
    feature: "RV",
    name: "Response find next",
    selector: '[data-testid="response-find-next"]',
    testId: "response-find-next",
    component: "shared/ui/FindBar.tsx",
  },
  {
    id: "EL-RV-021",
    feature: "RV",
    name: "SSE event row 0",
    selector: '[data-testid="response-sse-event-0"]',
    testId: "response-sse-event-0",
    component: "features/rest/response-viewer/components/SseEventList.tsx",
  },
];

export const collectionElements: TestElement[] = [
  {
    id: "EL-COL-001",
    feature: "COL",
    name: "Create collection button",
    selector: 'button:has-text("Create Collection"), button:has-text("New Collection")',
    component: "features/rest/collections/components/CollectionsTab.tsx",
  },
  {
    id: "EL-COL-002",
    feature: "COL",
    name: "Collection name modal input",
    selector: "#collection-name-modal-input",
    elementId: "collection-name-modal-input",
    component: "features/rest/collections/components/NameModal.tsx",
  },
  {
    id: "EL-COL-003",
    feature: "COL",
    name: "Save to collection modal",
    selector: '[data-testid="save-collection-modal"]',
    testId: "save-collection-modal",
    planned: true,
    component: "features/rest/collections/components/SaveToCollectionModal.tsx",
  },
  {
    id: "EL-COL-004",
    feature: "COL",
    name: "Folder config — Headers tab",
    selector: '[data-testid="folder-config-tab-headers"]',
    testId: "folder-config-tab-headers",
    component: "features/rest/collections/components/FolderConfigModal.tsx",
  },
  {
    id: "EL-COL-005",
    feature: "COL",
    name: "Folder config — Auth tab",
    selector: '[data-testid="folder-config-tab-auth"]',
    testId: "folder-config-tab-auth",
    component: "features/rest/collections/components/FolderConfigModal.tsx",
  },
  {
    id: "EL-COL-006",
    feature: "COL",
    name: "Folder header key (row 0)",
    selector: '[data-testid="folder-header-key-0"]',
    testId: "folder-header-key-0",
    component: "features/rest/collections/components/FolderConfigModal.tsx",
  },
  {
    id: "EL-COL-007",
    feature: "COL",
    name: "DnD drop target highlight",
    selector: '[data-testid="tree-row-drop-active"]',
    testId: "tree-row-drop-active",
    component: "shared/ui/TreeRow.tsx",
  },
  {
    id: "EL-COL-008",
    feature: "COL",
    name: "Confirm modal — confirm button",
    selector: '[data-testid="confirm-modal-confirm"]',
    testId: "confirm-modal-confirm",
    component: "packages/ui/src/components/ConfirmModal.tsx",
  },
  {
    id: "EL-COL-009",
    feature: "COL",
    name: "Add current request to collection/folder",
    selector: '[aria-label="Add current request"]',
    component: "features/rest/collections/components/CollectionsTab.tsx",
  },
  {
    id: "EL-COL-010",
    feature: "COL",
    name: "Add folder to collection",
    selector: '[aria-label="Add folder"]',
    component: "features/rest/collections/components/CollectionsTab.tsx",
  },
  {
    id: "EL-COL-011",
    feature: "COL",
    name: "Folder config gear",
    selector: '[aria-label="Folder headers & auth"]',
    component: "features/rest/collections/components/CollectionsTab.tsx",
    planned: true,
  },
  {
    id: "EL-COL-012",
    feature: "COL",
    name: "Name modal Create button",
    selector: '[role="dialog"] button:has-text("Create")',
    component: "features/rest/collections/components/NameModal.tsx",
  },
  {
    id: "EL-COL-013",
    feature: "COL",
    name: "Save modal Save button",
    selector: '[role="dialog"] button:has-text("Save")',
    component: "features/rest/collections/components/SaveToCollectionModal.tsx",
  },
  {
    id: "EL-COL-014",
    feature: "COL",
    name: "Collections empty / no-matches label",
    selector: "text=No matches, text=No collections yet",
    component: "features/rest/collections/components/CollectionsTab.tsx",
  },
];

export const environmentElements: TestElement[] = [
  {
    id: "EL-ENV-001",
    feature: "ENV",
    name: "No environment option",
    selector: '[data-testid="env-option-none"]',
    testId: "env-option-none",
    component: "features/environments/components/EnvSelector.tsx",
  },
  {
    id: "EL-ENV-002",
    feature: "ENV",
    name: "Environment option (dynamic)",
    selector: '[data-testid^="env-option-"]',
    component: "features/environments/components/EnvSelector.tsx",
    notes: "Pattern: env-option-{name}",
  },
  {
    id: "EL-ENV-003",
    feature: "ENV",
    name: "Manage environments link",
    selector: 'button:has-text("Manage environments")',
    component: "features/environments/components/EnvSelector.tsx",
  },
  {
    id: "EL-ENV-004",
    feature: "ENV",
    name: "Environment manager modal",
    selector: '[data-testid="env-modal"]',
    testId: "env-modal",
    planned: true,
    component: "features/environments/components/EnvModal.tsx",
  },
  {
    id: "EL-ENV-005",
    feature: "ENV",
    name: "Production checkbox",
    selector: '[data-testid="env-prod-checkbox"]',
    testId: "env-prod-checkbox",
    component: "features/environments/components/EnvModal.tsx",
  },
  {
    id: "EL-ENV-006",
    feature: "ENV",
    name: "Env variable key (row 0)",
    selector: '[data-testid="env-key-0"]',
    testId: "env-key-0",
    component: "features/environments/components/VarKeyValueEditor.tsx",
  },
  {
    id: "EL-ENV-007",
    feature: "ENV",
    name: "Env variable value (row 0)",
    selector: '[data-testid="env-value-0"]',
    testId: "env-value-0",
    component: "features/environments/components/VarKeyValueEditor.tsx",
  },
  {
    id: "EL-ENV-008",
    feature: "ENV",
    name: "Variable autocomplete suggestion",
    selector: '[data-testid="var-suggestion"]',
    testId: "var-suggestion",
    component: "features/environments/components/VarSuggestions.tsx",
  },
  {
    id: "EL-ENV-009",
    feature: "ENV",
    name: "Set active environment button",
    selector: 'button:has-text("Set active")',
    component: "features/environments/components/EnvModal.tsx",
  },
  {
    id: "EL-ENV-010",
    feature: "ENV",
    name: "Production confirm dialog",
    selector: '[data-testid="prod-confirm-dialog"]',
    testId: "prod-confirm-dialog",
    planned: true,
    component: "features/environments/components/EnvModal.tsx",
  },
  {
    id: "EL-ENV-011",
    feature: "ENV",
    name: "Duplicate environment",
    selector: 'button:has-text("Duplicate")',
    component: "features/environments/components/EnvModal.tsx",
  },
  {
    id: "EL-ENV-012",
    feature: "ENV",
    name: "Delete environment",
    selector: '[role="dialog"] button:has-text("Delete")',
    component: "features/environments/components/EnvModal.tsx",
  },
  {
    id: "EL-ENV-013",
    feature: "ENV",
    name: "Globals list item",
    selector: 'button:has-text("Globals")',
    component: "features/environments/components/EnvModal.tsx",
  },
  {
    id: "EL-ENV-014",
    feature: "ENV",
    name: "Mark secret lock",
    selector: '[aria-label="Mark secret"]',
    component: "features/environments/components/VarKeyValueEditor.tsx",
  },
  {
    id: "EL-ENV-015",
    feature: "ENV",
    name: "Add environment button",
    selector: '[role="dialog"] button:has-text("Add")',
    component: "features/environments/components/EnvModal.tsx",
  },
  {
    id: "EL-ENV-016",
    feature: "ENV",
    name: "Add variable button",
    selector: 'button:has-text("Add variable")',
    component: "features/environments/components/VarKeyValueEditor.tsx",
  },
];

export const importExportElements: TestElement[] = [
  {
    id: "EL-IE-001",
    feature: "IE",
    name: "Import mode — cURL",
    selector: '[data-testid="import-mode-curl"]',
    testId: "import-mode-curl",
    component: "features/rest/import-export/components/ImportModal.tsx",
  },
  {
    id: "EL-IE-002",
    feature: "IE",
    name: "Import mode — Postman",
    selector: '[data-testid="import-mode-postman"]',
    testId: "import-mode-postman",
    component: "features/rest/import-export/components/ImportModal.tsx",
  },
  {
    id: "EL-IE-003",
    feature: "IE",
    name: "Import cURL textarea",
    selector: '[data-testid="import-curl-textarea"]',
    testId: "import-curl-textarea",
    component: "features/rest/import-export/components/ImportModal.tsx",
  },
  {
    id: "EL-IE-004",
    feature: "IE",
    name: "Import cURL submit",
    selector: '[data-testid="import-curl-submit"]',
    testId: "import-curl-submit",
    component: "features/rest/import-export/components/ImportModal.tsx",
  },
  {
    id: "EL-IE-005",
    feature: "IE",
    name: "Import Postman textarea",
    selector: '[data-testid="import-postman-textarea"]',
    testId: "import-postman-textarea",
    component: "features/rest/import-export/components/ImportModal.tsx",
  },
  {
    id: "EL-IE-006",
    feature: "IE",
    name: "Import Postman file upload",
    selector: '[data-testid="import-postman-upload"]',
    testId: "import-postman-upload",
    component: "features/rest/import-export/components/ImportModal.tsx",
  },
  {
    id: "EL-IE-007",
    feature: "IE",
    name: "Import error message",
    selector: '[data-testid="import-error"]',
    testId: "import-error",
    planned: true,
    component: "features/rest/import-export/components/ImportModal.tsx",
  },
  {
    id: "EL-IE-008",
    feature: "IE",
    name: "Import Postman submit",
    selector: '[data-testid="import-postman-submit"]',
    testId: "import-postman-submit",
    component: "features/rest/import-export/components/ImportModal.tsx",
  },
];

export const commandPaletteElements: TestElement[] = [
  {
    id: "EL-CP-001",
    feature: "CP",
    name: "Command palette overlay",
    selector: '[data-testid="command-palette"]',
    testId: "command-palette",
    component: "features/command-palette/components/CommandPalette.tsx",
  },
  {
    id: "EL-CP-002",
    feature: "CP",
    name: "Command palette search input",
    selector: '[data-testid="command-palette-input"]',
    testId: "command-palette-input",
    component: "features/command-palette/components/CommandPalette.tsx",
  },
  {
    id: "EL-CP-003",
    feature: "CP",
    name: "Command palette result row 0",
    selector: '[data-testid="command-palette-result-0"]',
    testId: "command-palette-result-0",
    component: "features/command-palette/components/CommandPalette.tsx",
  },
];

export const settingsElements: TestElement[] = [
  {
    id: "EL-SET-001",
    feature: "SET",
    name: "Settings drawer",
    selector: '[data-testid="settings-drawer"]',
    testId: "settings-drawer",
    planned: true,
    component: "features/settings/components/SettingsDrawer.tsx",
  },
  {
    id: "EL-SET-002",
    feature: "SET",
    name: "Settings tab — General",
    selector: '[data-testid="settings-tab-general"]',
    testId: "settings-tab-general",
    planned: true,
    component: "features/settings/components/SettingsDrawer.tsx",
  },
  {
    id: "EL-SET-003",
    feature: "SET",
    name: "Settings tab — Requests",
    selector: '[data-testid="settings-tab-requests"]',
    testId: "settings-tab-requests",
    planned: true,
    component: "features/settings/components/SettingsDrawer.tsx",
  },
  {
    id: "EL-SET-004",
    feature: "SET",
    name: "Settings tab — Data",
    selector: '[data-testid="settings-tab-data"]',
    testId: "settings-tab-data",
    planned: true,
    component: "features/settings/components/SettingsDrawer.tsx",
  },
  {
    id: "EL-SET-005",
    feature: "SET",
    name: "Settings tab — About",
    selector: '[data-testid="settings-tab-about"]',
    testId: "settings-tab-about",
    planned: true,
    component: "features/settings/components/SettingsDrawer.tsx",
  },
  {
    id: "EL-SET-006",
    feature: "SET",
    name: "Theme — Dark",
    selector: 'button:has-text("Dark")',
    component: "features/settings/components/SettingsDrawer.tsx",
  },
  {
    id: "EL-SET-007",
    feature: "SET",
    name: "Theme — Light",
    selector: 'button:has-text("Light")',
    component: "features/settings/components/SettingsDrawer.tsx",
  },
  {
    id: "EL-SET-008",
    feature: "SET",
    name: "Word wrap setting",
    selector: '[data-testid="settings-word-wrap"]',
    testId: "settings-word-wrap",
    component: "features/settings/components/SettingsDrawer.tsx",
  },
  {
    id: "EL-SET-009",
    feature: "SET",
    name: "History retention setting",
    selector: '[data-testid="settings-retention"]',
    testId: "settings-retention",
    component: "features/settings/components/SettingsDrawer.tsx",
  },
  {
    id: "EL-SET-010",
    feature: "SET",
    name: "Save snapshots toggle",
    selector: '[data-testid="settings-save-snapshots"]',
    testId: "settings-save-snapshots",
    component: "features/settings/components/SettingsDrawer.tsx",
  },
  {
    id: "EL-SET-011",
    feature: "SET",
    name: "Data count — history",
    selector: "[data-count-history]",
    component: "features/settings/components/SettingsDrawer.tsx",
  },
  {
    id: "EL-SET-012",
    feature: "SET",
    name: "Keyboard shortcuts modal",
    selector: '[data-testid="keyboard-shortcuts-modal"]',
    testId: "keyboard-shortcuts-modal",
    planned: true,
    component: "features/settings/components/KeyboardShortcutsModal.tsx",
  },
  {
    id: "EL-SET-013",
    feature: "SET",
    name: "Proxy URL input",
    selector: '[placeholder="http://proxy:8080"]',
    component: "features/settings/components/SettingsDrawer.tsx",
  },
  {
    id: "EL-SET-014",
    feature: "SET",
    name: "Follow Redirects switch",
    selector: "text=Follow Redirects",
    component: "features/settings/components/SettingsDrawer.tsx",
  },
  {
    id: "EL-SET-015",
    feature: "SET",
    name: "SSL Verification switch",
    selector: "text=SSL Verification",
    component: "features/settings/components/SettingsDrawer.tsx",
  },
  {
    id: "EL-SET-016",
    feature: "SET",
    name: "Clear History",
    selector: 'button:has-text("Clear History")',
    component: "features/settings/components/SettingsDrawer.tsx",
  },
  {
    id: "EL-SET-017",
    feature: "SET",
    name: "Clear Drafts",
    selector: 'button:has-text("Clear Drafts")',
    component: "features/settings/components/SettingsDrawer.tsx",
  },
  {
    id: "EL-SET-018",
    feature: "SET",
    name: "Clear All Data",
    selector: 'button:has-text("Clear All Data")',
    component: "features/settings/components/SettingsDrawer.tsx",
  },
  {
    id: "EL-SET-019",
    feature: "SET",
    name: "Check for updates",
    selector: 'button:has-text("Check")',
    component: "features/settings/components/SettingsDrawer.tsx",
  },
  {
    id: "EL-SET-020",
    feature: "SET",
    name: "Settings Requests tab (label)",
    selector: 'button:has-text("Requests")',
    component: "features/settings/components/SettingsDrawer.tsx",
  },
  {
    id: "EL-SET-021",
    feature: "SET",
    name: "Settings Data tab (label)",
    selector: 'button:has-text("Data")',
    component: "features/settings/components/SettingsDrawer.tsx",
  },
  {
    id: "EL-SET-022",
    feature: "SET",
    name: "Data count — collections",
    selector: '[data-testid="data-count-collections"]',
    testId: "data-count-collections",
    component: "features/settings/components/SettingsDrawer.tsx",
  },
];

export const mcpElements: TestElement[] = [
  {
    id: "EL-MCP-001",
    feature: "MCP",
    name: "MCP panel root",
    selector: '[data-testid="mcp-panel"]',
    testId: "mcp-panel",
    component: "features/mcp/components/McpPanel.tsx",
    notes: "Bench retained; UI shows coming-soon in production",
  },
  {
    id: "EL-MCP-002",
    feature: "MCP",
    name: "MCP connect URL input",
    selector: '[data-testid="mcp-connect-url"]',
    testId: "mcp-connect-url",
    component: "features/mcp/components/McpPanel.tsx",
  },
  {
    id: "EL-MCP-003",
    feature: "MCP",
    name: "MCP connect button",
    selector: '[data-testid="mcp-connect-btn"]',
    testId: "mcp-connect-btn",
    component: "features/mcp/components/McpPanel.tsx",
  },
  {
    id: "EL-MCP-004",
    feature: "MCP",
    name: "MCP call tool button",
    selector: '[data-testid="mcp-call-btn"]',
    testId: "mcp-call-btn",
    component: "features/mcp/components/McpPanel.tsx",
  },
  {
    id: "EL-MCP-005",
    feature: "MCP",
    name: "MCP result pane",
    selector: '[data-testid="mcp-result"]',
    testId: "mcp-result",
    component: "features/mcp/components/McpPanel.tsx",
  },
  {
    id: "EL-MCP-006",
    feature: "MCP",
    name: "MCP error banner",
    selector: '[data-testid="mcp-error"]',
    testId: "mcp-error",
    component: "features/mcp/components/McpPanel.tsx",
  },
  {
    id: "EL-MCP-007",
    feature: "MCP",
    name: "MCP OAuth authorize",
    selector: '[data-testid="mcp-authorize-btn"]',
    testId: "mcp-authorize-btn",
    component: "features/mcp/components/McpPanel.tsx",
  },
  {
    id: "EL-MCP-008",
    feature: "MCP",
    name: "MCP forget auth",
    selector: '[data-testid="mcp-forget-auth-btn"]',
    testId: "mcp-forget-auth-btn",
    component: "features/mcp/components/McpSidebar.tsx",
  },
  {
    id: "EL-MCP-009",
    feature: "MCP",
    name: "MCP raw args",
    selector: '[data-testid="mcp-raw-args"]',
    testId: "mcp-raw-args",
    component: "features/mcp/components/McpPanel.tsx",
  },
];
