import type { TestElement } from "../types.js";

export const tabElements: TestElement[] = [
  {
    id: "EL-TAB-001",
    feature: "TAB",
    name: "Tab strip list",
    selector: '[role="tablist"]',
    component: "features/rest/request-builder/components/TabStrip.tsx",
  },
  {
    id: "EL-TAB-002",
    feature: "TAB",
    name: "Active request tab",
    selector: '[role="tab"][aria-selected="true"]',
    component: "features/rest/request-builder/components/TabStrip.tsx",
  },
  {
    id: "EL-TAB-003",
    feature: "TAB",
    name: "New request tab button",
    selector: '[title="New request"]',
    component: "features/rest/request-builder/components/TabStrip.tsx",
  },
  {
    id: "EL-TAB-004",
    feature: "TAB",
    name: "Close tab button",
    selector: '[title="Close tab"]',
    component: "features/rest/request-builder/components/TabStrip.tsx",
  },
  {
    id: "EL-TAB-005",
    feature: "TAB",
    name: "Scroll tabs left",
    selector: '[title="Scroll tabs left"]',
    component: "features/rest/request-builder/components/TabStrip.tsx",
  },
  {
    id: "EL-TAB-006",
    feature: "TAB",
    name: "Scroll tabs right",
    selector: '[title="Scroll tabs right"]',
    component: "features/rest/request-builder/components/TabStrip.tsx",
  },
  {
    id: "EL-TAB-007",
    feature: "TAB",
    name: "Tab rename input",
    selector: '[data-testid="tab-rename-input"]',
    testId: "tab-rename-input",
    planned: true,
    component: "features/rest/request-builder/components/TabStrip.tsx",
  },
  {
    id: "EL-TAB-008",
    feature: "TAB",
    name: "Tab context menu",
    selector: '[data-testid="tab-context-menu"]',
    testId: "tab-context-menu",
    component: "features/rest/request-builder/components/TabStrip.tsx",
  },
  {
    id: "EL-TAB-009",
    feature: "TAB",
    name: "Context menu — Duplicate Request",
    selector: '[data-testid="tab-context-menu"] [role="menuitem"]:has-text("Duplicate Request")',
    component: "features/rest/request-builder/components/TabStrip.tsx",
  },
  {
    id: "EL-TAB-010",
    feature: "TAB",
    name: "Context menu — Close Other Tabs",
    selector: '[data-testid="tab-context-menu"] [role="menuitem"]:has-text("Close Other Tabs")',
    component: "features/rest/request-builder/components/TabStrip.tsx",
  },
  {
    id: "EL-TAB-011",
    feature: "TAB",
    name: "Context menu — Close All Tabs",
    selector: '[data-testid="tab-context-menu"] [role="menuitem"]:has-text("Close All Tabs")',
    component: "features/rest/request-builder/components/TabStrip.tsx",
  },
  {
    id: "EL-TAB-012",
    feature: "TAB",
    name: "Context menu — New Request",
    selector: '[data-testid="tab-context-menu"] [role="menuitem"]:has-text("New Request")',
    component: "features/rest/request-builder/components/TabStrip.tsx",
  },
  {
    id: "EL-TAB-013",
    feature: "TAB",
    name: "Tab at index 0",
    selector: '[role="tablist"][aria-label="Workspace tabs"] [role="tab"]:nth-child(1)',
    component: "features/rest/request-builder/components/TabStrip.tsx",
  },
  {
    id: "EL-TAB-014",
    feature: "TAB",
    name: "Context menu — Close Tab",
    selector: '[data-testid="tab-context-menu"] [role="menuitem"]:has-text("Close Tab")',
    component: "features/rest/request-builder/components/TabStrip.tsx",
  },
  {
    id: "EL-TAB-015",
    feature: "TAB",
    name: "Scroll tabs left",
    selector: '[aria-label="Scroll tabs left"]',
    component: "features/rest/request-builder/components/TabStrip.tsx",
  },
  {
    id: "EL-TAB-016",
    feature: "TAB",
    name: "Scroll tabs right",
    selector: '[aria-label="Scroll tabs right"]',
    component: "features/rest/request-builder/components/TabStrip.tsx",
  },
];

export const requestBuilderElements: TestElement[] = [
  {
    id: "EL-RB-001",
    feature: "RB",
    name: "URL input",
    selector: '[data-testid="url-input"]:visible',
    testId: "url-input",
    component: "features/rest/request-builder/components/UrlBar.tsx",
    notes: "Scope :visible — inactive tabs stay mounted",
  },
  {
    id: "EL-RB-002",
    feature: "RB",
    name: "Method dropdown trigger",
    selector: '[data-testid="method-trigger"]:visible',
    testId: "method-trigger",
    component: "features/rest/request-builder/components/MethodSelector.tsx",
  },
  {
    id: "EL-RB-003",
    feature: "RB",
    name: "Method option GET",
    selector: '[data-testid="method-option-GET"]',
    testId: "method-option-GET",
    component: "features/rest/request-builder/components/MethodOption.tsx",
  },
  {
    id: "EL-RB-004",
    feature: "RB",
    name: "Method option POST",
    selector: '[data-testid="method-option-POST"]',
    testId: "method-option-POST",
    component: "features/rest/request-builder/components/MethodOption.tsx",
  },
  {
    id: "EL-RB-005",
    feature: "RB",
    name: "Method option PUT",
    selector: '[data-testid="method-option-PUT"]',
    testId: "method-option-PUT",
    component: "features/rest/request-builder/components/MethodOption.tsx",
  },
  {
    id: "EL-RB-006",
    feature: "RB",
    name: "Method option PATCH",
    selector: '[data-testid="method-option-PATCH"]',
    testId: "method-option-PATCH",
    component: "features/rest/request-builder/components/MethodOption.tsx",
  },
  {
    id: "EL-RB-007",
    feature: "RB",
    name: "Method option DELETE",
    selector: '[data-testid="method-option-DELETE"]',
    testId: "method-option-DELETE",
    component: "features/rest/request-builder/components/MethodOption.tsx",
  },
  {
    id: "EL-RB-008",
    feature: "RB",
    name: "Method option HEAD",
    selector: '[data-testid="method-option-HEAD"]',
    testId: "method-option-HEAD",
    component: "features/rest/request-builder/components/MethodOption.tsx",
  },
  {
    id: "EL-RB-009",
    feature: "RB",
    name: "Method option OPTIONS",
    selector: '[data-testid="method-option-OPTIONS"]',
    testId: "method-option-OPTIONS",
    component: "features/rest/request-builder/components/MethodOption.tsx",
  },
  {
    id: "EL-RB-010",
    feature: "RB",
    name: "Method option QUERY",
    selector: '[data-testid="method-option-QUERY"]',
    testId: "method-option-QUERY",
    component: "features/rest/request-builder/components/MethodOption.tsx",
  },
  {
    id: "EL-RB-011",
    feature: "RB",
    name: "Send button",
    selector: "[data-send-btn]",
    component: "features/rest/request-builder/components/UrlBar.tsx",
    notes: "Uses data-send-btn attribute",
  },
  {
    id: "EL-RB-012",
    feature: "RB",
    name: "Send error banner",
    selector: '[data-testid="send-error"]',
    testId: "send-error",
    component: "features/rest/request-builder/components/UrlBarStatusLine.tsx",
  },
  {
    id: "EL-RB-013",
    feature: "RB",
    name: "Environment token chip in URL",
    selector: '[data-testid="env-token"]',
    testId: "env-token",
    component: "features/rest/request-builder/components/TokenChip.tsx",
  },
  {
    id: "EL-RB-014",
    feature: "RB",
    name: "Params editor tab",
    selector: '[data-testid="editor-tab-params"]',
    testId: "editor-tab-params",
    component: "features/rest/request-builder/components/RequestEditor.tsx",
  },
  {
    id: "EL-RB-015",
    feature: "RB",
    name: "Auth editor tab",
    selector: '[data-testid="editor-tab-auth"]',
    testId: "editor-tab-auth",
    component: "features/rest/request-builder/components/RequestEditor.tsx",
  },
  {
    id: "EL-RB-016",
    feature: "RB",
    name: "Headers editor tab",
    selector: '[data-testid="editor-tab-headers"]',
    testId: "editor-tab-headers",
    component: "features/rest/request-builder/components/RequestEditor.tsx",
  },
  {
    id: "EL-RB-017",
    feature: "RB",
    name: "Body editor tab",
    selector: '[data-testid="editor-tab-body"]',
    testId: "editor-tab-body",
    component: "features/rest/request-builder/components/RequestEditor.tsx",
  },
  {
    id: "EL-RB-018",
    feature: "RB",
    name: "Param key input (row 0)",
    selector: '[data-testid="param-key-0"]',
    testId: "param-key-0",
    component: "shared/ui/KeyValueEditor/KeyValueEditor.tsx",
  },
  {
    id: "EL-RB-019",
    feature: "RB",
    name: "Param value input (row 0)",
    selector: '[data-testid="param-value-0"]',
    testId: "param-value-0",
    component: "shared/ui/KeyValueEditor/KeyValueEditor.tsx",
  },
  {
    id: "EL-RB-020",
    feature: "RB",
    name: "Header key input (row 0)",
    selector: '[data-testid="header-key-0"]',
    testId: "header-key-0",
    component: "shared/ui/KeyValueEditor/KeyValueEditor.tsx",
  },
  {
    id: "EL-RB-021",
    feature: "RB",
    name: "Header value input (row 0)",
    selector: '[data-testid="header-value-0"]',
    testId: "header-value-0",
    component: "shared/ui/KeyValueEditor/KeyValueEditor.tsx",
  },
  {
    id: "EL-RB-022",
    feature: "RB",
    name: "Add param button",
    selector: 'button:has-text("Add param")',
    component: "shared/ui/KeyValueEditor/KeyValueEditor.tsx",
  },
  {
    id: "EL-RB-023",
    feature: "RB",
    name: "Add header button",
    selector: 'button:has-text("Add header")',
    component: "shared/ui/KeyValueEditor/KeyValueEditor.tsx",
  },
  {
    id: "EL-RB-024",
    feature: "RB",
    name: "Body word wrap toggle",
    selector: '[data-testid="body-wrap-toggle"]',
    testId: "body-wrap-toggle",
    component: "features/rest/request-builder/components/BodyEditor.tsx",
  },
  {
    id: "EL-RB-025",
    feature: "RB",
    name: "Body find bar",
    selector: '[data-testid="body-find"]',
    testId: "body-find",
    component: "shared/ui/FindBar.tsx",
  },
  {
    id: "EL-RB-026",
    feature: "RB",
    name: "Empty request state — Load a sample",
    selector: '[data-testid="empty-try-example"]',
    testId: "empty-try-example",
    component: "features/rest/request-builder/components/EmptyRequestState.tsx",
  },
  {
    id: "EL-RB-027",
    feature: "RB",
    name: "Auth type selector",
    selector: '[data-testid="auth-type-select"]',
    testId: "auth-type-select",
    planned: true,
    component: "features/environments/components/VarAuthEditor.tsx",
  },
  {
    id: "EL-RB-028",
    feature: "RB",
    name: "Body type — JSON",
    selector: '[data-testid="body-type-json"]',
    testId: "body-type-json",
    planned: true,
    component: "features/rest/request-builder/components/BodyTypeSelector.tsx",
  },
  {
    id: "EL-RB-029",
    feature: "RB",
    name: "Body type — Form Data",
    selector: '[data-testid="body-type-form-data"]',
    testId: "body-type-form-data",
    planned: true,
    component: "features/rest/request-builder/components/BodyTypeSelector.tsx",
  },
  {
    id: "EL-RB-030",
    feature: "RB",
    name: "Body type — URL Encoded",
    selector: '[data-testid="body-type-urlencoded"]',
    testId: "body-type-urlencoded",
    planned: true,
    component: "features/rest/request-builder/components/BodyTypeSelector.tsx",
  },
  {
    id: "EL-RB-031",
    feature: "RB",
    name: "Body type — Binary",
    selector: '[data-testid="body-type-binary"]',
    testId: "body-type-binary",
    planned: true,
    component: "features/rest/request-builder/components/BodyTypeSelector.tsx",
  },
  {
    id: "EL-RB-032",
    feature: "RB",
    name: "Body JSON textarea",
    selector: '[data-testid="body-json-input"]',
    testId: "body-json-input",
    planned: true,
    component: "features/rest/request-builder/components/BodyEditor.tsx",
  },
  {
    id: "EL-RB-033",
    feature: "RB",
    name: "Body type — None",
    selector: 'button:has-text("None")',
    component: "features/rest/request-builder/components/BodyTypeSelector.tsx",
  },
  {
    id: "EL-RB-034",
    feature: "RB",
    name: "Body type — Raw",
    selector: 'button:has-text("Raw")',
    component: "features/rest/request-builder/components/BodyTypeSelector.tsx",
  },
  {
    id: "EL-RB-035",
    feature: "RB",
    name: "Format JSON button",
    selector: 'button:has-text("Format")',
    component: "features/rest/request-builder/components/BodyTypeSelector.tsx",
  },
  {
    id: "EL-RB-036",
    feature: "RB",
    name: "Auth bearer token input",
    selector: '[placeholder="eyJhbGciOiJIUzI1NiIs..."]',
    component: "features/environments/components/VarAuthEditor.tsx",
  },
  {
    id: "EL-RB-037",
    feature: "RB",
    name: "Auth basic username",
    selector: '[placeholder="username"]',
    component: "features/environments/components/VarAuthEditor.tsx",
  },
  {
    id: "EL-RB-038",
    feature: "RB",
    name: "Auth basic password",
    selector: '[placeholder="password"]',
    component: "features/environments/components/VarAuthEditor.tsx",
  },
  {
    id: "EL-RB-039",
    feature: "RB",
    name: "Auth API key name",
    selector: '[placeholder="X-API-Key"]',
    component: "features/environments/components/VarAuthEditor.tsx",
  },
  {
    id: "EL-RB-040",
    feature: "RB",
    name: "Auth API key value",
    selector: '[placeholder="api_key_value"]',
    component: "features/environments/components/VarAuthEditor.tsx",
  },
  {
    id: "EL-RB-041",
    feature: "RB",
    name: "Param row enable checkbox",
    selector: '[aria-label="Disable row"]',
    component: "shared/ui/KeyValueEditor/KeyValueEditor.tsx",
  },
  {
    id: "EL-RB-042",
    feature: "RB",
    name: "Body find input",
    selector: '[data-testid="body-find-input"]',
    testId: "body-find-input",
    component: "shared/ui/FindBar.tsx",
  },
  {
    id: "EL-RB-043",
    feature: "RB",
    name: "Auth type native select",
    selector: 'select, [role="combobox"]',
    component: "features/environments/components/VarAuthEditor.tsx",
    notes: "Type field: No Auth / Bearer Token / Basic Auth / API Key",
  },
  {
    id: "EL-RB-044",
    feature: "RB",
    name: "Remove param/header row",
    selector: '[aria-label="Remove row"]',
    component: "shared/ui/KeyValueEditor/KeyValueEditor.tsx",
  },
  {
    id: "EL-RB-045",
    feature: "RB",
    name: "Binary file pane",
    selector: '[data-testid="body-binary-pane"]',
    testId: "body-binary-pane",
    planned: true,
    component: "features/rest/request-builder/components/BinaryFilePane.tsx",
  },
];
